### ISSUE TITLE
能否在每一行增加hover 时 显示button操作按钮

### ISSUE THREAD

**Issue by q59188** [x-extends/vxe-table#1006]
**（必填）这个需求解决了什么问题：**
如果有大量操作按钮存在，单个cell不美观

**建议的 API 是什么样的：**
鼠标滑动显示按钮
![image](https://user-images.githubusercontent.com/23050383/90303858-7e3c1d00-dee4-11ea-8234-bdbcbebe9b9b.png)

**是否已有其他不错的替代方案：**
暂无

**Comment by Titans1001** [comment]
这个可以通过自定义渲染器搞定

**Comment by dahu0712** [comment]
想问下是哪个字段属性

> 这个可以通过自定义渲染器搞定
