### ISSUE TITLE
editconfig 的mode是cell的时候，必填校验失败

### ISSUE THREAD

**Issue by liang-louis** [x-extends/vxe-table#1019]
**（必填）请填写问题描述或截图：**
可编辑表格的校验，当有一个字段为必填项。设置了
`{ required: true, message: '该项不能为空' }`
编辑的数据不是处在数据的第一条的时候（比如第3条），表单里没有值。点击按钮执行校验方法，会提示校验通过（应该校验不通过的，因为有必填项为空）。官网例子也是如此

**（必填）请填在线链接：**
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/rowValid

**（必填）请填写期望的结果：**
希望能改善这个情况
**（必填）请填写以下信息：**

- OS:win 10
- Browser: chrome
- vue: 2.6+
- vxe-table: 2.9.17

**Comment by liang-louis** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/cellValid
这个是官网的案例
editconfig 的mode是cell的时候
`
editConfig: {
        trigger: 'click',
        mode: 'cell',
        showStatus: true,
        showIcon: false,
        activeMethod: this.activeCellMethod
      }
`

**Comment by tomsure** [comment]
我也遇到了，必填验证失效

**Comment by liang-louis** [comment]
@xuliangzhan  这个修复了吗

**Comment by xuliangzhan** [comment]
> @xuliangzhan 这个修复了吗

建议使用有效的在线链接来描述问题

**Comment by liang-louis** [comment]
> > @xuliangzhan 这个修复了吗
> 
> 建议使用有效的在线链接来描述问题

第二个链接就是 官方的例子也是不对的
