### ISSUE TITLE
希望传入footer-method 函数的参数能添加当前（$grid)

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1025]
**（必填）这个需求解决了什么问题：**
写通用函数的时候，可以快速获取当前grid，以便做相应的处理。

**建议的 API 是什么样的：**
footer-method

Function({$grid,columns, data}) 

**是否已有其他不错的替代方案：**
无

**Comment by Titans1001** [comment]
我已经加入已经合并，下个npm包版本发布更新即可

**Comment by jianliulin** [comment]
谢谢！！
