### ISSUE TITLE
2.9.16导致的一个 校验不兼容本问题

### ISSUE THREAD

**Issue by anyclub** [x-extends/vxe-table#1028]
**（必填）请填写问题描述或截图：**
之前使用2.9.15时能正常完成
2.9.17该方案报错
代码省略,简要描述如下

1. 创建一个可需要校验的可编辑表格
2. 通过push 加入一空行
3. 点击按钮,调用提供的validate校验方法

2.9.15 能正常校验到该行必填项错误,并能自动获得焦点,弹出tooltip提示
2.9.17 试过各类方案, 调整参数, 仅能catch到err信息,但无法自动获得焦点弹出提示

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-ceshide-demo-forked-lt5m4?file=/src/views/Demo1.vue
大致验证发现, 2.9.16-beta.5为最后一个可行版本

**（必填）请填写期望的结果：**
新版可校验空行,且能正常弹出tooltip信息等

**（必填）请填写以下信息：**

- OS: WIN10
- Browser:  EDGE
- vue: 2.6.11
- vxe-table: 2.9.17

**Comment by xuliangzhan** [comment]
校验和CRUD管理是属于同一种行为，只对临时数据有效，只有 insert 或 update 状态发生变化的数据才能触发校验，其他的数据是不会被校验的；如果打算全量校验，第一个参数为true则全量校验: xTable.validate(true)

v2版本中也可以通过全局设置来回退为已废弃的行为：
https://codesandbox.io/s/vxe-table-ceshide-demo-forked-qzhlk
```javascript
VXETable.setup({
  validFullData: 'obsolete'
})
```

**Comment by anyclub** [comment]
https://codesandbox.io/s/vxe-table-ceshide-demo-forked-q50v9?file=/src/views/Demo1.vue
2.9.17 开启validate(true)后 仍然无法完成自动提示等功能
不过 2.9.19 已经可以了  
谢谢解答
