### ISSUE TITLE
时隔多个版本 recalculate 再次出现问题

### ISSUE THREAD

**Issue by huoshidehua** [x-extends/vxe-table#1035]
**（必填）请填写问题描述或截图：**
![image](https://user-images.githubusercontent.com/8519297/91792176-e5313400-ec4f-11ea-8b86-313cd82695fb.png)

**（必填）请填在线链接：**
http://jsrun.net/PPvKp/edit

**（必填）请填写期望的结果：**
recalculate 正常运作
**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6.10+
- vxe-table: 2.9.19

**Comment by xuliangzhan** [comment]
应该使用 vue 的 $nextTick 回调里面去调用 recalculate 方法，避免还没渲染完成就去刷新导致有可能出现无效

**Comment by huoshidehua** [comment]
嗯发现了
