### ISSUE TITLE
组合类型row-id

### ISSUE THREAD

**Issue by joyfun** [x-extends/vxe-table#1039]
**（必填）这个需求解决了什么问题：**
table 的数据 是 [{group:"a",name:"name1"},{group:"a",name:"name2"},{group:"b",name:"name1"},{group:"b",name:"name2"}{group:"c",name:"name1"}]
如果单独设置 row-id="group" 或者name都会出现重复  能不能 设置组合的row-id "group+'_'+name"?
**建议的 API 是什么样的：**
row-id能够支持多列组合
**是否已有其他不错的替代方案：**
？

**Comment by xlz26296** [comment]
主键没有多个的概念，同一个表中必须是唯一的

**Comment by CoderSunnyLau** [comment]
你可以自己给这些数据加个主键 rowId，比如：
```
tableData.forEach(item => {
    item.rowId = item.group + item.name;
});
```
