### ISSUE TITLE
树形表格，要实现删除全部子节点，但是不删除父节点的需求，有好的办法实现么？

### ISSUE THREAD

**Issue by lguos9960** [x-extends/vxe-table#1040]
**（必填）请填写问题描述或截图：**
![image](https://user-images.githubusercontent.com/67782322/91987433-a048f280-ed60-11ea-9306-fa2ef5583087.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-ceshide-demo-forked-nwbzb?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
proxy-config 增删改查 的时候，标记删除项， checkbox 勾选某个节点的所有子节点的时候，父节点不应该被选中 ！（删除的时候，只删除子节点，不删除父节点）

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6.10+
- vxe-table: 2.9.2

**Comment by CoderSunnyLau** [comment]
可以通过 checkStrictly 设置父子节点不互相关联。

**Comment by lguos9960** [comment]
> 可以通过 checkStrictly 设置父子节点不互相关联。

删除父节点，需要吧子节点也删除，删除子节点的时候不删除父节点，checkStrictly 设置为true,父子不关联，不能满足需求了。

**Comment by lguos9960** [comment]
现在要实现删除多个子节点，但是不删除父节点的需求，有好的办法实现么？求教@xuliangzhan

**Comment by MiracleCsf** [comment]
@lguos9960 请问这个问题解决了么，我也遇到这个问题了

**Comment by abcdongyuhua** [comment]
> 
设置了  不生效

**Comment by abcdongyuhua** [comment]
> 可以通过 checkStrictly 设置父子节点不互相关联。

设置以后不生效
