### ISSUE TITLE
loadData加载数据，checkbox-config 设置 reserve: true,checkField:'checked'，全选事件 返回reserves是空数组

### ISSUE THREAD

**Issue by liang-louis** [x-extends/vxe-table#1044]
**（必填）请填写问题描述或截图：**
在线 demo操作步骤
1、vxe-table 使用loadData 加载数据。 `checkbox-config` 设置为 `:checkbox-config="{reserve: true,checkField:'checked'}"`
2、查询 表单输入‘**大宋**’， 点击全选。然后再搜 ‘**小程序**，再点击全选，这时 `selectAllEvent`的参数 `{records, reserves}`.只有`records` 返回当前的数据。`reserves` 始终返回空数组

**（必填）请填在线链接：**
http://cbbgjj.bgsz.net/vxe/
打开链接，代码为复现代码

**（必填）请填写期望的结果：**
希望可以返回已选择的数据

**（必填）请填写以下信息：**

- OS:  win10
- Browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.19

**Comment by liang-louis** [comment]
@xuliangzhan

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试
