### ISSUE TITLE
Vxe-table size="mini" 在几百行数据的情况下 overFlow错误 导致内容不能折行以及超出被隐藏

### ISSUE THREAD

**Issue by adoin** [x-extends/vxe-table#1046]
**（必填）请填写问题描述或截图：**

![bug1](https://user-images.githubusercontent.com/20517172/92373780-6d707700-f131-11ea-9db8-13e28643a82a.png)
![bug2](https://user-images.githubusercontent.com/20517172/92373804-73665800-f131-11ea-936c-6dcd2de1a9f4.png)

**（必填）请填在线链接：**
[https://codesandbox.io/s/vxe-table-ceshide-demo-forked-nvk87?file=/src/views/Demo1.vue](url)
**（必填）请填写期望的结果：**
能和少量数据的情况下一样正常显示

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6+
- vxe-table: 2.9.19

**Comment by adoin** [comment]
请点击代码产出的页面底部 的‘测试大量数据 ’按钮

**Comment by xlz26296** [comment]
文档有说明
![image](https://user-images.githubusercontent.com/34787386/92376185-ca216100-f134-11ea-8a12-fd08d1b23591.png)

**Comment by adoin** [comment]
> 文档有说明
> ![image](https://user-images.githubusercontent.com/34787386/92376185-ca216100-f134-11ea-8a12-fd08d1b23591.png)

???sample code 在那 哪有加这几个？

**Comment by xlz26296** [comment]
> > 文档有说明
> > ![image](https://user-images.githubusercontent.com/34787386/92376185-ca216100-f134-11ea-8a12-fd08d1b23591.png)
> 
> ???height去掉也是一样 99条就正常100 就不行

你按照文档的说明去设置就可以了，关闭高性能的虚拟滚动用来换取动态行高，加上这个就行了：:scroll-y="{gt: -1}"

**Comment by adoin** [comment]
> > > 文档有说明
> > > ![image](https://user-images.githubusercontent.com/34787386/92376185-ca216100-f134-11ea-8a12-fd08d1b23591.png)
> > 
> > 
> > ???height去掉也是一样 99条就正常100 就不行
> 
> 你按照文档的说明去设置就可以了，关闭高性能的虚拟滚动用来换取动态行高，加上这个就行了：:scroll-y="{gt: -1}"

解决了 文档没找到。。多谢兄台！
