### ISSUE TITLE
2.9.17 表格不校验

### ISSUE THREAD

**Issue by qhhuang** [x-extends/vxe-table#1051]
**（必填）请填写问题描述或截图：**
2.9.11正常
升级到2.9.17 表格不校验

**（必填）请填在线链接：**
https://jsrun.net/LrLKp/edit 目前引用的是2.9.17 不能校验,改成2.9.11就能校验

**（必填）请填写期望的结果：**
校验

**（必填）请填写以下信息：**

- OS: Mac OS 10.15.6 (19G2021)
- Browser: chrom
- vue: 2.6.10
- vxe-table: 2.9.11/2.9.17

**Comment by qhhuang** [comment]
2.9.15可以 
2.9.16版本开始不行的

**Comment by xlz26296** [comment]
#1028
