### ISSUE TITLE
树形表格+行样式渲染，显示错误

### ISSUE THREAD

**Issue by Saszr** [x-extends/vxe-table#1052]
**（必填）请填写问题描述或截图：**
树形表格+行样式渲染
row-class-name 里面的 rowIndex 
子树和外层相同
![image](https://user-images.githubusercontent.com/22406550/92562389-7b94d380-f2a8-11ea-854d-57b79d6b3383.png)

**（必填）请填在线链接：**
http://jsrun.net/BrLKp/edit

**（必填）请填写期望的结果：**
只外层第一行加粗

row-class-name 区分层级 或者 能点击展开的时候阻止 row-class-name 事件

**（必填）请填写以下信息：**

- OS: win10
- Browser: edge
- vue: 2.6.11
- vxe-table: 2.9.19

**Comment by xuliangzhan** [comment]
树只有第一层拥有索引 rowIndex，子节点没有索引的
