### ISSUE TITLE
N多个模态窗口 ESC按键   逐层关闭和全部一键关闭

### ISSUE THREAD

**Issue by alexjlw** [x-extends/vxe-table#1058]
**（必填）这个需求解决了什么问题：**
多层弹出窗 下 怎么使用ESC键  逐层关闭 窗口

**建议的 API 是什么样的：**
加个参数   如  closeCurr:true 表示每次关闭当前的最上层窗口
False 默认全部关闭

**是否已有其他不错的替代方案：**
无

**Comment by xuliangzhan** [comment]
没看明白，目前不就是这样吗？

**Comment by alexjlw** [comment]
现在是多个模态框弹出 ，按以下esc  会全部关闭
