### ISSUE TITLE
吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/

### ISSUE THREAD

**Issue by summerPt** [x-extends/vxe-table#1063]
**（必填）这个需求解决了什么问题：**
吐槽下吧
吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/

**建议的 API 是什么样的：**
吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/

**是否已有其他不错的替代方案：**
吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/

**Comment by xlz26296** [comment]
晕死，大概看了一下代码，还以为有更好的实现，原来是个这么玩的，果然人不要脸无敌了啊
[u-table](https://unpkg.com/pl-table/) 复制 element-ui
[ux-grid](https://unpkg.com/plxy-grid/) 复制 vxe-table，改个 class 这种做法不是感觉不太高级，要不要教你一种更高级的😆

**Comment by summerPt** [comment]
@xlz26296 麻瓜 需要你教？真没看上你。不懂别瞎JB BB  比你这个好  弱鸡，害你吗收费，至少人家热情  咋的  不像你家  麻瓜开源 还你吗收费  问问题  草拟吗

**Comment by summerPt** [comment]
@xlz26296 老子只知道 人家解决老子问题了。你家不热情 收费 多简单的  傻逼zzz

**Comment by 850036165** [comment]
憨子，人家开源又没让你用，还教，作者是你爹妈吗为什么要教你，欠你的？开口闭口一个老子，“但是遇到问题感觉没人能帮助”，蠢猪，自己不会看文档？这点都看不懂你还写个几把毛的代码滚回家种田吧废物

**Comment by MellowCo** [comment]
你不要钱吃饭是吧 人家又没强制你 人家开源是你爹啊 什么都要惯着你

**Comment by summerPt** [comment]
@850036165 你简直没吧老子笑死。咋的 不教 不解决问题 开你妈的源呢？咋的   问个问题还需要收费。怎么啦 我只管谁解决了我的问题。服务好，我换个库怎么啦。我TM是他先骂我的 好吗。我只说了 换个库，咋的 哪家好  服务好用哪家，我只管谁解决我的问题。我管他插件是怎么来的？他就在哪里BB   以为自己多牛B 的 ！

**Comment by summerPt** [comment]
@M
呵呵 笑死    你好好看  我提得问题  吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/。  我只管谁服务好 免费。我只是换个库。我没骂他。我说的是事实！

**Comment by 850036165** [comment]
@summerPt 我要是开源一坨屎，你是不是还要让我教你怎么吃？

**Comment by summerPt** [comment]
@850036165 笑了 没喊你教。不你教 我就换呗， 找个可以回答的 不就完了，市面上就像UI库一样。那么多  ，找个好讨论的，至少不像这个技术支持收费  哈哈哈，不跟你BB了

**Comment by liliping997** [comment]
确实vxe服务不行哈哈。顶你个

**Comment by xlz26296** [comment]
@summerPt 什么玩意，还骂人，还找账号来刷什么存在感，要打广告也不用这么无耻的到各个开源库去打广告，还在不要脸的自娱自乐，你既然这么牛咋不上天，谁有这个时间搭理你

**Comment by summerPt** [comment]
@xlz26296 哇哦 你简直没笑死爸爸  弱鸡 没看上你！

**Comment by summerPt** [comment]
@xlz26296 对我而言你简直在放屁 懂吗  弟弟！毫无证据  憨批  瞎BB 还会啥！

**Comment by tengos13** [comment]
@summerPt 顶

**Comment by tengos13** [comment]
@summerPt 顶

**Comment by ZhongHongLi** [comment]
> **（必填）这个需求解决了什么问题：**
> 吐槽下吧
> 吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/
> 
> **建议的 API 是什么样的：**
> 吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/
> 
> **是否已有其他不错的替代方案：**
> 吐槽下吧，首先是使用了vxe很久了，但是遇到问题感觉没人能帮助，且作者还是为了赚钱，所以搞了个需要收费的东西。所以我失望了。所以我换了一个解决表格卡顿的库了 希望对大家有帮助吧、:https://www.umyui.com/

感觉作者真的挺给力的。。。赞不是广告我是转过去的用户

**Comment by someoneInGit** [comment]
你以为在国内做开源和国外一样呢

**Comment by fh345392977** [comment]
感觉作者更新挺积极啊，之前反馈bug都能很快响应。

你如果比较着急的话也可以fork自己改一下，而且他的pro版那些属性，大部分人都用不上吧。

**Comment by fenghaocheng** [comment]
umyui 说好的前端交流群，在里面问一下vxe-table的东西就踢我出群，垃圾东西还开源，玩不起别建前端交流群，垃圾umyui。

**Comment by kooriookami** [comment]
> umyui 说好的前端交流群，在里面问一下vxe-table的东西就踢我出群，垃圾东西还开源，玩不起别建前端交流群，垃圾umyui。

我也被踢了
