### ISSUE TITLE
更新最新版本後，「篩選」功能失效

### ISSUE THREAD

**Issue by HenryLin0914** [x-extends/vxe-table#1068]
**（必填）请填写问题描述或截图：**
更新到最新版後篩選功能失效如下圖

1. 點選=>「實現內容的篩選」
2. 按下篩選後，不會有反應

![image](https://user-images.githubusercontent.com/66756295/93725601-18c60500-fbe3-11ea-8acd-b93cca12ed63.png)

**（必填）请填在线链接：**
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/filter

**（必填）请填写期望的结果：**
期待大大修正

**（必填）请填写以下信息：**

- OS: windows7
- Browser: chrome最新版
- vue: 2.6+
- vxe-table: 最新版本

**Comment by HenryLin0914** [comment]
附上我使用的模板: https://jsfiddle.net/fh5rvsbL/

**Comment by xuliangzhan** [comment]
应该通过官网的 api 去使用而不是直接使用示例，简单示例仅用于演示，并不具备功能，渲染器的功能是自行实现的

**Comment by HenryLin0914** [comment]
> 应该通过官网的 api 去使用而不是直接使用示例，简单示例仅供参考，并不具备任何功能，渲染器的功能都是自行实现的

實現位置: https://jsfiddle.net/h0mfk7vs/

點選name進行過濾

本來舊版本是OK可以work

**Comment by xuliangzhan** [comment]
> > 应该通过官网的 api 去使用而不是直接使用示例，简单示例仅供参考，并不具备任何功能，渲染器的功能都是自行实现的
> 
> 實現位置: https://jsfiddle.net/h0mfk7vs/
> 
> 點選name進行過濾
> 
> 本來舊版本是OK可以work
> 
> 舊版本實現位置: https://jsfiddle.net/b93nyL81/

正确的方式应该是使用 API，而不是手动更改内置变量，因为改动内置变量存在兼容性问题，需要同时修改 checked 和 _checked
https://jsfiddle.net/w83nur6b/
![image](https://user-images.githubusercontent.com/34864213/93733401-ca772d00-fc07-11ea-8ebf-4a8881e83f5b.png)

**Comment by HenryLin0914** [comment]
感謝大大!!問題已解決

**Comment by z7klan** [comment]
渲染相同的filter-render, 点击某一列的筛选图标后，，再去点另一列的筛选图标，里面展示的内容还是上一个里面的内容
![image](https://user-images.githubusercontent.com/41694318/94430153-08ef8780-01c6-11eb-904a-44df05034719.png)
如果点击第一个的筛选，，然后不点击其他位置，直接点击第二个的筛选会展示第一个里面的内容

**Comment by wangyong6688** [comment]
> 感谢！！大问题已解决

你好，请问this.$refs.xTable.clearFilter()清楚筛选后，confirmFilter功能失效，怎么修复的
