### ISSUE TITLE
this.$XPrint is not a function

### ISSUE THREAD

**Issue by Duzx5517** [x-extends/vxe-table#1069]
**（必填）请填写问题描述或截图：**
使用 this.$XPrint  打印时报错

 **（必填）请填在线链接：**
http://jsrun.net/ph6Kp/edit

**（必填）请填写期望的结果：**
？

**（必填）请填写以下信息：**

- OS: ？
- Browser: ？
- vue: ？
- vxe-table: ？

**Comment by benemohamed** [comment]
same here !!
