### ISSUE TITLE
this.$XPrint is not a funciton

### ISSUE THREAD

**Issue by Duzx5517** [x-extends/vxe-table#1071]
**（必填）请填写问题描述或截图：**
在使用 $Xprint 打印时报错
this.$XPrint is not a funciton

**（必填）请填在线链接：**
http://jsrun.net/ph6Kp/edit

**（必填）请填写期望的结果：**
$Xprint 可以打印

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6
- vxe-table: 2.7

**Comment by xuliangzhan** [comment]
vue 的全局属性是自行挂载的，命名也是自行随意的
http://jsrun.net/qh6Kp/edit
