### ISSUE TITLE
Collapse / expand column

### ISSUE THREAD

**Issue by diamond95** [x-extends/vxe-table#1076]
**（必填）这个需求解决了什么问题：**
 better visibility, if there is huge number of data ( columns )

**建议的 API 是什么样的：**
collapsable

**是否已有其他不错的替代方案：**
no.

Is it possible to have feature simillar to row expand ( https://x-extends.github.io/vxe-table/#/table/advanced/expand ), but for columns ?
For example, if user clicks on header cell, that column should be collapsed / expanded..

Regards

**Comment by xuliangzhan** [comment]
Columns can be controlled by [column.visible](https://x-extends.github.io/vxe-table/#/table-column/api?q=visible)
https://x-extends.github.io/vxe-table/#/table/advanced/custom
