### ISSUE TITLE
html 标签 title内容问题

### ISSUE THREAD

**Issue by Duzx5517** [x-extends/vxe-table#1081]
**（必填）这个需求解决了什么问题：**
vxe-table 设置表格所有内容的title，当有一列为html标签时，title 显示为html内容

https://jsrun.net/Jb6Kp/edit
status 列通过html 标签 ，title显示为html内容

**建议的 API 是什么样的：**
？

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
列头不是可以使用插槽模板？
