### ISSUE TITLE
$panel.confirmFilter()没有

### ISSUE THREAD

**Issue by z7klan** [x-extends/vxe-table#1085]
**（必填）请填写问题描述或截图：**
？
![image](https://user-images.githubusercontent.com/41694318/94265839-cd598100-ff6b-11ea-9e0d-01d12620f3d6.png)

**（必填）请填在线链接：**
？https://github.com/x-extends/vxe-table/blob/2.9.23/examples/plugins/xtable/renderer/components/FilterComplex.vue

**（必填）请填写期望的结果：**
？
![image](https://user-images.githubusercontent.com/41694318/94265922-eb26e600-ff6b-11ea-8330-694c76c078af.png)
点击确定后应该正确筛选出数据

**（必填）请填写以下信息：**

- OS: ？window
- Browser: ？google
- vue: ？yes
- vxe-table: ？yes

**Comment by z7klan** [comment]
$panel.confirmFilter()没有生效

**Comment by HenryLin0914** [comment]
https://github.com/x-extends/vxe-table/issues/1068
