### ISSUE TITLE
npm安装并全局引入所有组件后，使用vxe-table-colgroup提示组件未注册

### ISSUE THREAD

**Issue by 565871779** [x-extends/vxe-table#1090]
**（必填）请填写问题描述或截图：**
使用其他组件暂时一切正常，但使用vxe-table-colgroup就会提示未注册。在线网站上没有这个问题

![image](https://user-images.githubusercontent.com/41174671/94535134-c71d1a80-0273-11eb-8d8d-b6ae086d6fa4.png)
![image](https://user-images.githubusercontent.com/41174671/94535889-ad300780-0274-11eb-8bff-6b88fc19ada6.png)
![image](https://user-images.githubusercontent.com/41174671/94535898-b0c38e80-0274-11eb-88ae-baf0e6c1427a.png)

**（必填）请填在线链接：**
https://jsrun.net/7rXKp/edit

**（必填）请填写期望的结果：**
vxe-table-colgroup可以正常渲染

**（必填）请填写以下信息：**

- OS: windows10
- Browser: chorme 
- vue: 2.6.10
- vxe-table: 2.9.23

**Comment by xuliangzhan** [comment]
vxe-table-colgroup 是 2.9.24+ 新增的

**Comment by 565871779** [comment]
> vxe-table-colgroup 是 2.9.24+ 新增的

建议在文档上加点提示，找这个问题找了好久。。
