### ISSUE TITLE
[vxe-table] The property "{{0}}" is deprecated, please use "{{1}}

### ISSUE THREAD

**Issue by gguney** [x-extends/vxe-table#1092]
**（必填）请填写问题描述或截图：**
I dont know this language
[vxe-table] The property "{{0}}" is deprecated, please use "{{1}}
<img width="506" alt="Screen Shot 2020-09-29 at 13 38 09" src="https://user-images.githubusercontent.com/16459896/94549689-45b98e00-025b-11eb-86b6-2f1adefaca8a.png">

**（必填）请填在线链接：**
I dont know this language

**（必填）请填写期望的结果：**
I dont know this language

**（必填）请填写以下信息：**
I dont know this language

- OS: MacOS, Windows
- Browser: Chrome
- vue: 2.6.10
- vxe-table: 2.9.24

**Comment by xuliangzhan** [comment]
@gguney use vue-18n
https://xuliangzhan_admin.gitee.io/vxe-table/v2/index.html#/table/start/i18n

**Comment by gguney** [comment]
I'm already using it in my application. I'm using Vue-Element-Admin template how should I use it? Component was working great but now it is not

**Comment by xuliangzhan** [comment]
Please provide demo code to describe the problem.

**Comment by gguney** [comment]
Actually It is quite complicated code. But the part that I use for i18n is like that: 

Vue.use(VXETable, {
  translate: key => i18n.t(key),
  i18n: key => i18n.t(key)
})

and my language keys from en.js and they are like that : 

    pager: {
      goto: 'Go to',
      pagesize: '{{0}}/page',
      total: 'Total {{0}} record',
      pageClassifier: '',
      prevPage: 'Previous page',
      nextPage: 'next page',
      prevJump: 'Jump previous page',
      nextJump: 'Jump next page'
    },

**Comment by xuliangzhan** [comment]
```javascript
Vue.use(VXETable, {
translate: (keyy, args) => i18n.t(key, args),
i18n: (keyy, args) => i18n.t(keyy, args)
})
```
![image](https://user-images.githubusercontent.com/34864213/94553044-7664ec00-028a-11eb-8e96-99f408db2860.png)

**Comment by gguney** [comment]
If I change it to that then this error turns to this: 

[vxe-table] The property "}" is deprecated, please use "}".

**Comment by gguney** [comment]
If I change double { } s to just one {} then it is fixed. So, I changed all 
pager: {
  goto: 'Go to',
  pagesize: '{{0}}/page',
  total: 'Total {{0}} record',
  pageClassifier: '',
  prevPage: 'Previous page',
  nextPage: 'next page',
  prevJump: 'Jump previous page',
  nextJump: 'Jump next page'
},

to 

pager: {
  goto: 'Go to',
  pagesize: '{0}/page',
  total: 'Total {0} record',
  pageClassifier: '',
  prevPage: 'Previous page',
  nextPage: 'next page',
  prevJump: 'Jump previous page',
  nextJump: 'Jump next page'
},

this

**Comment by xuliangzhan** [comment]
language content change '{{0}}' to '{0}'
https://github.com/x-extends/vxe-table/tree/v2/packages/locale/lang

**Comment by gguney** [comment]
Thank you for your quick reply I was using my own language key for it. It is now fixed
