### ISSUE TITLE
希望modal在点击关闭按钮时有一个拦截关闭的事件

### ISSUE THREAD

**Issue by ayao0530** [x-extends/vxe-table#1094]
**（必填）这个需求解决了什么问题：**
现有的close事件是关闭modal后才触发，希望在点击modal关闭时有个提示框，确定后才关闭modal

**建议的 API 是什么样的：**
？

**是否已有其他不错的替代方案：**
类似于element dialog里面的before-close

**Comment by tclqlove** [comment]
我需要做关闭前的拦截事件。目前我只能隐藏默认的关闭按钮，然后自己写个button来替代关闭！

**Comment by ayao0530** [comment]
> 我需要做关闭前的拦截事件。目前我只能隐藏默认的关闭按钮，然后自己写个button来替代关闭！

暂时的话这样的解决方案也可以，或者说能让我自定义关闭按钮的方法

**Comment by xuliangzhan** [comment]
该功能会在 3.0+ 支持 [modal](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/modal)
