### ISSUE TITLE
希望导出功能能默认支持slots数据

### ISSUE THREAD

**Issue by juliastegner** [x-extends/vxe-table#1099]
**（必填）这个需求解决了什么问题：**
我升级到3.0后发现就只能导出源数据了,之前默认支持slots这样导出很方便，不用自己再另外重复处理数据，所见即所导～

**建议的 API 是什么样的：**
希望能继续支持

**是否已有其他不错的替代方案：**
现在只能导出的时候另外处理一遍数据。

**Comment by xuliangzhan** [comment]
虚拟滚动关闭情况是支持导出插槽文本的，虚拟滚动启用后只能导出源数据，formatter 则支持任何场景

**Comment by juliastegner** [comment]
之前是好的，这个是新改的规则吗？但是我去掉虚拟还是不行！真不敢更新了，好几个出错，引发客怨了.
