### ISSUE TITLE
升级到3.0导出csv 包含,号时，会错位。

### ISSUE THREAD

**Issue by juliastegner** [x-extends/vxe-table#1111]
**（必填）请填写问题描述或截图：**
有很多格式化到金融数字 带千分位的，全部都错位了，检查后发现是导出的每项数据没有加引号导致的。不知道是新版去掉了，还是老版就有的bug,这个能否默认就有引号？我看其他ui的表格导出有这个配置项。

**（必填）请填在线链接：**
https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/36b52898-d06c-4e4b-9c24-e8a16f749bfb.png

**（必填）请填写期望的结果：**
希望默认有引号或者增加配置项

**（必填）请填写以下信息：**

- OS: ？win10
- Browser: ？chrome
- vue: ？2.6
- vxe-table: ？3.0

**Comment by juliastegner** [comment]
补充一下，是最新的3.0beta7，之前好的

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试
