### ISSUE TITLE
vue3的支持计划是怎样的？

### ISSUE THREAD

**Issue by fh345392977** [x-extends/vxe-table#1112]
**（必填）这个需求解决了什么问题：**
兼容vue3

**截图或在线链接：**
看官网文档已经有v4的文档了，是用的vue3的写法

**建议的 API 是什么样的：**
？

**是否已有其他不错的替代方案：**
？

**问题补充**
是否已有时间计划？

**Comment by xuliangzhan** [comment]
v4 next 基于 typescript 重写的，支持 vue3.0，将完整支持 ts，预计会在下个月发布 beta 版
v3 将继续支持 vue2.6

v2 只修复bug及维护向下兼容功能，不增加非兼容性功能 
v1 已停止维护

**Comment by cjx913** [comment]
现在可以使用v4开发吗，与vite兼容吗
想研究下

**Comment by xlz26296** [comment]
> 现在可以使用v4开发吗，与vite兼容吗
> 想研究下

4.0.0-alpha.0 已经发布了

**Comment by slgluo** [comment]
看了4.x的文档，是不是4.x的功能开发尚未完善？特别是表格编辑部分
