### ISSUE TITLE
设置了最大高度的表，工具栏列设置操作后表格显示出错

### ISSUE THREAD

**Issue by square-knight** [x-extends/vxe-table#1115]
**（必填）请填写问题描述或截图：**
操作：当vxe-table设置了max-height，并且固定第一列时，vxe-toolbar的**列设置**取消勾选第一列，点击确定，再勾选上第一列，点击确定。
现象：经过以上操作第一列会显示不全。
![image](https://user-images.githubusercontent.com/18032717/96559899-307ecf00-12f0-11eb-82b0-c3b323abb031.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-06ksd?file=/src/views/Demo1.vue:68-78

**（必填）请填写期望的结果：**
第一列正常显示

**（必填）请填写以下信息：**

- OS: win10
- Browser: Chrome
- vue: 2.6.10
- vxe-table: ^2.9.25

**Comment by xuliangzhan** [comment]
该问题会在 2.9.26+ 修复
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-vhnh4

**Comment by HenryLin0914** [comment]
新版本在大數據渲染上效能好像變得比較差，會有空白出現，整體的UX變差了

請求作者支援一下...


2.9.15 搭配 2.7.2 目前是可以解決

**不知道最新版本有沒有解決這個問題呢**

#1042
