### ISSUE TITLE
申请增加模拟编辑数据行的接口

### ISSUE THREAD

**Issue by yixiu025** [x-extends/vxe-table#1118]
**（必填）这个需求解决了什么问题：**
能够在远程加载数据后通过接口调用来保持当前数据行的编辑状态

**截图或在线链接：**
http://jsrun.net/Tt6Kp/edit

**建议的 API 是什么样的：**
查阅相关源码发现keep-source会保存两份数据,一份是sourceData,一份是tableData,而单元格的编辑标记也是根据这两份数据的区别来`决定的，所以希望增加如下API(伪代码):
`
updateRow(row){
    // 按ID更新tableData数据,保持sourceData不变
    this.tableData.forEach(item => {
        if(item.id === row.id){
            item = row;
        }
    })
}
`

**是否已有其他不错的替代方案：**
无

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/status

**Comment by yixiu025** [comment]
不好意思，可能我的问题描述有点问题。
我想实现的效果是(_u代表数据编辑后显示了修改状态的单元格_)：

> 有如下表格：

        姓名     账号      电话号码          邮箱
        张三     zhangs  1xxx                 zhangs@163.com
        李四     lis          1xxx                 lis@163.com
        (其他数据...)

> 当用户对张三行进行修改后,此时被修改的单元格会显示修改状态，如下：

        姓名     账号             电话号码          邮箱
        张三     zhangs1(u)  1xxx                  zhangs1@163.com(u)
        李四     lis                 1xxx                 lis@163.com
        (其他数据...)

此时,列表数据较多,用户按姓名查找李四的这条数据,表格中保留已编辑的数据和符合筛选条件的数据
> 预期效果如下:

        姓名     账号             电话号码          邮箱
        张三     zhangs1(u)  1xxx                  zhangs1@163.com(u)
        李四     lis                 1xxx                 lis@163.com

> 实际效果是: 

        姓名     账号             电话号码          邮箱
        张三     zhangs1       1xxx                 zhangs1@163.com         // 此行的数据是修改后的,但是丢失了修改状态
        李四     lis                 1xxx                 lis@163.com

考虑变通的办法是：数据加载完成后,先渲染服务器的原始数据，然后通过调用接口模拟用户编辑操作绑定修改后的数据以实现修改状态的保留
您所回复的reloadRow()是加载行数据并恢复到初始状态，这样做也会丢失修改状态。

**Comment by xuliangzhan** [comment]
你可以在 tableData 更新之前先把旧的保存起来，然后将旧的列表赋值给新的列表

**Comment by yixiu025** [comment]
好的，谢谢。

**Comment by yixiu025** [comment]
> 您可以在tableData更新之前先把旧的保存起来，然后将旧的列表赋值给新的列表
> http://jsrun.net/fn6Kp/edit

好的，谢谢~
