### ISSUE TITLE
键盘导航进行编辑的问题

### ISSUE THREAD

**Issue by PythonMaker** [x-extends/vxe-table#1127]
**（必填）请填写问题描述或截图：**

问题1：加载页面完成后，无法直接将焦点移动到vxe-table上并激活单元格；
问题2：点击插入新行并激活第一个单元格打开编辑后，按回车键无法选中下一个单元格（已经开启键盘导航）；
问题3：鼠标点击单元格打开编辑后，按回车键导航到下一个单元格，使用中文输入法进行输入后的第一个字符会输入英文，其后才会使用期望的中文输入法。
问题4：有没有通过键盘导航时，选中单元格触发的事件？

**（必填）请填在线链接：**

https://codesandbox.io/s/jianpandaohangjinxingbianjidewentiyanshi-forked-s3xwo

**（必填）请填写期望的结果：**

打开并加载页面后，激活表格的第一个单元格进行编辑，按回车键导航到下一个单元格，并可直接输入中文。
现有行数用完后，插入新行并激活行内第一个单元格，按回车键后导航到下一个单元格继续输入中文。

**（必填）请填写以下信息：**

- OS: Win10
- Browser: Firefox 82.0.2 (64 位)
- vue: 2.6.11
- vxe-table: 2.9.25

**Comment by autukill** [comment]
解决方法: https://developer.mozilla.org/zh-CN/docs/Web/Events/compositionstart

**Comment by wumo1016** [comment]
找到答案了吗大佬？

**Comment by yinjisong** [comment]
求解决啊，我也遇到了！！！

**Comment by xuliangzhan** [comment]
#853
