### ISSUE TITLE
row-style不支持返回类名

### ISSUE THREAD

**Issue by liwen327** [x-extends/vxe-table#1129]
**（必填）这个需求解决了什么问题：**
需要row-style返回类名，这样可以在样式中写行的特殊样式。

**截图或在线链接：**
![image](https://user-images.githubusercontent.com/12168167/97945363-4b5a4480-1dc2-11eb-88ba-a26108d4c704.png)

**建议的 API 是什么样的：**
rowStyle({ row }) {
      console.log('row: ',row);
      if (row.rowType === 4 || row.rowType === 5 || row.rowType === 7) {
        return {
          backgroundColor: "#f0f0f0",
          // className:"grayCalss"  //不支持返回类名
        };
      }
    },

**是否已有其他不错的替代方案：**
无

**Comment by xuliangzhan** [comment]
[row-class-name](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=row-class-name)
