### ISSUE TITLE
vxe-form-item 的datetime 不能弹出日期选择框

### ISSUE THREAD

**Issue by xiaolinshu** [x-extends/vxe-table#1137]
**（必填）请填写问题描述或截图：**

在form里编辑datetime格式的input时变为纯文本，而不是timepicker
在表格里用datetime 可以 。
vxe-form-item title="Date" field="date3" span="12" :item-render="{name: 'input', attrs: {type: 'datetime', placeholder: '请选择日期'}}"

**（必填）请填在线链接：**
https://jsrun.net/TqwKp/edit

**（必填）请填写期望的结果：**
vxe-form-item可以正常编辑datetime

**（必填）请填写以下信息：**

- OS: centos7
- Browser: chrome Version 85.0.4183.121
- vue: 2.6.11
- vxe-table: 2.9.26

**Comment by xlz26296** [comment]
HTML input 的使用及兼容性可以查看对应的文档
```{ name: 'input', attrs: { type: 'xxx', ... } }```
https://www.w3school.com.cn/html5/att_input_type.asp
https://www.runoob.com/tags/att-input-type.html

**Comment by xiaolinshu** [comment]
> HTML input 的属性参数及兼容性可以查看对应的文档 `{ name: 'input', attrs: { type: 'xxx', ... } }`
> https://www.runoob.com/tags/att-input-type.html

是 在 vxe-form-item  标检里 不能用datetime

**Comment by xiaolinshu** [comment]
问题解决了，原来文档有误，现己更正。可以关闭了。

**Comment by xiebinggui** [comment]
怎么解决的？我也遇到同样的问题。求共享！
