### ISSUE TITLE
footer-method表尾能插入html到单元格吗？

### ISSUE THREAD

**Issue by txatxp** [x-extends/vxe-table#1143]
**（必填）这个需求解决了什么问题：**
？
表尾自定义html，有些合计需要展示百分比进度条，需要html，或者能展示vue组件也可，现在只能展示文本
**截图或在线链接：**
？

`footerMethod({ columns, data }) {
      columns.forEach((item) => {
        item.type = "html";
      });
      const sums = [];
      columns.forEach((column, columnIndex) => {
        console.log(column);
        column.type = "html";
        if (columnIndex === 0) {
          columnIndex === 0 && sums.push("合计");
        } else {
          if (columnIndex === 3) {
            let sumCell = null;
            sumCell = XEUtils.sum(data, column.property);
            sums.push(sumCell);
          } else {
            sums.push("<span>ff</span>");
          }
        }
      });
      return [sums];`

**建议的 API 是什么样的：**
？
footer-method
**是否已有其他不错的替代方案：**
？

**Comment by ryanryanorient** [comment]
> 

使用的是什么插槽名？

**Comment by shawon1220** [comment]
在列设置插槽，slots:{footer:(params,h)=>{}}
