### ISSUE TITLE
文档那里有cell-selected的方法，单元格被选中时会触发该事件，但是拿来用没有效果

### ISSUE THREAD

**Issue by glw116** [x-extends/vxe-table#1157]
**（必填）请填写问题描述或截图：**
看到文档那里有cell-selected，单元格被选中时会触发该事件，但是拿来用没有效果

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-108pq

**（必填）请填写期望的结果：**
能否实现可以在选中单元格时候触发

**（必填）请填写以下信息：**

- OS: ？window
- Browser: ？chrome
- vue: ？2.6.10
- vxe-table: ？^2.9.27

**Comment by xuliangzhan** [comment]
[cell-selected](https://xuliangzhan_admin.gitee.io/vxe-table/v2/#/table/api?q=cell-selected) 需要 v2.9.10+
