### ISSUE TITLE
当vxe-table行内嵌套el-dialog，弹出的页面中再嵌套vxe-grid时，点击标题行，el-dialog就直接关闭了。

### ISSUE THREAD

**Issue by citystory** [x-extends/vxe-table#1161]
**（必填）请填写问题描述或截图：**
当vxe-table行内vxe-table-column中嵌套el-dialog，弹出的el-dialog中再嵌套vxe-grid时，点击里面vxe-grid标题行任何地方，el-dialog就直接关闭了，当全选按钮可用时，这个事件未执行，整个el-dialog就关闭了。但是点击表格的筛选toolbar、数据主体内容、翻页等其他地方都可以正常使用。

**（必填）请填在线链接：**
http://jsrun.net/uIwKp

**（必填）请填写期望的结果：**
点击el-dialog中vxe-grid的标题行时，不关闭el-dialog，点击标题行中的全选框时，全选框能够正常执行对应的全选事件。

**（必填）请填写以下信息：**

- OS: win10 20H2
- Browser: 谷歌浏览器86.0.4240.198
- vue: 2.6.11
- vxe-table: 2.10.0

**Comment by xuliangzhan** [comment]
该问题会在 2.10.2+ 中修复
