### ISSUE TITLE
Is it possible to use internationalization without vue-18n?

### ISSUE THREAD

**Issue by im1x** [x-extends/vxe-table#1165]
**（必填）请填写问题描述或截图：**
Hello. I have a problem with warnings like this:
`[vxe-table] The property "{{0}}" is deprecated, please use "{{1}}`
![](https://i.imgur.com/g6KHg0S.jpg)

Yes, I know that the exact same ticket has been previously https://github.com/x-extends/vxe-table/issues/1092

But my problem is that I am already using i18next in my project and don't want to install additional third party libraries for internationalization like vue-18n.

I used a way like this:
```
VXETable.setup({
  i18n: (key, value) => XEUtils.get(EnLocat, key)
});
```
But now this apparently doesn’t work correctly.

Is it possible to use English translation of vxe-table without installing vue-18n?

**（必填）请填在线链接：**
No need, another type of problem
Empty link to prevent the bot from closing the ticket.
https://jsfiddle.net/04Ldpsy8/

**（必填）请填写期望的结果：**
I would like to use the available translations without installing additional third party libraries. I already have XEUtils and i18next installed so also a solution with these libraries will be ok too

**（必填）请填写以下信息：**

- OS: Win10
- Browser: Chrome 86
- vue: 2.6.12
- vxe-table: 2.10.0

**Comment by xlz26296** [comment]
You can handle string placeholder parsing functions yourself. #1092

```
var str = 'xx {0} xx'
var result = XEUtils.template(str, ['abc'], { tmplRE: /\{([.\w[\]\s]+)\}/g })
// result = 'xx abc xx'
```

```
Vue.use(VXETable, {
  // If you do not use vue-i18n, you will need to escape the string syntax itself: '{xx}', for example:
  i18n: (key, args) => XEUtils.template(i18n.t(key, args), args, { tmplRE: /\{([.\w[\]\s]+)\}/g })
})
```

**Comment by im1x** [comment]
> You can handle string placeholder parsing functions yourself. #1092
> 
> ```
> var str = 'xx {0} xx'
> var result = XEUtils.template(str, ['abc'], { tmplRE: /\{([.\w[\]\s]+)\}/g })
> // result = 'xx abc xx'
> ```
> 
> If you do not use `vue-i18n`, you will need to escape the string syntax itself: 'xx {0} xx', for example:
> 
> ```
> Vue.use(VXETable, {
>   i18n: (key, args) => XEUtils.template(i18n.t(key, args), args, { tmplRE: /\{([.\w[\]\s]+)\}/g })
> })
> ```

Thank you very much for your help!
This code works for me:
```
Vue.use(VXETable, {
  i18n: (key, args) => XEUtils.template(XEUtils.get(EnLocat, key), args, { tmplRE: /\{([.\w[\]\s]+)\}/g })
})
```
