### ISSUE TITLE
4.0.0-alpha.4: 第二次提了: 表格插槽数据错乱

### ISSUE THREAD

**Issue by zn98com** [x-extends/vxe-table#1170]
**（必填）请填写问题描述或截图：**
? 同一表格查询加载数据, 表格显示正确的,但是<b>插槽数据错乱</b>,还是以前的. 同行修改,删除等操作根本就无法完成.

![1](https://user-images.githubusercontent.com/10260081/99872042-dab48400-2c19-11eb-828f-09c62d572eb9.png)

**（必填）请填在线链接：**
？https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/grid/fullEdit

**（必填）请填写期望的结果：**
？修改

**（必填）请填写以下信息：**

- OS: ？windows
- Browser: ？任何浏览器
- vue: ？3
- vxe-table: ？4.0.0-alpha.4

**Comment by xuliangzhan** [comment]
没看明白这是啥问题

**Comment by zn98com** [comment]
1.你在每一行后面添加&nbsp;修改或删除按钮.
2.录入关键字,多查询几次,&nbsp;使表格加载不同的数据.
3.表格界面的数据是对的.&nbsp;但是点"修改按钮",你观察一下ID和内容,&nbsp;是以前的缓存内容,不是&nbsp;当前行的内容.&nbsp;&nbsp;









‍







成都赛珂琪科技有限公司

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x-extends/vxe-table"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月21日(星期六) 晚上8:03
收件人:&nbsp;"x-extends/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"智能软件"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [x-extends/vxe-table] 4.0.0-alpha.4: 第二次提了: 表格插槽数据错乱 (#1170)





 
没看明白这是啥问题
