### ISSUE TITLE
树形表格操作数据源插入子节点后，报错: Duplicate keys detected: ''. This may cause an update error.

### ISSUE THREAD

**Issue by withcancer** [x-extends/vxe-table#1172]
**（必填）请填写问题描述或截图：**
操作顺序：
1，点击添加行
2，点击添加子节点
3，重复2步骤大于3次
4，点击展开三角形
现象：
1，控制台报错: [Vue warn]: Duplicate keys detected: ''. This may cause an update error.
![_UFIZW_U${9`ED5}JWZ_9$9](https://user-images.githubusercontent.com/19775306/99893094-06d21280-2cb7-11eb-869e-9f52b2b0492a.png)
2，除去第一条子节点以外的子节点行数据，rowId字段不存在
![8INAQ( L$D{RL%YC8LE%2G0](https://user-images.githubusercontent.com/19775306/99893118-354fed80-2cb7-11eb-99dc-2af116a45b92.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-charuzijiedianwentiyanshi-30470?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
1，控制台无报错
2，所有子节点的rowId存在且正常赋值

**（必填）请填写以下信息：**

- OS: Window10 1909
- Browser: Chrome 87
- vue: 2.6.12
- vxe-table: 3.0.0

**关联issue：**
#63 
#463
#1020 
#1021

**Comment by xuliangzhan** [comment]
操作深层节点需要改变 data 或者调用 [syncData](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=syncData) 方法同步数据
https://codesandbox.io/s/vxe-table-charuzijiedianwentiyanshi-forked-3t0k4

**Comment by withcancer** [comment]
感谢大佬迅速而且准确的解答！
