### ISSUE TITLE
xe-utils.js版本已经最新版本分页器显示还是有问题

### ISSUE THREAD

**Issue by HongHomeDong** [x-extends/vxe-table#1182]
**（必填）请填写问题描述或截图：**
？
![image](https://user-images.githubusercontent.com/33336056/100359564-b221f500-3032-11eb-9182-0d90bbe021d6.png)

**（必填）请填在线链接：**
？暂无

**（必填）请填写期望的结果：**
？希望解决

**（必填）请填写以下信息：**

- OS: ？Mac
- Browser: ？Edge
- vue: ？2.6.10
- vxe-table: ？3.1.0

**Comment by HongHomeDong** [comment]
![image](https://user-images.githubusercontent.com/33336056/100359885-2361a800-3033-11eb-891b-c7e2f158caee.png)

**Comment by HongHomeDong** [comment]
@xuliangzhan

**Comment by liniu** [comment]
我也是这个情况

**Comment by 850593913** [comment]
注意国际化的配置
`VXETable.setup({
  i18n: (key, args) => XEUtils.toFormatString(XEUtils.get(zhCNLocat, key), args)
})`
