### ISSUE TITLE
父容器加了transition，表格内容不会自适应

### ISSUE THREAD

**Issue by square-knight** [x-extends/vxe-table#1184]
**（必填）请填写问题描述或截图：**
父容器设置了transition改变了宽度后table内容无法自适应，demo中有el-table和vxe-table的对比演示。
![image](https://user-images.githubusercontent.com/18032717/100421721-e42f6780-30c3-11eb-839c-2a596502b334.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-tzzp4?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
当父容器动态改变了宽度时，table内容可以适应当前尺寸。

**（必填）请填写以下信息：**

- OS: win10
- Browser: Chrome
- vue: 2.6.10
- vxe-table: ^2.10.0

**Comment by xuliangzhan** [comment]
如果需要自动跟随父容器，设置参数 [auto-resize](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=resize) 即可
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-5vyh9

**Comment by square-knight** [comment]
好的，谢谢
