### ISSUE TITLE
当表格数据刷新时，如果有横向滚动，表头会闪烁

### ISSUE THREAD

**Issue by anotherten** [x-extends/vxe-table#1186]
**（必填）请填写问题描述或截图：**
当有多列存在，且有横向滚动条，且发生了横向滚动
当表格数据刷新时，表头会闪烁
![Kapture 2020-11-30 at 17 11 18](https://user-images.githubusercontent.com/14290099/100590615-9454d880-332f-11eb-95ed-93c6ab9d988d.gif)

**（必填）请填在线链接：**
https://jsrun.net/TrXKp/edit 
使用官方在线demo，设置一个定时器去更新数据，即可复现
```js
        setInterval(() => {
            var list1 = []
            for (var index = 0; index < 10; index++) {
                list1.push({
                    name: 'aaa' + index,
                    role: 'bbb',
                    sex: 'ccc',
                    date: '2019-05-01',
                    time: 1556677810888 + index * 500,
                    region: 'ShenZhen',
                    address: 'address abc' + index
                })
            }
            this.tableData = list1;
        }, 1000)
```

**（必填）请填写期望的结果：**
仅数据更新，表头不发生变化

**（必填）请填写以下信息：**

- OS: macOS 10.15.4
- Browser: chrome 87
- vue: 在线demo运行版本
- vxe-table: 在线demo运行版本

**Comment by Xuffy** [comment]
有解决方案了吗？
