### ISSUE TITLE
请问虚拟滚动能配合树形结构懒加载一起使用吗

### ISSUE THREAD

**Issue by zhoufenfens** [x-extends/vxe-table#1188]
**（必填）这个需求解决了什么问题：**
？树形结构懒加载的节点总数过多时，也能使用虚拟滚动提高性能

**截图或在线链接：**
？

**建议的 API 是什么样的：**
？

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
树形不支持虚拟滚动，有额外的插件可供参考 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/treeRows

**Comment by zhoufenfens** [comment]
> 树形不支持虚拟滚动，有额外的插件可供参考 [vxe-table-plugin-virtual-tree](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/treeRows)

谢谢，我看下
