### ISSUE TITLE
因formatter函数所依赖数据在表格数据加载完成后才加载成功，单元格数据未格式化的问题

### ISSUE THREAD

**Issue by yixiu025** [x-extends/vxe-table#1189]
**（必填）这个需求解决了什么问题：**
因formatter函数所依赖数据在表格数据加载完成后才加载成功，单元格数据未格式化的问题

**截图或在线链接：**
http://jsrun.net/GBwKp
// 您可以分别点击 “字典>数据” 和 “数据>字典” 查看不同的渲染结果

**建议的 API 是什么样的：**
在formatter函数依赖数据加载完成后再次渲染DOM

**是否已有其他不错的替代方案：**
暂无

**Comment by xuliangzhan** [comment]
目前 formatter 格式化函数只会在对应 field 值发生变化时才会触发调用，如果对应的 field 值未发生变化时不会重新执行的

**Comment by yixiu025** [comment]
嗯嗯，请问后续有增加这个功能的计划吗？

**Comment by xuliangzhan** [comment]
建议还是 formatter  里面的字典数据在表格加载之前先获取到吧，目前的 formatter 只会在对应 field 值发生变化时才会触发调用；后续有待优化！

**Comment by yixiu025** [comment]
好的，谢谢。

**Comment by huzedong2015** [comment]
> 建议还是 formatter 里面的字典数据在表格加载之前先获取到吧，目前的 formatter 只会在对应 field 值发生变化时才会触发调用；后续有待优化！

2022年了，可以了吗

**Comment by huzedong2015** [comment]
@yixiu025 这个现在有解决方案吗，单元格 格式化需要动态获取数据
