### ISSUE TITLE
TablePrintConfig希望能添加一个指向后台pdf文件流的url，直接通过流打印pdf

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1191]
**（必填）这个需求解决了什么问题：**
TablePrintConfig希望能添加一个指向后台pdf文件流的url，直接通过流打印pdf，最好支持(gzip,zip)压缩后的流

**截图或在线链接：**
无

**建议的 API 是什么样的：**

export interface TablePrintConfig {
 
  url ？ ：string；

  sheetName?: string;

  mode?: string;
  .....
 }

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
打印pdf文件和表格无关吧，你写个按钮绑个事件去获取文件流后打印就行了，这应该不属于表格功能
