### ISSUE TITLE
vxe Table Filter Fields

### ISSUE THREAD

**Issue by martinfruehmorgen** [x-extends/vxe-table#1194]
**（必填）这个需求解决了什么问题：**
The possibility to change the default filter fields in a header of a filter, if you have different fields (not value/label) coming from a database. In my case id/value

**截图或在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-7tn5r?file=/src/views/Demo1.vue

**建议的 API 是什么样的：**
The possibility to choose a id field and a label field value

**是否已有其他不错的替代方案：**
Can't find in the docs.

**Comment by xuliangzhan** [comment]
Currently, other fields names are not supported. Only label/value is supported
