### ISSUE TITLE
使用transform将报表旋转90度之后，变成横屏，此时滑动事件异常，手机屏幕竖直方向的上下滑动，导致报表横屏的上下滑动

### ISSUE THREAD

**Issue by Wingbu** [x-extends/vxe-table#1195]
**（必填）请填写问题描述或截图：**
？使用transform将报表旋转90度之后，变成横屏，此时滑动事件异常，手机屏幕竖屏的上下滑动，导致报表横屏的上下滑动

**（必填）请填在线链接：**
？

**（必填）请填写期望的结果：**
？使用transform将报表旋转90度之后，变成横屏，此时滑动事件异常，手机屏幕竖屏的上下滑动，导致报表横屏的左右滑动，手机屏幕竖屏的左右滑动，导致报表横屏的上下滑动

**（必填）请填写以下信息：**

- OS: ？
- Browser: ？
- vue: ？
- vxe-table: ？

**Comment by xiaoqingb** [comment]
请求复活这个issue

**Comment by shi-gui** [comment]
请求复活这个issue

**Comment by wenhuowu** [comment]
请求复活这个issue
