### ISSUE TITLE
能否新增vxe-table特色的【布局容器】和左侧【导航菜单】

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1197]
**（必填）这个需求解决了什么问题：**
能否新增vxe-table风格的【布局容器】和左侧【导航菜单】，目前vxe-table已经自成体系，就差这块拼图，加上不少第三方已经跟不上vxe-table的步伐，不支持vue3.0

**截图或在线链接：**
![image](https://user-images.githubusercontent.com/4531974/101301098-b50eb800-3872-11eb-8b02-64a17ca10d27.png)
![image](https://user-images.githubusercontent.com/4531974/101301105-b9d36c00-3872-11eb-8aa9-907c513b1de2.png)

**建议的 API 是什么样的：**

**是否已有其他不错的替代方案：**

**Comment by xuliangzhan** [comment]
vxe-table 是表格组件，不是UI库，除了与表格相关的组件其他的可能不会增加😂，可以使用 [ui 库](https://vxeui.com)就有
