### ISSUE TITLE
vxe-grid columns 自定義 控制各button顯示 icon未刷新

### ISSUE THREAD

**Issue by StitchJian** [x-extends/vxe-table#1198]
**（必填）请填写问题描述或截图：**
vxe-grid columns 自定義 情況下 控制各button顯示 fontAwesome(icon)未刷新

**（必填）请填在线链接：**

https://codesandbox.io/s/vxe-table-wentiyanshi-forked-bbzof?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
fontAwesome正常刷新

**（必填）请填写以下信息：**

- OS: windows10
- Browser: chrome(87.0.4280.88)
- vue: 2.6.12
- vxe-table: 3.0.3

**Comment by xlz26296** [comment]
你这个是监听dom变化自己去替换的dom元素的，看代码vue已经正常响应了，如果是这种手动破坏vue的dom元素可以加个key，由于你这种不是vue的用法，具体引发的问题只能自行解决了

**Comment by StitchJian** [comment]
> **（必填）請填寫問題描述或截圖：**
> vxe-grid列自定義情況下控制各按鈕顯示fontAwesome（icon）未刷新
> 
> **（必填）請填在線鏈接：**
> 
> https://codesandbox.io/s/vxe-table-wentiyanshi-forked-bbzof?file=/src/views/Demo1.vue
> 
> **（必填）請填寫**
> 期望**的結果：** fontAwesome正常刷新
> 
> **（必填）請填寫以下信息：**
> 
> * 操作系統：Windows10
> * 瀏覽器：chrome（87.0.4280.88）
> * 版本：2.6.12
> * vxe表：3.0.3
