### ISSUE TITLE
能否添加快速选择一年中的周，类似选择月份一样。

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1206]
**（必填）这个需求解决了什么问题：**
能否添加快速选择一年中的周，类似选择月份一样，目前选择的周是带日期的，希望有已给不带日期，一个版块就可以一年之中任何一周，返回类似【第一周】2020-01，第15周【2020-15】

**截图或在线链接：**

![image](https://user-images.githubusercontent.com/4531974/102067193-bcffc680-3e35-11eb-88fd-79c19e9f7c99.png)

**建议的 API 是什么样的：**

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
一年有 50 多周，这个是放不下的，看起来并不合适，一般和日期放在一起更直观一些

**Comment by jianliulin** [comment]
10个一行，6行可以fang放下，也不算多。有些需求只看周，以周为单位，不看日期。

**Comment by xuliangzhan** [comment]
目前可能不会支持，这种特殊的需求建议自行封装一个组件吧
