### ISSUE TITLE
vxe-table内的下拉按钮设置了transfer属性，导致table抖动、下拉容器有几率错位

### ISSUE THREAD

**Issue by square-knight** [x-extends/vxe-table#1207]
**（必填）请填写问题描述或截图：**
如图，当在vxe-table中设置了下拉按钮并且设置了transfer属性后，在第一次触发下拉容器弹出时下拉容器有几率错位，并且伴随整个vxe-table的抖动。
**补充：请把浏览器上下宽度调整到最右侧的滚动条正好消失的状态。如图**
![image](https://user-images.githubusercontent.com/18032717/102603374-a6bb7880-415d-11eb-9611-b3e9de050abc.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-dvlv5?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
下拉按钮设置了transfer时：table不抖动，下拉容器位置正常

**（必填）请填写以下信息：**

- OS: win10
- Browser: Chrome
- vue: 2.6.10
- vxe-table: ^2.10.0

**Comment by xuliangzhan** [comment]
我用谷歌浏览器看了貌似没有你说的那种情况

**Comment by square-knight** [comment]
> 我用谷歌浏览器看了貌似没有你说的那种情况

你使用了我创建的在线连接么？我刚刚进在线连接看了还是有的啊

**Comment by square-knight** [comment]
和谷歌的版本会有关系么？我的版本 85.0.4183.121（正式版本） （64 位）

**Comment by square-knight** [comment]
> 我用谷歌浏览器看了貌似没有你说的那种情况
请把浏览器上下宽度调整到最左侧的滚动条正好消失的状态，如图
![123456](https://user-images.githubusercontent.com/18032717/102603814-47aa3380-415e-11eb-996f-9d999f308ff7.png)

**Comment by square-knight** [comment]
@xuliangzhan 能再看看这个问题么，谢谢

**Comment by xuliangzhan** [comment]
建议看看优化的 v3.0 版本
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-6lecy

**Comment by square-knight** [comment]
@xuliangzhan 刚刚试过，v3.0版本也有此类现象
