### ISSUE TITLE
树状表格 点击添加子分类，如果该行本来没有子节点，点击添加后，必须点击其他展开按钮或收起按钮，子节点才会出现

### ISSUE THREAD

**Issue by Angiey-12** [x-extends/vxe-table#1211]
**（必填）请填写问题描述或截图：**
树状表格 点击添加子分类，如果该行本来没有子节点，点击添加后，必须点击其他展开按钮或收起按钮，子节点才会出现

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-n5x0c?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
添加后就马上能看见子节点

**（必填）请填写以下信息：**

- OS: windows10
- Browser: chorme
- vue: 2.6.0
- vxe-table: 3.0.0

**Comment by xuliangzhan** [comment]
[vue 响应式](https://cn.vuejs.org/v2/guide/reactivity.html#对于对象) 的使用应该遵循其规范，先定义后使用，如果不存在字段，则无法响应
