### ISSUE TITLE
vxe-button 如何使用iconfont图标？

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1215]
**（必填）这个需求解决了什么问题：**
vxe-button 如何使用iconfont图标？，官网上看大的是fontawesome，能否使用svg的图标。

**截图或在线链接：**
图标库链接：
https://www.iconfont.cn/collections/index?spm=a313x.7781069.1998910419.d33146d14&type=3

**建议的 API 是什么样的：**

**是否已有其他不错的替代方案：**

**Comment by xuliangzhan** [comment]
图标支持任何 class 字体图标库，只要指定 class 即可，不能用于 svg
