### ISSUE TITLE
vxe-table报错：Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by square-knight** [x-extends/vxe-table#1222]
**（必填）请填写问题描述或截图：**
1.当vxe-table编辑模式，不指定height属性并且指定了edit-rules属性
2.表格内只有一行数据
3.当触发校验错误时

当满足上述两个条件时，点击切换cell会报Cannot read property 'getBoundingClientRect' of null错误
![image](https://user-images.githubusercontent.com/18032717/102989152-18c20200-4550-11eb-89e3-ddd4f04ed69e.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-wentiyanshi-forked-3bkus?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
消除错误

**（必填）请填写以下信息：**

- OS: win10
- Browser: Chrome
- vue: 2.6.10
- vxe-table: ^2.10.0

**Comment by xuliangzhan** [comment]
该问题会在 2.10.9+ 修复
