### ISSUE TITLE
[更新3.0.18出現問題] ctor_amd_xe_utils_default.a.browse

### ISSUE THREAD

**Issue by HenryLin0914** [x-extends/vxe-table#1223]
**（必填）请填写问题描述或截图：**
![image](https://user-images.githubusercontent.com/66756295/103118993-58056580-46ac-11eb-8691-69af3eb2d2a7.png)

**（必填）请填在线链接：**
http://localhost

**（必填）请填写期望的结果：**
試過查到的所有方法,都無效
![image](https://user-images.githubusercontent.com/66756295/103119023-7b301500-46ac-11eb-95e4-a84e529785a6.png)

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6
- vxe-table: 3.0.18
- xe-utils:3.0.4

**Comment by conanskyforce** [comment]
同样问题

**Comment by 850036165** [comment]
同，请问解决了吗

**Comment by stanye** [comment]
同

**Comment by 850036165** [comment]
在每个应用table之前都先引用xutils

**Comment by frank994** [comment]
同问

**Comment by xlz26296** [comment]
看一下你使用方式是否正确 https://github.com/xuliangzhan/vxe-table-demo

**Comment by zwb3707811** [comment]
同
