### ISSUE TITLE
Make vxe-grid work with PeachScript/vue-infinite-loader.

### ISSUE THREAD

**Issue by matsch01** [x-extends/vxe-table#1234]
**（必填）这个需求解决了什么问题：**
I want to use PeachScript/vue-infinite-loader with vxe-grid similar to this example using Element UI:

https://peachscript.github.io/vue-infinite-loading/guide/use-with-el-table.html

Here is a working example:

https://jsfiddle.net/PeachScript/uyjb6z34/

I can't get this to work with vxe-grid. I'm using the pager slot with force-use-infinite-wrapper=".vxe-table--body-wrapper".

- To your knowledge, should this be possible?
- If it's not possible, please provide an alternative solution for infinite scrolling in vxe-grid.
- If there is no solution for infinite scrolling, please implement one.

**截图或在线链接：**
？

**建议的 API 是什么样的：**
？

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
Not supported, you can listen for [scroll](https://x-extends.github.io/vxe-table/#/table/api?q=scroll) events to handle.
