### ISSUE TITLE
edit-render 在 events 的事件函数中，如何获取编辑后的最新值？

### ISSUE THREAD

**Issue by Namesen** [x-extends/vxe-table#1249]
![image](https://user-images.githubusercontent.com/35164366/104887266-faf88900-59a5-11eb-8461-fcb76dd0be24.png)

测试代码地址： http://jsrun.net/NgaKp/edit

在编辑Name列时，会监听change事件，有变动时会调用nameChangeEvent函数， 此时获取的row.name仍然是编辑前的值。

如何在nameChangeEvent函数里获取编辑后的值。

**Comment by chenhongen** [comment]
解决了吗
