### ISSUE TITLE
使用 $input 和自定义渲染器 无法正常触发校验

### ISSUE THREAD

**Issue by lzj97** [x-extends/vxe-table#1257]
**（必填）请填写问题描述或截图：**
使用 内置渲染器$input 和 自定义渲染器 无法正常触发校验，但使用原生渲染器（input）会正常触发。

**html：**

```html
<vxe-grid
  :edit-config="editConfig"
  :edit-rules="editRules"
  :columns="tableColumn"
  :data.sync="tableData"
/>
```

**js：**

```js
data(){
  return {
    tableColumn: [
      {
        field: "name",
        title: "姓名",
        editRender: {
          //使用 内置渲染器$input 和 自定义渲染器 都不能正常触发，只能在聚焦时触发
          name: "$input",

          //使用原生 input 可以正常触发
          // name: "input",
        },
      },
    ],
    tableData: [
      {
        name: "张三",
      }
    ],
    editConfig: { trigger: "click", mode: "cell" },
    editRules: {
      name: [
        {
          required: true,
          message: "空啥",
          trigger: "change"
        }
      ]
    }
  }
}
```

**使用原生 input**

```js
editRender: {
  name: "input"
}
```

正常触发：
![正常](https://user-images.githubusercontent.com/44044710/105442902-98550500-5ca5-11eb-8cfa-a0321515e7cb.gif)

**使用内置渲染器 $input 或 自定义渲染器**

```js
editRender: {
  name: "$input"
}
```

不正常：
![异常](https://user-images.githubusercontent.com/44044710/105443112-f386f780-5ca5-11eb-8ce7-a1af8b2f83c7.gif)

**（必填）请填在线链接：**
[https://codesandbox.io/s/vibrant-curran-doh9j?file=/src/App.vue](https://codesandbox.io/s/vibrant-curran-doh9j?file=/src/App.vue)

**（必填）请填写期望的结果：**
与原生渲染器一样正常触发

**（必填）请填写以下信息：**

- OS: windows10
- Browser: chrome 86.0.4240.198
- vue: 2.6.10
- vxe-table: 3.0.28

**Comment by xuliangzhan** [comment]
自定义插槽模板需要调用方法 [updateStatus](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=updateStatus) 去更新状态
https://codesandbox.io/s/vxe-table-demo-forked-33gmi
