### ISSUE TITLE
`vxe-grid`的toolbar buttons能否绑定自定义事件

### ISSUE THREAD

**Issue by shlroland** [x-extends/vxe-table#1259]
**（必填）这个需求解决了什么问题：**
？想保留部分自带功能，但是需要插入自定义的按钮进行操作。使用自定义插槽怎么失去了code选项，进行自动操作

**截图或在线链接：**
？

**建议的 API 是什么样的：**
？加一个 如  clickEvent 的 属性 就行回调

**是否已有其他不错的替代方案：**
？或者将code所代表的功能 存入grid示例中，可以自动调用

**Comment by HyWell** [comment]
请问有解决办法了吗？
