### ISSUE TITLE
虚拟滚动表格初始化后会展示所有的行

### ISSUE THREAD

**Issue by Forx-Js** [x-extends/vxe-table#1283]
**（必填）请填写问题描述或截图：**
虚拟滚动初始化后会直接加载全部行,仍旧造成卡顿,当表格触发滚动时,恢复正常

**（必填）请填在线链接：**
https://codepen.io/forx-js/pen/KKNZXOE

**（必填）请填写期望的结果：**
？
初始化后应该只显示该显示的行
**（必填）请填写以下信息：**

- OS: Windows10
- Browser: Microsoft Edge 88.0
- vue: 2.6.12
- vxe-table: 3.1.6

**Comment by xuliangzhan** [comment]
改问题会在下版本修复 https://codepen.io/xuliangzhan/pen/zYopLdB
