### ISSUE TITLE
revertData does not reset validation

### ISSUE THREAD

**Issue by silvialeung** [x-extends/vxe-table#1286]
**（必填）请填写问题描述或截图：**
I tried to validate row on edit-closed event and revertData() and clearActived() if error exists. The data was reverted but the error message remained under the cell

**（必填）请填在线链接：**
http://jsrun.net/wjaKp/edit

This is copied from the validation(cell) demo (https://jsrun.net/IcWKp/edit). The only difference is @edit-closed event handler.

**（必填）请填写期望的结果：**
The data is reverted to original value and cell is set to inactive with no error message

**（必填）请填写以下信息：**

- OS: Window 10
- Browser: Google Chrome ver. 88.0.4324.190
- vue: v2.6.12
- vxe-table: v.3.1.7

**Comment by xuliangzhan** [comment]
fix v3.1.8+
Be aware that this approach may cause an infinite loop!
`edit-closed` -> `clearActived` -> `edit-closed` ...
