### ISSUE TITLE
编辑表格-手动触发-点击编辑-编辑name-点击保存,方法中打印的row显示获取到的还是旧数据

### ISSUE THREAD

**Issue by DoveAz** [x-extends/vxe-table#1287]
**（必填）请填写问题描述或截图：**
![image](https://user-images.githubusercontent.com/15158280/109612194-4b98ff80-7b6a-11eb-93f0-9c37a5f2410a.png)
编辑表格-手动触发-点击编辑-编辑name-点击保存,方法中打印的row显示获取到的还是旧数据

**（必填）请填在线链接：**
https://jsrun.net/7jaKp/edit

**（必填）请填写期望的结果：**
回调函数中的row是新数据

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome 88
- vue: 2.x latest
- vxe-table: 3.1.7

**Comment by xuliangzhan** [comment]
如果未设置 [immediate](https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?q=immediate) 实时更新的情况下，需要在异步之后才能获取到 `row` 对象
https://jsrun.net/4uaKp/edit

**Comment by DoveAz** [comment]
> 如果未设置 [immediate](https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?q=immediate) 实时更新的情况下，需要在异步之后才能获取到 `row` 对象
> https://jsrun.net/4uaKp/edit

thanks
