### ISSUE TITLE
设置expand的trigger为row时，点击checkbox单元格也会展示行

### ISSUE THREAD

**Issue by fh345392977** [x-extends/vxe-table#1290]
**（必填）请填写问题描述或截图：**
设置expand的trigger为row时，点击checkbox单元格也会展示行

**（必填）请填在线链接：**
https://jsrun.net/yBaKp/edit

**（必填）请填写期望的结果：**
点击checkbox单元格不会展示行

**（必填）请填写以下信息：**

- OS: osx 11.2
- Browser: Chrome 88
- vue: 2.6
- vxe-table: 3.1.7

**Comment by xuliangzhan** [comment]
点击复选框的冒泡问题已在 v3.1.8 修复：https://jsrun.net/pMaKp/edit
如果同时设置多种功能的 trigger 依然是同时触发的，该类型场景待后续版本考虑，建议自行通过 [cell-click](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=cell-click) 自行实现；
