### ISSUE TITLE
移动端下使用vxe-grid，固定列并显示表尾时，固定的列会滚动

### ISSUE THREAD

**Issue by jackjtr** [x-extends/vxe-table#1295]
**（必填）请填写问题描述或截图：**

![image](https://user-images.githubusercontent.com/6552755/110602661-3010a300-81c1-11eb-9aa2-1bc14e72a3a9.png)

**（必填）请填在线链接：**
[在线示例地址](https://codesandbox.io/s/stoic-mahavira-49w9v)
[移动端模拟地址](https://49w9v.csb.app/)

**（必填）请填写期望的结果：**
固定的列不可滚动

**（必填）请填写以下信息：**

- OS: Windows 10
- Browser: Chrome 88.0.4324.190
- vue: 2.6.11
- vxe-table: 3.2.0

**Comment by xuliangzhan** [comment]
注意：这是 PC 端的表格组件，不能用于移动端！

**Comment by curryft** [comment]
pc端也是有同样问题的大佬，我看有这个css：.vxe-table--render-default:not(.is--empty).is--footer.is--scroll-x .vxe-table--body-wrapper{overflow-x:scroll} 导致的 请问这个css是有特殊的用途吗不敢轻易覆盖，谢谢
