### ISSUE TITLE
Fixed与expand能同时使用

### ISSUE THREAD

**Issue by fh345392977** [x-extends/vxe-table#1303]
**（必填）这个需求解决了什么问题：**
当前版本同时使用fixed和expand时，会出现警告提示 [vxe-table] 参数 "column.fixed" 与 "column.type=expand" 有冲突，再不做任何修改的情况下，expand在fixed列的部分无法显示。

**截图或在线链接：**
![image](https://user-images.githubusercontent.com/16329330/111260060-1e187f80-865b-11eb-8ae2-ba67ab53fa24.png)

**建议的 API 是什么样的：**
建议fixed与expand能并存，并且显示正常

**是否已有其他不错的替代方案：**
目前通过css的处理得以显示，
![image](https://user-images.githubusercontent.com/16329330/111260098-2cff3200-865b-11eb-98fa-34d497f88c33.png)
但有时会出现因showOverflow未设置时fixed列无法显示的问题
![image](https://user-images.githubusercontent.com/16329330/111260212-62a41b00-865b-11eb-9727-1e8a883b6c77.png)
设置showOverflow:true后，fixed:right下expand的内容则会异常。

故目前最优的解决办法依然是去掉fixed，可业务有并存方面的需要，希望能看看这个issue，或者能提供一个思路，不尽感激。

**Comment by xuliangzhan** [comment]
该功能某些场景是有用的，预计下版本支持
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/expand

**Comment by fh345392977** [comment]
fixed:left与fixed:right同时使用时，left的expand会出现right的空白列

**Comment by FeiLong2014** [comment]
`<template>
  <el-container style="height: 105%">
    <el-header height="80px" style="text-align: right">
      <el-button @click="getSelectEvent">获取选中</el-button>
    </el-header>
    <el-main style="padding: 0; height: 100%">
      <vxe-table class="mytable-scrollbar" stripe border resizable show-overflow show-header-overflow highlight-hover-row highlight-current-row
        ref="xTable" height="100%" :export-config="{}" :loading="loading" :sort-config="{ trigger: 'cell' }" :cell-style="cellStyle"
        :header-cell-style="cellStyle" :checkbox-config="{ checkField: 'checked' }" style="background-color: #fff;">
        <vxe-table-column type="checkbox" width="60" style="position:sticky"></vxe-table-column>
        <vxe-table-column type="expand" width="60">
          <template v-slot:content="{ rowIndex }">
            <vxe-table border :data="tableData(rowIndex)" style="width: 500px">
              <vxe-table-column type="seq" title="seq" width="60"></vxe-table-column>
              <vxe-table-column field="name" title="name" width="60"></vxe-table-column>
              <vxe-table-column field="sex" title="sex" width="60"></vxe-table-column>
            </vxe-table>
          </template>
        </vxe-table-column>
        <vxe-table-column type="seq" width="100"></vxe-table-column>
        <vxe-table-column field="name" title="Name" sortable width="200"></vxe-table-column>
        <vxe-table-column field="sex" title="Sex" width="200"></vxe-table-column>
        <vxe-table-column field="role" title="Role" width="200"></vxe-table-column>
        <vxe-table-column field="region" title="Region" width="200"></vxe-table-column>
        <vxe-table-column field="time" title="Time" width="200"></vxe-table-column>
        <vxe-table-column field="address" title="Address" width="300"></vxe-table-column>
        <vxe-table-column field="updateTime" title="UpdateTime" width="200"></vxe-table-column>
        <vxe-table-column field="createTime" title="CreateTime" width="200"></vxe-table-column>
        <vxe-table-column field="attr1" title="Attr1" width="200"></vxe-table-column>
        <vxe-table-column field="attr2" title="Attr2" width="200"></vxe-table-column>
        <vxe-table-column field="attr3" title="Attr3" width="200"></vxe-table-column>
        <vxe-table-column field="attr4" title="Attr4" width="200"></vxe-table-column>
        <vxe-table-column field="attr5" title="Attr5" width="200"></vxe-table-column>
        <vxe-table-column field="attr6" title="Attr6" width="200"></vxe-table-column>
        <vxe-table-column field="attr7" title="Attr7" width="200"></vxe-table-column>
        <vxe-table-column field="attr8" title="Attr8" width="200"></vxe-table-column>
        <vxe-table-column field="attr9" title="Attr9" width="200"></vxe-table-column>
        <vxe-table-column field="createTime" title="CreateTime" width="200"></vxe-table-column>
        <vxe-table-column field="age" title="Age" width="200"></vxe-table-column>
      </vxe-table>
    </el-main>
  </el-container>
</template>

<script>
import XEUtils from 'xe-utils'
export default {
  data() {
    return {
      loading: false
    }
  },
  created() {
    this.allData = []
    this.loadList(50000)
  },
  methods: {
    loadList(size) {
      this.loading = true
      this.findList(size).then((data) => {
        this.allData = this.allData.concat(data) // 局部追加并保存所有数据
        const xTable = this.$refs.xTable
        if (xTable) {
          xTable.loadData(this.allData)
        }
        this.loading = false
      })
    },
    findList(size) {
      return new Promise((resolve) => {
        setTimeout(() => {
          var list = []
          for (var index = 0; index < size; index++) {
            list.push({
              id: XEUtils.uniqueId(),
              checked: false,
              name: 'test' + index,
              sex: 1,
              role: 'developer',
              age: 10,
              date: '2019-05-01',
              address: 'address abc' + index
            })
          }
          resolve(list)
        }, 500)
      })
    },
    getSelectEvent() {
      let selectRecords = this.$refs.xTable.getCheckboxRecords()
      console.dir(selectRecords)
    },
    tableData() {
      var list = []
      for (var index = 0; index < 5; index++) {
        list.push({
          id: XEUtils.uniqueId(),
          checked: false,
          name: 'test' + index,
          sex: 1,
          role: 'developer',
          age: 10,
          date: '2019-05-01',
          address: 'address abc' + index
        })
      }
      return list
    },
    cellStyle({ $columnIndex, $rowIndex, type }) {
      if ($columnIndex === 0) {
        return {
          position: 'sticky',
          left: $columnIndex * 60 + 'px',
          backgroundColor: 'inherit',
          zIndex: 1
        }
      } else if ($columnIndex === 1) {
        return {
          position: 'sticky',
          left: $columnIndex * 60 + 'px',
          backgroundColor: 'inherit',
          boxShadow: '4px 0px 0px 0 rgba(0,0,0,.06)',
          zIndex: 1
        }
      }
      //  else if ($columnIndex === 20) {
      //   return {
      //     position: 'sticky',
      //     right: type === 'header' ? '10px' : 0,
      //     borderLeft: '1px solid #f1f1f1',
      //     backgroundColor: 'inherit',
      //     // boxShadow: '-4px 3px 4px 0 rgba(0,0,0,.12)',
      //     zIndex: 1
      //   }
      // }
    }
  }
}
</script>


<style>
.vxe-body--row {
  background-color: #fff;
}
.vxe-header--row {
  background-color: #f8f8f9;
}
</style>
`

**Comment by VincentDream** [comment]
![image](https://user-images.githubusercontent.com/9589356/182571747-4d35bb1e-80b5-4081-ab92-bf972f319a58.png)
官方示例，这种情况属于正常情况吗
