### ISSUE TITLE
3.x version pager problem

### ISSUE THREAD

**Issue by lai397826696** [x-extends/vxe-table#1304]
**（必填）请填写问题描述或截图：**
？
3.x版本分页器问题，通过官方的ide测试正常的，但是在本地测试就不行了
![微信截图_20210316173316](https://user-images.githubusercontent.com/13134964/111287525-45cd0f00-867e-11eb-81cd-f4a3a0916b8c.png)

**（必填）请填在线链接：**
？
[vue-test.zip](https://github.com/x-extends/vxe-table/files/6147719/vue-test.zip)

**（必填）请填写期望的结果：**
？
![微信截图_20210316173628](https://user-images.githubusercontent.com/13134964/111288130-ddcaf880-867e-11eb-970e-f7c593691941.png)

**（必填）请填写以下信息：**

- OS: ？win10-x64
- Browser: ？google => 88.0.4324.190
- vue: ？2.6.11
- vxe-table: ？3.2.1

**Comment by xlz26296** [comment]
你应该按照官网的用法，按需加载是不带国际化数据的，你应该自行导入
例如：vue-i18n 方式： https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/i18n
