### ISSUE TITLE
v2.10.15 Table內置放TextArea元件 編輯顯示問題

### ISSUE THREAD

**Issue by karenali** [x-extends/vxe-table#1309]
**（必填）请填写问题描述或截图：**
vxe-table-2.10.15 table內置放TextArea元件，觸發編輯時欄位高度無法隨內容縮放
![圖片](https://user-images.githubusercontent.com/29136484/111595985-a76cb500-8807-11eb-9635-3edd5ade711c.png)
![圖片](https://user-images.githubusercontent.com/29136484/111453195-4503ae00-874e-11eb-820f-48d5d6457288.png)

vxe-table-2.9.13 是正常的
![圖片](https://user-images.githubusercontent.com/29136484/111453214-4a60f880-874e-11eb-8a61-d86e83420bc9.png)
![圖片](https://user-images.githubusercontent.com/29136484/111596020-adfb2c80-8807-11eb-842e-b790ac08ef10.png)

**（必填）请填在线链接：**
[vxe-table-2.10.15 啟用編輯時顯示有問題](https://codesandbox.io/s/edit-closed-event-err-forked-i9djn?file=/src/main.js)

[vxe-table-2.9.13 正常](https://codesandbox.io/s/edit-closed-event-err-forked-hgpv4)

**（必填）请填写期望的结果：**
 希望於vxe-table 2.10.15 table置放自定元件，觸發編輯時欄位高度能隨內容縮放

**（必填）请填写以下信息：**

- OS: Ubuntu14.04
- Browser: Firefox 84.0.2、Chrome 86
- vue: 2.6.10
- vxe-table: 2.9.13、2.10.15

**Comment by xuliangzhan** [comment]
[show-overflow](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=show-overflow) 是单元格溢出隐藏，如果想要自适应行高必须去掉
https://codesandbox.io/s/edit-closed-event-err-forked-0jt9o

**Comment by karenali** [comment]
原來是這樣，感謝回覆~
