### ISSUE TITLE
tsx属性类型提示

### ISSUE THREAD

**Issue by agileago** [x-extends/vxe-table#1310]
**（必填）这个需求解决了什么问题：**
？
vite下使用tsx有属性提示以及类型提示

**截图或在线链接：**
？
![image](https://user-images.githubusercontent.com/11799110/111628283-055ec400-882b-11eb-9d4e-78ba7d3e1013.png)
没有任何属性提示
而`ant-design-vue`是全的
![image](https://user-images.githubusercontent.com/11799110/111628494-3e973400-882b-11eb-8cee-ae5ea912e8e4.png)

**建议的 API 是什么样的：**
？
希望支持`tsx`
**是否已有其他不错的替代方案：**
？

**Comment by agileago** [comment]
NB!!! 类型这次是你自己写的么？不是生成的？

**Comment by xuliangzhan** [comment]
本来就有现成的定义，不需要去生成😃

**Comment by agileago** [comment]
```jsx
import {Table, Column} from 'vxe-table'
const ListTable = (props, ctx) => {
  return <Table>
  <Column></Column>
</Table>
}
```
如果我没全局引入是不显示header的，看你代码里面直接 `resolveComponent('vxe-table-header')`了，这块后面是不是要重构掉？

**Comment by xuliangzhan** [comment]
按需加载分为两类：一种表格功能模块（必须 use 形式安装）；一种组件类（可选组件，可局部注册）
![image](https://user-images.githubusercontent.com/34864213/111997923-803f1c00-8b56-11eb-85c3-6f4697f88320.png)

**Comment by agileago** [comment]
了解
