### ISSUE TITLE
切换路由页面时, 表格渲染报错

### ISSUE THREAD

**Issue by wcldyx** [x-extends/vxe-table#1325]
**（必填）请填写问题描述或截图：**
路由切换时,存在过渡动画时 ,vxe-table表格报错: Cannot read property 'parentNode' of undefined;
![error](https://user-images.githubusercontent.com/26700595/112623230-f656b380-8de0-11eb-80c7-632c623fa12e.gif)
经过反复测试发现是 transition 过渡动画组件导致这个错误的，在不使用 transition 组件时是正常渲染表格的

**（必填）请填在线链接：**

https://codesandbox.io/s/vxe-table-3x-zai-transition-dewenti-j65nb?file=/src/App.vue

**（必填）请填写期望的结果：**
兼容路由过渡效果(transition)组件，正常渲染表格

**（必填）请填写以下信息：**

- OS: window10
- Browser: chrome89
- vue: 3.07
- vxe-table: 4.0.5

**Comment by xuliangzhan** [comment]
该问题会在下版本修复
https://codesandbox.io/s/vxe-table-3x-zai-transition-dewenti-forked-bpnv2
