### ISSUE TITLE
全局筛选功能，获取不到筛选的value值，返回一直是undefined

### ISSUE THREAD

**Issue by zsun-Jason** [x-extends/vxe-table#1327]
**（必填）请填写问题描述或截图：**
**采用vxe-grid 全局筛选, 定义全局筛选函数 filtterByReleaseType,**  
<vxe-grid
      :data="tableData"
      :columns="tableColumn"
      :filter-config="{ filterMethod: filterByReleaseType }"  >
 </vxe-grid>

**在tablbColumn定义filters**
tableColumn: [
        {
          title: "Product Release",
          fixed: "left",
          children: [
            { type: "seq", width: 50 },
            { field: "project_name", title: "Product" },
            { field: "rls_version", title: "Version", type: "html" },
            {
              field: "rls_type",
              title: "Type",
              sortable: true,
              **filters**: [
                { label: "Major", value: "major" },
                { label: "Maint", value: "maint" },
              ],

**在methods中定义filterByReleaseType()函数，用来接受处理filter 的 value值，但是每次打印接收到的都是undefined,**

filterByReleaseType({ value, row, column }) {
      **console.log(value); //value得不到被选中的filter的值**
      return row.rls_type === value;
    },

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-3x-vue-26-wentiyanshi-forked-uo373?file=/src/views/Demo1.vue:1328-1466

**（必填）请填写期望的结果：**
期望能够接收到value的值，后续在进行筛选处理

**（必填）请填写以下信息：**

- OS: MAC
- Browser: Chrome
- vue: 2.6
- vxe-table: 3.0.2

**Comment by zsun-Jason** [comment]
大概率还是自己配置出现了问题，这是一个最基本的功能，困扰我整整两天了，请大家帮忙指教，先谢谢大家了。

**Comment by xuliangzhan** [comment]
全局筛选方法 [table.filter-method](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=filter-method) 和列筛选方法 [column.filter-method](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=filter-method) 参数是不一样的
https://codesandbox.io/s/vxe-table-3x-vue-26-wentiyanshi-forked-e6ku3

**Comment by zsun-Jason** [comment]
完美解决，谢谢@xuliangzhan.
