### ISSUE TITLE
全局参数zIndex 无效 全局参数 table size 无效

### ISSUE THREAD

**Issue by XIAOAOAARON** [x-extends/vxe-table#1338]
**（必填）请填写问题描述或截图：**

![image](https://user-images.githubusercontent.com/34054781/114300149-5fcd0680-9af1-11eb-9ffa-9c255d26d643.png)

**（必填）请填在线链接：**

https://codesandbox.io/s/vxe-table-3x-vue-26-wentiyanshi-forked-8wfkb?file=/src/main.js
**（必填）请填写期望的结果：**

想要设置 zIndex 使得  tooltip 能够正常显示 , 就算重写 
:tooltip-config="{contentMethod: showTooltipMethodInfo, showAll:true,enterable:true}" 也不能正常显示
先要设置table size 一次性设置全局参数 . 
且想要设置统一的 emptyText  ! 不想要每个界面都设置一次 ! 
**（必填）请填写以下信息：**

- OS: windows
- Browser: Chrome/Edge
- vue: ^2.6.10
- vxe-table: ^3.2.9

**Comment by xuliangzhan** [comment]
更新到 2.10.15+ 可以支持 emptyText 全局
https://codesandbox.io/s/vxe-table-3x-vue-26-wentiyanshi-forked-wnq9m

**Comment by David-11z** [comment]
3.6.0版本按需加载全局配置tableloading参数无效 @xuliangzhan
