### ISSUE TITLE
4.0版本引入类型报错

### ISSUE THREAD

**Issue by jackjtr** [x-extends/vxe-table#1356]
（必填）请填写问题描述或截图：
TypeScript项目引入类型报错
![image](https://user-images.githubusercontent.com/6552755/115839719-82461480-a44d-11eb-9d5d-81820cee865f.png)

（必填）请填在线链接：
[https://codesandbox.io/s/vxe-table-4x-vue-30-wentiyanshi-forked-lk077?file=/src/views/Demo1.vue](https://codesandbox.io/s/vxe-table-4x-vue-30-wentiyanshi-forked-lk077?file=/src/views/Demo1.vue)

（必填）请填写期望的结果：
能够在TypeScript环境正常使用vxe-table定义的类型

（必填）请填写以下信息：

OS: Windows 10
Browser: Chrome
vue: 3.0.7
vxe-table: 4.0.13

**Comment by jackjtr** [comment]
已经自己解决，4.0.12升级到4.0.13后引入namespace即可

**Comment by xuliangzhan** [comment]
建议使用 import { VxeGridProps } from 'vxe-table'

**Comment by HyWell** [comment]
vue:3.1.2
vxe-table:4.1.18-beta.0
使用import { VxeGridProps } from 'vxe-table'无法引入对应类型，
![image](https://user-images.githubusercontent.com/21263451/146990335-475a5830-471f-43e5-a226-e5400da28105.png)

**Comment by tobegit3hub** [comment]
Same issue  and fail to import packages about `grid`.
