### ISSUE TITLE
向可编辑表格插入数据后，如果编辑组件是Antd，那么会导致方向键无法正常使用，删除后恢复正常

### ISSUE THREAD

**Issue by uniorder** [x-extends/vxe-table#1361]
**（必填）请填写问题描述或截图：**
当使用Antd作为编辑组件的时候（例如<a-input />），通过`table.insert({})`方式插入数据后无法正常使用键盘方向键进行cell的选择。将新增的数据删除后，方向键回复正常。

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-4x-vue-30-wentiyanshi-vxv3d?file=/src/App.vue

**（必填）请填写期望的结果：**
方向键能够正常使用

**（必填）请填写以下信息：**

- OS: Windows
- Browser: Chrome latest version
- vue: 3.0.0
- vxe-table: 4.0.14
- vxe-table-plugin-antd: 3.0.3
- Andt Vue: 2.1.2

**Comment by xuliangzhan** [comment]
该问题在 4.0.15+ 中是修复了的 https://codesandbox.io/s/vxe-table-4x-vue-30-wentiyanshi-forked-rwove

**Comment by uniorder** [comment]
多谢
