### ISSUE TITLE
我们项目table的列展示是数据传进来遍历的，列顺序可以改变还可以恢复，但是改变列顺序后，数据展示没有变

### ISSUE THREAD

**Issue by Guidozijef** [x-extends/vxe-table#1362]
比如，行号是第一列，订单号是第二列，我把列顺序换了后变成第一列是订单号，第二列是行号，但是此时数据还是展示的之前的数据列顺序，行号下面是订单号，订单号下面是行号，换头不换位，求解决方法，试过loadColumn方法，重新加载，但是有个问题，重载后把之前自带的多选框和序号给弄没了，

**Comment by DoveAz** [comment]
是不是在column上加key了，我发现不加key就可以动态变化，加了就不行
