### ISSUE TITLE
当循环列带有key的时候无法对column排序

### ISSUE THREAD

**Issue by DoveAz** [x-extends/vxe-table#1363]
**（必填）请填写问题描述或截图：**
当循环列带有key的时候列无法自动响应
**（必填）请填在线链接：**
https://jsrun.net/qP3Kp/edit

**（必填）请填写期望的结果：**
有key的时候列也能自动响应

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome 90
- vue: 2.0+
- vxe-table: 3.0+

**Comment by DoveAz** [comment]
#1362

**Comment by xuliangzhan** [comment]
静态列不能使用 for 换位置，仅支持改变属性参数；你应该使用 grid 动态表格：https://jsrun.net/ZP3Kp/edit
