### ISSUE TITLE
表格数据量大的时候，全选会有卡顿，能否优化

### ISSUE THREAD

**Issue by wubiandaxian** [x-extends/vxe-table#1388]
**（必填）这个需求解决了什么问题：**
在不用分页的情况下，一次性渲染几百条数据，全选会有卡顿，能否优化。比如官网的“虚拟滚动->最大高度”中的demo，600条数据全选，就有卡顿情况，我的数据达到800条，卡顿现象更明显

**截图或在线链接：**
https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/scroll/maxHeight

**建议的 API 是什么样的：**
能够优化全选的渲染速度，或者有比较好的可行性建议

**是否已有其他不错的替代方案：**
暂无

**Comment by kt3721** [comment]
我这500条就开始卡顿了，差不多1~2秒才有反应。数据量再大点直接卡死了~

**Comment by chenlei8910** [comment]
对于多选 type=checkbox 当数据量海量时应该绑定 checkbox-config 中的 checkField 属性渲染速度更快

**Comment by LadyChatterleyLover** [comment]
> 对于多选 type=checkbox 当数据量海量时应该绑定 checkbox-config 中的 checkField 属性渲染速度更快

请问一下，设置了checkField 属性为什么表格第一次默认全选了？

**Comment by xietiansheng** [comment]
> **（必填）这个需要解决了什么问题：** 在不使用分页的情况下，一次性流染几百条数据，全选会有卡顿，不能优化。比如官网的“虚毐” demo，600条数据全选，就有卡顿情况，我的数据达到800条，卡顿现象更明显
> 
> **截图或在线链接：** https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/scroll/maxHeight
> 
> **建议的API是什么样的：** 能够优化全选的冲洗速度，或者有比较好的可执行性建议
> 
> **是不是已经有其他不错的替代方案：** 暂无

请问这里是怎么解决的呢

**Comment by brightzoe** [comment]
> > 对于多选 type=checkbox 当数据量海量时应该绑定 checkbox-config 中的 checkField 属性渲染速度更快
> 
> 请问一下，设置了checkField 属性为什么表格第一次默认全选了？


假如这个属性写为 ’checkedField: checked‘, 则数据中都要有 checked 字段，初始数据中的 checked 字段要为 false。

默认第一次全选应该是因为你绑定的字段checked 被识别为 true 了。

简言之就是你绑定的对应字段是 falsy 还是 truthy 用于table 设置默认选中态。



@xietiansheng 看看设置这个属性能不能解决呢

**Comment by xieerduos** [comment]
> 设置了checkField 属性为什么表格第一次默认全选了？

我在table增加这个属性解决了   :checkbox-config="{checkField: 'checked'}"

```vue
  <vxe-table
      border="none"
      show-overflow
      :height="tableHeight"
      :row-config="{height: 66, isHover: true}"
      :checkbox-config="{checkField: 'checked'}"
      class="mytable-scrollbar"
      :data="tableData">
      <vxe-column type="checkbox" width="55" fixed="left" align="center"></vxe-column>
```

**Comment by doglex** [comment]
另一个可能的地方， console.log 太多也会导致卡顿

**Comment by ethanhome** [comment]
可以参考文档这里解决：https://vxetable.cn/v3/#/table/scroll/fullRows
