### ISSUE TITLE
使用展开行时，如果有固定列到最右会有bug

### ISSUE THREAD

**Issue by cnsdwu** [x-extends/vxe-table#1390]
![image](https://user-images.githubusercontent.com/23513790/118930987-07ebb000-b979-11eb-8e16-4a995a6ae606.png)

如果是固定到左边时拖动也会出现一些问题，比如文档中[https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/expand](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/expand)

**Comment by proxiti** [comment]
请问解决了吗
