### ISSUE TITLE
当语言设置为日本语时，列表翻页部分参数显示错误

### ISSUE THREAD

**Issue by myerwang** [x-extends/vxe-table#1391]
**（必填）请填写问题描述或截图：**
？ 当语言设置为日本语时，列表翻页部分参数显示错误。

**（必填）请填在线链接：**
？ https://codesandbox.io/s/gallant-cerf-6o50s

**（必填）请填写期望的结果：**
修正

**（必填）请填写以下信息：**

- OS: macos10
- Browser: chrome
- vue: 2.6.12
- vxe-table: 3.3.3

**Comment by xlz26296** [comment]
文档都有说明 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/i18n

**Comment by myerwang** [comment]
> 文档都有说明 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/i18n

在线测试都不看就扔个文档过来？切换到中文明显没问题，切换到日文参数就丢失，明显是bug。

顺便说一下，官方或许可以把单独设置某一国语言的代码贴出来，这样的需求其实还是很多的，而不是额外要装i18n。

虽然我已经知道怎么设置了，还是花了好几天时间，还是从外文网站找到的设置方法。

**Comment by xlz26296** [comment]
文档不是也都写得清清楚楚的吗，如果你不用vue-i18n，就得自行解决 "{0}" 占位符
![image](https://user-images.githubusercontent.com/34787386/119259263-fb2cbd80-bbff-11eb-9fe7-b7c7c97efdc8.png)

**Comment by myerwang** [comment]
> 文档不是写得清清楚楚的吗，如果你不用 `vue-i18n`，就得自行解决 "{0}" 占位符；如果使用 `vue-i18n` 自带占位符解析

我看lang语言文件里都有对应翻译，怎么这块又出来个占位符，我不需要额外翻译什么，系统带的那些就够了呀。

占位符怎么设置也没例子，这个配置会报告args参数未定义。

这个文档还真是架构师级别的，我这小白还真没看懂。

**Comment by myerwang** [comment]
> 文档那里应该写得很清楚的吧，如果你不用 `vue-i18n`，就得自行解决 "{0}" 占位符；如果使用 `vue-i18n` 自带占位符解析

我这链接打开的怎么没有你图片里那段代码？

**Comment by xlz26296** [comment]
使用vue-i18n解析国际化
```
VXETable.setup({
          i18n: (key, args) => i18n.t(key, args)
})
```

自行实现解析国际化
```
VXETable.setup({
          i18n: (key, args) => XEUtils.toFormatString(XEUtils.get(zhCN, key), args)
})
```

**Comment by myerwang** [comment]
原来之前配置前面参数忘写了一个args，非常感谢，是我的问题。
但是文档里确实没有，https://gitee.com/isni_admin/vxe-table-demo
在这里找到了你说的配置方法。
