### ISSUE TITLE
表格编辑模式渲染为 antd-vue 的 a-auto-complete时，出现无法用鼠标点击选择值

### ISSUE THREAD

**Issue by yangwb1123** [x-extends/vxe-table#1395]
**（必填）请填写问题描述或截图：**
使用渲染器或者插槽自定义编辑模式下的 cell 为 antd-vue 的 自动完成组件，出现鼠标无法选择下拉选项。具体情况请查看下面的链接。

**（必填）请填在线链接：**
http://jsrun.net/epVKp/edit

**（必填）请填写期望的结果：**
修复 bug，使鼠标可以选择

**（必填）请填写以下信息：**

- OS: Manjaro 21.0.5 Ornara
- Browser: 90.0.4430.212（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 3.3.4

**Comment by xuliangzhan** [comment]
可以使用  [vxe-table-plugin-antd](https://github.com/x-extends/vxe-table-plugin-antd) 适配插件 http://jsrun.net/hkVKp/edit
或者自行解决 [事件冲突](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/interceptor/api) 都可以
