### ISSUE TITLE
启用 KeepAlive 后，表格无法显示 

### ISSUE THREAD

**Issue by Ttou** [x-extends/vxe-table#1399]
**（必填）请填写问题描述或截图：**
如果使用了 KeepAlive 包裹路由，从其他页面进入表格页会报错，表格无法显示，刷新后正常；生产环境无法看到错误信息，开发环境错误如下：
![屏幕截图 2021-05-28 234617](https://user-images.githubusercontent.com/4298437/120009792-ef316900-c00e-11eb-83dd-afaf8fbd48ba.png)

**（必填）请填在线链接：**
源码地址：https://gitee.com/jh_shot/admin-template.git
演示地址：http://jh_shot.gitee.io/admin-template/

**（必填）请填写期望的结果：**
表格正常显示

**（必填）请填写以下信息：**

- OS: windows 10
- Browser: edge 91.0.864.37
- vue: 3.0.11
- vxe-table: 4.0.19

**Comment by xuliangzhan** [comment]
该问题会在下版本修复
