### ISSUE TITLE
设置了 show-footer 后通过按住 shift + 鼠标滚轮横向滚动表格时滚动速度非常慢

### ISSUE THREAD

**Issue by elewen** [x-extends/vxe-table#1400]

**Comment by elewen** [comment]
更新：
1. 当开启了 show-footer 时，光标必须放在 vxe-table--footer-wrapper 才能正常使用 shift + 鼠标滚轮横向滚动功能；光标放在 vxe-table--body-wrapper 上时 shift + 鼠标滚轮横向滚动速度很慢；光标放在 vxe-table--header-wrapper 上时 shift + 鼠标滚轮横向滚动无任何反应。
2. 当不开启 show-footer 时，光标放在 vxe-table--header-wrapper 上时 shift + 鼠标滚轮横向滚动无任何反应。

期望的结果：无论是否 show-footer，且无论光标放在 vxe-table--header-wrapper、vxe-table--body-wrapper、vxe-table--footer-wrapper 上时，只要表格有横向滚动条，都能通过shift + 鼠标滚轮横向正常滚动。

**Comment by MadiniGo** [comment]
我也发现了这个问题，设置了 show-foote，shfit+滚轮还有笔记本触控板滚动也是会非常慢

**Comment by changlin666666** [comment]
+1,期望作者大大加把劲
