### ISSUE TITLE
希望v4.0版本中【 ProxyAjaxQueryParams，ProxyAjaxDeleteParams，ProxyAjaxSaveParams，ProxyAjaxQueryFiltersParams】 这个几个类型能添加 $table，$grid两个属性

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1402]
**（必填）这个需求解决了什么问题：**
希望【ProxyAjaxQueryParams，ProxyAjaxDeleteParams，ProxyAjaxSaveParams，ProxyAjaxQueryFiltersParams】 这个几个类型添加 $table，$grid，就像ProxyAjaxQueryAllParams参数一样，因为写一些通用函数时候需要用到这个两个属性。
**截图或在线链接：**
![image](https://user-images.githubusercontent.com/4531974/120576699-cae1ec00-c455-11eb-8370-a7f9005e13ca.png)

**建议的 API 是什么样的：**
```
  interface ProxyAjaxQueryParams {
    $table: VxeTableConstructor;
    $grid: VxeGridConstructor;
    page: ProxyAjaxQueryPageParams;
    sort: ProxyAjaxQuerySortCheckedParams;
    sorts: ProxyAjaxQuerySortCheckedParams[];
    filters: ProxyAjaxQueryFiltersParams[];
    form: any;
  }
```
**是否已有其他不错的替代方案：**

**Comment by xuliangzhan** [comment]
可以的，下版本可以支持
