### ISSUE TITLE
ProxyAjaxQueryParams 中，传过来的 $grid 是默认的配置，应该是传赋值后的 $grid实例

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1408]
**（必填）请填写问题描述或截图：**

ProxyAjaxQueryParams 参数传过来的$grid ，应该是赋值了gridOptions 的grid，目前是默认配置的grid

如图中 $grid.params 应该打印 { url: "www.qq.com" }

![image](https://user-images.githubusercontent.com/4531974/121327283-e4979d80-c945-11eb-9082-c2cfc7bfead8.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/reverent-hamilton-o32hj?file=/src/components/HelloWorld.vue

**（必填）请填写期望的结果：**
希望传过来的$grid 是赋值后的

**（必填）请填写以下信息：**

- OS:  windows server 2008R2？
- Browser: chrome ？
- vue:  3.1.1？
- vxe-table: 4.0.21？

**Comment by xuliangzhan** [comment]
在 v4 版本中，参数中已经没有 vue 实例了，拿到是Grid对象，可以通过 $grid.props 获取组件参数

**Comment by jianliulin** [comment]
$grid 如何添加自定义函数，类似app.config.globalProperties.$XPrint = VXETable.print这样，
