### ISSUE TITLE
请问使用webpack打包的项目是否在配置上要注意什么？我在自有项目里添加编辑表格的自定义组件，输入数据无效

### ISSUE THREAD

**Issue by renyi818** [x-extends/vxe-table#1410]
**（必填）请填写问题描述或截图：**
？
![image](https://user-images.githubusercontent.com/30144443/121705986-c7123180-cb07-11eb-924d-5416d2415a74.png)
我在自有项目里添加表格的自定义组件，发现无法触发输入值联动，但是在github上下载下来的vxe-demo项目，使用相同的代码是能执行的， 并且我将两个项目使用的package.json组件版本调整到一致，也还是出现本项目不触发updateStatus的情况。 我仔细对比两边的项目，可能主要的差异就在于我现在的自有项目是使用webpack打包的。 
**（必填）请填在线链接：**
？https://github.com/xuliangzhan/vxe-table-demo 这是我下载下来测试的代码。使用这个代码我运行是正常执行的，但是一旦拷贝到我的自有项目，就无法触发。 如果不用自定义组件，直接使用:edit-render="{name: 'input' 也是能正常更新的。

**（必填）请填写期望的结果：**
？添加自定义组件能正常触发输入框的值更新。

**（必填）请填写以下信息：**
使用的代码如下：
`VXETable.renderer.add('myInput', {
  // 激活时自动聚焦
  autofocus: '.my-cell',
  // 可编辑激活模板
  renderEdit(h, renderOpts, params) {
    const { row, rowIndex, $rowIndex, column, columnIndex, $columnIndex, $table } = params
    console.log('renderEdit -> row, rowIndex, $rowIndex, column, columnIndex, $columnIndex, $table', row, rowIndex, $rowIndex, column, columnIndex, $columnIndex, $table)

    return [
      <vxe-input class='my-cell' v-model={ row[column.property] } prefix-icon='fa fa-user' suffix-icon='fa fa-search' clearable></vxe-input>
    ]
  },
  // 可编辑显示模板
  renderCell(h, renderOpts, { row, column }) {
    console.log('renderCell -> column', column)
    console.log('renderCell -> row', row)
    return [
      <span>{row[column.property]}</span>
    ]
  }
})`

我有在webpack添加如下内容：
`module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/webpack-dev-server/client'),
          resolve('node_modules/element-ui/src'),
          resolve('node_modules/element-ui/packages'),
          resolve('node_modules/vxe-table')
        ]
      },`
- OS:Mac
- Browser: Chrome
- vue: 2.6.12
- vxe-table: 3.3.6 和3.3.7均试过
- xe-utils： 3.2.1
- element-ui: 2.12.0

**Comment by xuliangzhan** [comment]
如果是使用 vue-cli 的话是不需要额外配置的，jsx相关的转换都已经默认集成，可以尝试使用一个空项目去找一下问题

**Comment by renyi818** [comment]
> 如果是使用 vue-cli 的话是不需要额外配置的，jsx相关的转换都已经默认集成，可以尝试使用一个空项目去找一下问题

谢谢大佬回复！是的，使用vue-cli建立的项目是没问题的，这两天我都在不断的建立新项目测试。我测试的时候，就发现测试用的xuliangzhan/vxe-table-demo 用的是vue-cli建立的项目，而不巧的是，我现有项目是早期项目，没有使用vue-cli，使用的配置文件是webpack.base.conf.js。两遍的package.json也改为引入同样的组件。唯一的差异就是，一边用的是vue-cli，一边是用的webpack;
package.json内引入的是如下版本的webpack组件
"webpack": "4.16.5",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "3.1.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "4.1.4"
我一开始以为是babel-loader的问题，升级到了7.1.5。 结果还是测试失败。不知道是不是哪里需要调整配置？我的.babelrc文件的内容配置如下：
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins":["transform-vue-jsx", 
    "transform-runtime", 
    "transform-es2015-modules-commonjs",
    [
      "import",
      {
        "libraryName": "vxe-table",
        "style": true // 样式是否也按需加载
      }
    ]
  ]
}
`
我的webpack.base.conf.js节选如下：
`module: {
    rules: [
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/webpack-dev-server/client'),
          resolve('node_modules/element-ui/src'),
          resolve('node_modules/element-ui/packages'),
          ...vxeTableDirs,
          ...bigTableDirs
        ]
      },
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/icons')],
        options: {
          symbolId: 'icon-[name]'
        }
      },`

**Comment by renyi818** [comment]
我放弃了，尝试更换成vue-cli来打包了，重写了vue.config.js ，这个问题暂时关闭吧。谢谢
