### ISSUE TITLE
vxe-grid 配置pager-config.layouts:["Number"] 中的Number不显示页编号

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1413]
**（必填）请填写问题描述或截图：**
vxe-grid 配置pager-config.layouts:["Number"] 中的Number不显示页编号，
![image](https://user-images.githubusercontent.com/4531974/122003987-62482700-cde6-11eb-9fe8-eb504410f0f8.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/reverent-hamilton-o32hj?file=/src/components/HelloWorld.vue:545-552

**（必填）请填写期望的结果：**
正确显示页编号

**（必填）请填写以下信息：**

- OS:  windows 2008r2
- Browser: chrome
- vue: 3.x
- vxe-table: v4.x？

**Comment by xuliangzhan** [comment]
该问题会在下版本修复
