### ISSUE TITLE
$XModal.open() 方式打开modal，vxe-form 标签不显示控件

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1414]
**（必填）请填写问题描述或截图：**
$XModal.open() 方式打开modal，vxe-form 标签不显示控件，vxe-table v3.x 是正常的。
![image](https://user-images.githubusercontent.com/4531974/122170850-a18f7a00-ceb1-11eb-83c9-a6e33eb10967.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/reverent-hamilton-o32hj?file=/src/components/HelloWorld.vue

**（必填）请填写期望的结果：**
正确显示vxe控件

**（必填）请填写以下信息：**

- OS:  windows 2008r2
- Browser: chrome
- vue:  3.x
- vxe-table: 4.x

**Comment by xuliangzhan** [comment]
建议可以先去查阅 vue3 的相关文档，渲染函数用法是完全不同的，建议使用 jsx
https://v3.cn.vuejs.org/guide/render-function.html#%E5%88%9B%E5%BB%BA%E7%BB%84%E4%BB%B6-vnode
https://codesandbox.io/s/mystifying-goldstine-4engo
