### ISSUE TITLE
树形表格选取与pager问题

### ISSUE THREAD

**Issue by Jimlikezebra** [x-extends/vxe-table#1448]
**（必填）请填写问题描述或截图：**
复选框数据，vxe-grid设置了reserve为true ，切换到下一页，无法记录上一次选中的数据.

![圖片](https://user-images.githubusercontent.com/25003602/125728707-41727289-f919-4df0-9dc7-c01c81c3c6cd.png)
切换到下一页
![圖片](https://user-images.githubusercontent.com/25003602/125728736-34842be0-92a7-42d5-aa67-c8eda64f9ccc.png)
选了序号 1 和 7，只选中1笔.

**（必填）请填在线链接：**
http://jsrun.net/7RVKp/edit

**（必填）请填写期望的结果：**
选了序号 1 和 7，要选中2笔.

**（必填）请填写以下信息：**
OS: win 10
Browser: chrome
vue: 2.9.6
vxe-table: 3.3.6

**Comment by xlz26296** [comment]
缺少主键 row-id，这个文档说得很清楚了 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=reserve
