### ISSUE TITLE
树形表格选取问题

### ISSUE THREAD

**Issue by Jimlikezebra** [x-extends/vxe-table#1449]
**（必填）请填写问题描述或截图：**
vxe-grid设置了reserve为true ，切换到下一页，无法记录上一次选中的数据.
选了序号 1 和 7，只选中1笔.

![圖片](https://user-images.githubusercontent.com/25003602/125729605-7f303a1c-e96f-4797-9406-53741f31c768.png)
![圖片](https://user-images.githubusercontent.com/25003602/125729621-00fa01d6-8f71-4ba7-bd60-783161ec3d2a.png)

**（必填）请填在线链接：**
http://jsrun.net/7RVKp/edit

**（必填）请填写期望的结果：**
选了序号 1 和 7，要选中2笔.

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.9.6
- vxe-table: 3.3.6

**Comment by xlz26296** [comment]
缺少主键 row-id，文档有说明 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=reserve

**Comment by Jimlikezebra** [comment]
有填,忘了放上去
row-id填了一样有bug
http://jsrun.net/7RVKp/edit 已更新

**Comment by Jimlikezebra** [comment]
切换到下一页,前一页选的就不见了
