### ISSUE TITLE
清除筛选函数的clearFilter()报错

### ISSUE THREAD

**Issue by wangfh** [x-extends/vxe-table#1457]
**（必填）请填写问题描述或截图：**
？筛选后，清除筛选的函数clearFilter()报错:Cannot destructure property 'slots' of 'column' as it is null.
![image](https://user-images.githubusercontent.com/2703804/127084850-5aa66328-69bd-4767-a6aa-469c5a97b013.png)

**（必填）请填在线链接：**
？https://codesandbox.io/s/gracious-sanderson-z7s21?file=/src/App.vue:108-121

**（必填）请填写期望的结果：**
？请解决此bug

**（必填）请填写以下信息：**

- OS: win10
- Browser: Microsoft Edge 版本 92.0.902.55 
- vue: 3.1.1
- vxe-table: 4.0.24

**Comment by xuliangzhan** [comment]
该问题再最新版本中修复
