### ISSUE TITLE
vxe-grid v4.x使用动态控件<Suspense> 后，如果setup()函数前加async会引起表头宽度错乱，反之正常

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1474]
**（必填）请填写问题描述或截图：**

vxe-grid v4.x使用动态控件<Suspense> 后，如果setup()函数前加async会引起表头宽度错乱，反之正常

![image](https://user-images.githubusercontent.com/4531974/129325967-27edf417-ac6e-4d8d-b1b6-007515de06df.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/upbeat-golick-102gt?file=/src/Demo.vue

**（必填）请填写期望的结果：**
希望表头宽度正常，或者grid添加一个异步获取grid配置的函数，可以通过这个函数从后台获取配置

**（必填）请填写以下信息：**

- OS:  winserver 2016
- Browser:  chrome
- vue:  3.15
- vxe-table:  4.0.26

**Comment by jianliulin** [comment]
@yokochen222  请问这个问题你解决了吗？

**Comment by xuliangzhan** [comment]
可以更新到最新版本

**Comment by jianliulin** [comment]
谢谢！！
