### ISSUE TITLE
vxe-grid v4.x的单元格渲染中如何发布自定义事件

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1475]
**（必填）这个需求解决了什么问题：**
     单元格渲染中 v3.x版本中可以直接用 $table.$emit('aclick',{$table} )  来发布一个自定义事件，在4.x中好像失效了，如果想发布这样的自定义事件，该如果做？。

**截图或在线链接：**
![image](https://user-images.githubusercontent.com/4531974/129330735-6e375e40-27cd-4a44-a2d1-a56983ed4acb.png)

**建议的 API 是什么样的：**
无

**是否已有其他不错的替代方案：**
无

**Comment by xuliangzhan** [comment]
可以使用 events 去自行实现回调，不管是哪个版本都不应该这样用
