### ISSUE TITLE
vxe-grid v4.x 中的渲染函数renderEdit(renderOpts, params)  中params的$table希望能加入editRules 和params 两个属性

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1483]
**（必填）这个需求解决了什么问题：**
vxe-grid v4.x 中的渲染函数renderEdit(renderOpts, params)  中params的$table希望能加入editRules 和params 两个属性，v3.x版本是存在这个两个参数的。

**截图或在线链接：**

![image](https://user-images.githubusercontent.com/4531974/130014204-542872a3-62db-4bf5-8caf-09ae8cecde36.png)

**建议的 API 是什么样的：**
和v3.x版本一样，传入这个两个参数，方便自定义扩展。

**是否已有其他不错的替代方案：**
？

**Comment by xuliangzhan** [comment]
vue3版本已经去除 this，$table 为表格实例，可以通过 `$table.props` 获取参数
