### ISSUE TITLE
使用elementui插件时，带动画组件在虚拟滚动中抖动

### ISSUE THREAD

**Issue by Lucius-CN** [x-extends/vxe-table#1524]
**（必填）请填写问题描述或截图：**
使用elementui插件时，带动画组件在虚拟滚动中抖动

**（必填）请填在线链接：**
https://codesandbox.io/embed/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-8m9b9?fontsize=14&hidenavigation=1&theme=dark

**（必填）请填写期望的结果：**
使用虚拟滚动时，动画组件不抖动

**（必填）请填写以下信息：**

- OS: Win10专业版1903
- Browser: Chrome90.0.4430.93
- vue: 2.0
- vxe-table: 3.x

**Comment by xlz26296** [comment]
这是vue的复用元素，要想不复用需要加上 [row-key](https://x-extends.github.io/vxe-table/#/table/api?q=row-key)
