### ISSUE TITLE
表格排序调用远程方法后，标题的 排序图标不会刷新

### ISSUE THREAD

**Issue by abings** [x-extends/vxe-table#1544]
**（必填）请填写问题描述或截图：**
表格排序调用远程方法后，标题的 排序图标不会刷新

**（必填）请填在线链接：**
http://jsrun.net/TRTKp/edit

**（必填）请填写期望的结果：**
请帮助处理下

**（必填）请填写以下信息：**

- OS: mac
- Browser: google
- vue: vue3
- vxe-table: 4.0.28

**Comment by xuliangzhan** [comment]
该问题会在 v4.0.30+ 修复
http://jsrun.net/pkUKp/edit

**Comment by zphtown** [comment]
已经找到解决办法，猜测是组件的问题
思路：把data单独拿传参，不放到v-bind
1. <vxe-table v-bind="{tableConfig}" data="data" />
2. 备注：如果写的是jsx，就写成如下
<vxe-table {...tableConfig} data={data} />
