### ISSUE TITLE
vxe-table 配置 row-config 行高不生效

### ISSUE THREAD

**Issue by wananle** [x-extends/vxe-table#1557]
设置 row-config 行高不生效， vxe-grid 也是一样
https://codesandbox.io/s/currying-star-m0z6u?file=/src/components/HelloWorld.vue

**Comment by fengpang** [comment]
> [row-config](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=pro)是4.1才支持的功能

![image](https://user-images.githubusercontent.com/30470182/150295284-90249047-8cdf-41f6-a1fa-0061451ac595.png)
v3的文档里面有的哇
