### ISSUE TITLE
使用insertAt插入行，如何插入在某一行的下方

### ISSUE THREAD

**Issue by wallowbear** [x-extends/vxe-table#1577]
示例的插入数据有三种位置，首尾及特定行。
特定行插入行是插入在点击行的上方，现在我想在下方插入新的行请问要如何实现？

**Comment by chitongyu** [comment]
可以简单的判断一下当前行是否本身还有下一行
let nextRow = data[rowIndex + 1]; // 下一行
let newRow = row; // 新增行
Reflect.deleteProperty(nextRow,'id'); // 删除id，id会影响索引
if(nextRow) {
  // 还有下一行，则在下一行之前新增一行
  insertAt(newRow,nextRow)
}else {
  // 没有下一行，则在最后新增一行
  insertAt(newRow,-1)
}
原文：往表格插入临时数据，从指定位置插入一行或多行；第二个参数：row 指定位置、null从第一行插入、-1 从最后插入

**Comment by layxyer** [comment]
碰到了相同的问题,回答中的解决方式像树这种结构是有问题的,是在想不明白为什么不提供可控制插入节点前后的方法,跟踪代码应该可以通过修改findTree方法中的index来解决,但是这种搞起来有点麻烦
