### ISSUE TITLE
自3.4.7+版本以后的普通树形表格，展开后子记录层级序号显示为-1

### ISSUE THREAD

**Issue by ginkosen** [x-extends/vxe-table#1593]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-l2mm0?file=/src/views/Demo1.vue

### 问题描述与截图：

自**3.4.7+**版本以后的**普通树形表格**，展开后子记录**层级序号**显示为-1
![image](https://user-images.githubusercontent.com/2233819/144577792-48f87b95-a25d-48a6-ad5b-5de0b0b1e149.png)

### 期望的结果：

展开后层级序号计算正确

### 操作系统：

macOX

### 浏览器版本：

Chrome/96.0.4664.45

### vue 版本：

2.6+

### vxe-table 版本：

3.4.7+

**Comment by xuliangzhan** [comment]
该问题在 v3.4.11+修复
https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-i4knf?file=/src/views/Demo1.vue

**Comment by ginkosen** [comment]
Thanks
