### ISSUE TITLE
vxe-grid 导出 csv表格  自动省略0 

### ISSUE THREAD

**Issue by fufengren** [x-extends/vxe-table#1597]
### 可复现的链接：

https://x-extends.github.io/vxe-table/v4/table/grid/toolbarIcon

### 问题描述与截图：

![Snipaste](https://user-images.githubusercontent.com/76684168/145010340-e7b7634f-ea40-427f-802b-9c62e7ff5e02.png)

### 期望的结果：

可以不做 自动过滤0 

### 操作系统：

windo10

### 浏览器版本：

chrome 96.0.4664.45

### vue 版本：

vue3

### vxe-table 版本：

4

**Comment by 908023777** [comment]
![image](https://user-images.githubusercontent.com/37042827/145130543-f95634f4-644e-4397-a33a-b9ebca447dd6.png)
导出类型改成文本就可以了
