### ISSUE TITLE
文档挂了，没法看

### ISSUE THREAD

**Issue by Garland-Huang** [x-extends/vxe-table#1609]
### 可复现的链接：

https://xuliangzhan_admin.gitee.io/vxe-table/#/grid/api

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/46437704/146742345-8588d366-8f8f-491b-b8a3-22cff5c528f2.png)

文档挂了，没法看

### 操作系统：

window10

### 浏览器版本：

96.0.4664.110

### vue 版本：

4.5.15

### vxe-table 版本：

4.0

**Comment by xuliangzhan** [comment]
已恢复了
