### ISSUE TITLE
EditConfig.activeMethod传入的参数能否添加$grid,方便写通用函数，根据不同的grid执行不同的代码。

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#1616]
### 这个需求解决了什么问题：

EditConfig.activeMethod传入的参数能否添加$grid,方便写通用函数，根据不同的grid执行不同的代码。

  export interface EditConfig {
    trigger?: 'manual' | 'click' | 'dblclick';
    mode?: string;
    icon?: string;
    showIcon?: boolean;
    showStatus?: boolean;
    showUpdateStatus?: boolean;
    showInsertStatus?: boolean;
    showAsterisk?: boolean;
    autoClear?: boolean;
    /**
     * 该方法的返回值用来决定该单元格是否允许编辑
     */
    activeMethod?(params: {
      row: any;
      rowIndex: number;
      column: VxeTableDefines.ColumnInfo;
      columnIndex: number;
    }): boolean;
  }

### 建议的 API 是什么样的：

   activeMethod?(params: {
      $grid: VxeGridConstructor | null | undefined;
      row: any;
      rowIndex: number;
      column: VxeTableDefines.ColumnInfo;
      columnIndex: number;
    }): boolean;

### 是否已有其他不错的替代方案：

无

**Comment by xuliangzhan** [comment]
下版本可以考虑支持

**Comment by jianliulin** [comment]
谢谢！！！
