### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by wuchaoxin** [x-extends/vxe-table#1620]
### 可复现的链接：

很遗憾，我没能在 codesandbox 中复现，猜测这只是在 chrome 才能复现的问题。

## 现象：
Chrome 浏览器中，window.error 捕获到错误：ResizeObserver loop limit exceeded。Safari 不受影响。

## 如何复现

在代码中加入（并且在 chrome 浏览器中打开）
```js
 window.addEventListener(
    "error",
    (err) => {
      console.log("globalError", err);
    },
    true
  );
```

## 原因：
通过查询 issues https://github.com/x-extends/vxe-table/issues/302
这个问题似乎是加入 ResizeObserver 引发的问题。

### 期望的结果：

window.error 不再捕获到错误

### 操作系统：

macOS Big Sur 11.5.1

### 浏览器版本：

chrome 91.0.4472.114

### vue 版本：

3.2.4

### vxe-table 版本：

4.1.18

**Comment by dyywork** [comment]
楼主解决了吗
