### ISSUE TITLE
range 失效，无法范围选择

### ISSUE THREAD

**Issue by gening110** [x-extends/vxe-table#1622]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-7g9kw?file=/src/views/Demo1.vue

### 问题描述与截图：

当设置了固定列，改变表格容器的宽度，如果没有下面的滚动条，range失效，滚动条出现，range生效

或者表格容器设置了display:none; 再显示，range也失效
![image](https://user-images.githubusercontent.com/58022048/148373439-f865943c-58f4-4f55-a726-7bb4d892ca86.png)

![image](https://user-images.githubusercontent.com/58022048/148373635-6b193d51-a27e-462f-9f0c-d1e3c26caacd.png)

### 期望的结果：

一直可以范围选中

### 操作系统：

win7

### 浏览器版本：

chrome 95

### vue 版本：

2.6

### vxe-table 版本：

2.1或3.4都不行

**Comment by gening110** [comment]
3.4也不行

**Comment by gening110** [comment]
> _**机器人助手：**_
> 
> * 皱眉脸 该版本已停止维护，建议更新到最新版本

3.4 也不行

**Comment by gening110** [comment]
> > _**机器人助手：**_
> > 
> > * 皱眉脸 该版本已停止维护，建议更新到最新版本
> 
> 3.4 也不行

3.x的版本修复了吗

**Comment by xuliangzhan** [comment]
已修复，建议更新到最新版本
https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-pc940
