### ISSUE TITLE
vxe-toolbar中使用vxe-select无法选择的问题

### ISSUE THREAD

**Issue by citystory** [x-extends/vxe-table#1640]
### 可复现的链接：

https://jsrun.net/LJ9Kp

### 问题描述与截图：

之前旧版本运行一切正常，升级到最新版本后，1、是选项无法异步获取添加上去。2、即使提前写好的选项，点击选项后，没有任何变化。

### 期望的结果：

异步能正常赋值，点击选项后能正常变化。

### 操作系统：

win 10

### 浏览器版本：

97.0.4692.71

### vue 版本：

2.6.14

### vxe-table 版本：

3.4.13

**Comment by citystory** [comment]
经测试，在2.11.0以及之前可以，从3版本开始，就用不了了。

**Comment by xlz26296** [comment]
你插槽的用法不对，插槽要用 #default 或 v-slot
 ```html
<vxe-form-item>
  <template #default>
    <input v-model="test1">
  </template>
</vxe-form-item>
```
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/form

**Comment by citystory** [comment]
哦，之前2的版本，没有用插槽，没有注意到这个变化，经测试按照你说的插槽方式，是可以正常运行的，谢谢。
