### ISSUE TITLE
xtable编辑状态时下拉框无效

### ISSUE THREAD

**Issue by 535944903** [x-extends/vxe-table#1641]
### 可复现的链接：

https://codesandbox.io/s/nostalgic-shtern-nihqf?file=/src/App.vue

### 问题描述与截图：

通过我们官网对着demo集成了element plus。 希望编辑时使用 element plus的 下拉框。  但是点击下拉没有效果。 文本框是有效可用的。 使用咱们自己的下拉是没问题的，换成element plus就有问题了。

### 期望的结果：

下拉选中后值获得改变

### 操作系统：

win10

### 浏览器版本：

chrome95

### vue 版本：

3.2

### vxe-table 版本：

4.1.19

**Comment by xlz26296** [comment]
文档都有说明的，你要使用第三方组件时，是需要自己解决事件冲突问题。或者安装 [vxe-table-plugin-element](https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/other/element) 适配插件
```javascript
import VXETable from 'vxe-table'
import VXETablePluginElement from 'vxe-table-plugin-element'
VXETable.use(VXETablePluginElement)
```

**Comment by 535944903** [comment]
非常感谢，非常感谢
