### ISSUE TITLE
vxe-column，width如果设置为小数，table列宽度没有正常渲染。

### ISSUE THREAD

**Issue by 65min** [x-extends/vxe-table#1643]
### 可复现的链接：

https://codesandbox.io/s/vxe-column-width-bug-20220127-6klz5?file=/src/views/Demo1.vue

### 问题描述与截图：

vxe-column，width设置为整数，table列宽度渲染没问题，如果设置为小数，table列宽度没有正常渲染。
![image](https://user-images.githubusercontent.com/11242340/151283386-89b43896-1df3-43da-9bbd-74403ba6a12a.png)

### 期望的结果：

期望宽度能够按参数正常渲染

### 操作系统：

windows11

### 浏览器版本：

chrome 91.0.4472.77

### vue 版本：

2.6.14

### vxe-table 版本：

3.4.13

**Comment by xuliangzhan** [comment]
不支持小数，目前只支持整数
