### ISSUE TITLE
建议height等类似属性支持calc计算

### ISSUE THREAD

**Issue by svipchao** [x-extends/vxe-table#1689]
### 这个需求解决了什么问题：

更好的进行页面布局

### 是否已有其他不错的替代方案：

将父元素高度固定，设置max-height为100%

**Comment by huzedong2015** [comment]
vex-grid height: 100% 可以，但是如果加了toolbar 就不行了。

**Comment by xjphhh** [comment]
原来是table自带的bug，我说怎么100%就是撑不开高度，短一截
