### ISSUE TITLE
文档->基础表格的“多选表格，通过配置 trigger 设置触发源，使用渲染最快的 checkField 属性绑定方式:checkbox-config="{checkField: 'checked', trigger: 'row'}"无效

### ISSUE THREAD

**Issue by fengyun2** [x-extends/vxe-table#1705]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-element-ui-syos5n?file=/src/components/VxeTable/index.vue

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/8147202/163792277-c126743e-77f2-4b7e-82e7-a9a5aa0f913d.png)

设置了`:checkbox-config="{checkField: 'checked', trigger: 'row'}"` 后，无法选中复选框。

### 期望的结果：

可以选中复选框

### 操作系统：

window10

### 浏览器版本：

chrome 99.0.4844.74

### vue 版本：

2.6.1

### vxe-table 版本：

3.5.4

**Comment by xlz26296** [comment]
你既然绑定了 checkField 字段名，你那字段哪去了？

**Comment by fengyun2** [comment]
已解决
