### ISSUE TITLE
在qinkun动态渲染select option无法显示

### ISSUE THREAD

**Issue by Acidhj** [x-extends/vxe-table#1706]
### 可复现的链接：

暂无

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/34772657/164952279-cd627c59-03d7-4c55-aba0-896cda426770.png)
改用el-select就可以显示,但是很卡  vxe流程  但是option不显示

qiankun版本:2.7.0

### 操作系统：

windows11

### 浏览器版本：

99.0.4844.82

### vue 版本：

3.2.2

### vxe-table 版本：

4.2.1

**Comment by qiangxue1206** [comment]
https://github.com/umijs/qiankun/issues/2120
