### ISSUE TITLE
html页面中出现Object(...) is not a function

### ISSUE THREAD

**Issue by hzyuanhai** [x-extends/vxe-table#1711]
### 可复现的链接：

html

### 问题描述与截图：

var app = new Vue({
    el: '.vue-box',
    data() {
        return {
            gridOptions1: {
                border: true,
                resizable: true,
                showOverflow: true,
                height: 300,
                align: 'left',
                toolbarConfig: {
                    slots: {
                        // 自定义工具栏模板
                        buttons: 'toolbar_buttons'
                    }
                },
                columns: [
                    { type: 'seq', width: 50 },
                    { field: 'name', title: 'Name' },
                    { field: 'sex', title: 'Sex', showHeaderOverflow: true },
                    { field: 'address', title: 'Address', showOverflow: true }
                ],
                data: [
                    { id: 10001, name: 'Test1', nickname: 'T1', role: 'Develop', sex: 'Man', age: 0, address: 'Shenzhen' },
                    { id: 10002, name: 'Test2', nickname: 'T2', role: 'Test', sex: 'Women', age: 22, address: 'Guangzhou' },
                    { id: 10003, name: 'Test3', nickname: 'T3', role: 'PM', sex: 'Man', age: 100, address: 'Shanghai' },
                    { id: 10004, name: 'Test4', nickname: 'T4', role: 'Designer', sex: 'Women', age: 70, address: 'Shenzhen' },
                    { id: 10005, name: 'Test5', nickname: 'T5', role: 'Develop', sex: 'Women', age: 10, address: 'Shanghai' },
                    { id: 10006, name: 'Test6', nickname: 'T6', role: 'Designer', sex: 'Women', age: 90, address: 'Shenzhen' },
                    { id: 10007, name: 'Test7', nickname: 'T7', role: 'Test', sex: 'Man', age: 5, address: 'Shenzhen' },
                    { id: 10008, name: 'Test8', nickname: 'T8', role: 'Develop', sex: 'Man', age: 80, address: 'Shenzhen' }
                ]
            },
        }
    },
    methods: {
    },
    created: function () {
      
    },
    mounted: function () {
    },
    updated: function () {
    },
    ready: function () {
    },
});
这个页面在浏览器中浏览出现
Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (vxe-table:1)
    at n (vxe-table:1)
    at 00ee (vxe-table:1)
    at vxe-table:1
    at vxe-table:1
    at vxe-table:1
错误,页面无法展示Grid表格

### 操作系统：

window10

### 浏览器版本：

Google Chrome版本 100.0.4896.127（正式版本） （64 位）

### vue 版本：

2.6.14

### vxe-table 版本：

3.5.6

**Comment by Lruihao** [comment]
请问这个问题怎么解决的。
