### ISSUE TITLE
ref({} as VxeTableInstance)?

### ISSUE THREAD

**Issue by dishcheng** [x-extends/vxe-table#1750]
### 可复现的链接：

ss

### 问题描述与截图：

https://vxetable.cn/#/table/advanced/template

这段代码我用的编辑器是WebStorm 2022.1.2

```
   const xTable = ref({} as VxeTableInstance)
```

奇怪的是这里无法启动

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/26062252/172338313-625adf49-7fa2-4908-a1ee-20e7fa73d016.png">

### 操作系统：

mac

### 浏览器版本：

版本 102.0.5005.61（正式版本） (x86_64)

### vue 版本：

3.8.4

### vxe-table 版本：

4.2.3

**Comment by dishcheng** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/26062252/172343634-b9d7ebaa-702a-4c15-8dd0-2d61675965be.png">

webstorm 这样设置...

然后这样创建ref,然后就可以了🤔
```
    const xTable: VxeTableInstance = ref({})
```

**Comment by dishcheng** [comment]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/26062252/172389589-3995f62b-5580-4f85-bf25-a025aa292a78.png">

我把代码改为这样后,可以编译了,但是有提示,操作没有什么作用,求大佬指点迷津
```
    const AlibabaBatchOrderTable = ref<VxeTableInstance>({})
```

**Comment by dishcheng** [comment]
好像是因为没有用TS环境....

**Comment by dishcheng** [comment]
Solved

**Comment by THEO-1126** [comment]
> Solved

怎么解决的呀？😭
