### ISSUE TITLE
使用vxegrid开启数据代理后，关闭分页 loaddata 报错

### ISSUE THREAD

**Issue by i7eo** [x-extends/vxe-table#1755]
### 可复现的链接：

详情见描述

### 问题描述与截图：

使用 vxegrid，开启数据代理，配置如下：
```javascript
// ...
 proxyConfig: {
    result: 'data.result',
    total: 'data.total'
}
// ...
```
此时关闭分页:
`pagerConfig={{ enabled: false }}`

报错如下：
![截屏2022-06-14 10 54 02](https://user-images.githubusercontent.com/18899748/173483733-6081ffa3-05f5-4600-a416-ec80b1009cb4.png)
![1655175369437](https://user-images.githubusercontent.com/18899748/173483913-f7a3030f-b9b8-4905-8021-2705f47c4488.jpg)
这里直接调用了 slice 而没有判断数据类型，一般开启proxy后返回的都是对象

### 操作系统：

macos monterey

### 浏览器版本：

101.0.4951.64 (arm)

### vue 版本：

3.2.21

### vxe-table 版本：

4.2.6

**Comment by 0x1f57** [comment]
该问题在vxe-table的v3版本中依然存在，望修复
