### ISSUE TITLE
按需加载表格show-overflow不能显示提示

### ISSUE THREAD

**Issue by yanghejing** [x-extends/vxe-table#1865]
### 可复现的链接：

https://h4c67m.csb.app/

### 问题描述与截图：

![18d510dd9a3695b6d82c517bc21b44d](https://user-images.githubusercontent.com/24284734/191649546-f31bc87b-eba4-4468-b6c0-557d331fc84f.jpg)

### 操作系统：

window10

### 浏览器版本：

chrome 101.0.4951.54

### vue 版本：

3.2.37

### vxe-table 版本：

4.3.2

**Comment by Banana-energy** [comment]
没有引入tooltip肯定不能显示
![image](https://user-images.githubusercontent.com/49467518/192734004-87217ef3-9bf0-4444-bb6c-65ae930e63fd.png)
