### ISSUE TITLE
VXE-Table v3.6.5 tree-config 设置启用 transform: true  时 页面无数据渲染

### ISSUE THREAD

**Issue by mili-wang** [x-extends/vxe-table#1883]
### 可复现的链接：

直接拿官方示例 无数据展示 。表格显示  暂无数据

### 问题描述与截图：

VXE-Table v3.6.5 tree-config 设置启用 transform: true  时 页面无数据渲染

目前只能使用children  树结构不支持虚拟滚动

### 期望的结果：

能够正常渲染数据 （树结构）

### 操作系统：

windows 10

### 浏览器版本：

版本 91.0.4472.164（正式版本） （64 位）

### vue 版本：

2.6.10

### vxe-table 版本：

3.6.5

**Comment by mili-wang** [comment]
问题不存在

**Comment by qingyanmaodai** [comment]
请问你是怎么解决的，我也是是这种问题
