### ISSUE TITLE
分组表头是否支持虚拟滚动

### ISSUE THREAD

**Issue by wangxdmm** [x-extends/vxe-table#1891]
### 这个需求解决了什么问题：

分类不多，但是子类非常多，做成分组表头，但是目前不支持分组表头横向虚拟滚动，希望可以支持。

### 是否已有其他不错的替代方案：

react 社区好像有这样的 [表格](https://ali-react-table.js.org/examples/others/simple-pivot-table/)

**Comment by xlz26296** [comment]
https://vxetable.cn/#/table/scroll/group
