### ISSUE TITLE
希望增加 Loading 插槽，可以自定义 Loading 状态下的显示内容

### ISSUE THREAD

**Issue by BoBo-Git** [x-extends/vxe-table#1898]
### 这个需求解决了什么问题：

可以自定义 Loding 状态下的展示内容，类似 Empty 空状态一样。

### 建议的 API 是什么样的：

```html
<vxe-table loading>
  <template #loading>
     <!-- 自定义的 Loading 元素 -->
  </template>
</vxe-table>


### 是否已有其他不错的替代方案：

_No response_

**Comment by BoBo-Git** [comment]
更新到 4.3.6 版本后好像还是没有效果。

**Comment by Lionad-Morotar** [comment]
看文档要的话这个功能要 4.3.7 才有，但是现在最新版本是 4.3.6，估计要等一会儿了。

```bash
pnpm view vxe-tables versions
```

**Comment by BoBo-Git** [comment]
> 看文档要的话这个功能要 4.3.7 才有，但是现在最新版本是 4.3.6，估计要等一会儿了。
> 
> ![企业微信截图_16705665703477](https://user-images.githubusercontent.com/26913795/206637285-480c65a7-d6a2-4087-b38b-65d9e05e3b8d.png)
> 
> ```shell
> pnpm view vxe-tables versions
> ```

感谢回复，没注意看文档标注的支持版本。今天更新了下，发现已支持。
