### ISSUE TITLE
this.$refs.xTable.getColumns()后设置visible无效

### ISSUE THREAD

**Issue by TuT-UI** [x-extends/vxe-table#1907]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-fj4tf8?file=/src/views/Demo1.vue

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/18112565/202405993-467fe583-6874-4084-93df-f1b3830d6f60.png)

### 期望的结果：

getColumns()获取列属性修改后，使用refreshColumn()生效。

### 操作系统：

win10

### 浏览器版本：

chrome 107.0.5304.107

### vue 版本：

2.6.0

### vxe-table 版本：

3.6.5

**Comment by zouyaoji** [comment]
+1
