### ISSUE TITLE
无法修改scss变量

### ISSUE THREAD

**Issue by coderlcb** [x-extends/vxe-table#1930]
### 可复现的链接：

null

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/55039022/206855931-5ec64901-bd5d-40b1-994a-9dbca7331281.png)

经测试，自定义的变量可以在vue组件中使用，但是对vxe-table的变量修改却无效，并且@import的文件点击找不到。

### 操作系统：

win10

### 浏览器版本：

chrome

### vue 版本：

3.2

### vxe-table 版本：

3.4.0

**Comment by Mrs-suo** [comment]
怎么解决的呀，也碰见了相同的问题
