### ISSUE TITLE
show-overflow="tooltip"tooltip出现的位置不是最表格对应的上层

### ISSUE THREAD

**Issue by ye-xue** [x-extends/vxe-table#1931]
### 可复现的链接：

无

### 问题描述与截图：

当页面出现多个表格,上层表格有该设置项时,鼠标移上去tooltip显示的位置不对
![image](https://user-images.githubusercontent.com/30040613/207514029-30cb52c4-9d37-4a83-8a00-c78369594285.png)

### 期望的结果：

tooltip显示的位置在当前表格的上方

### 操作系统：

window10

### 浏览器版本：

Microsoft Edge 版本 108.0.1462.46 (正式版本) (64 位)

### vue 版本：

3.2.40

### vxe-table 版本：

4.3.5

**Comment by xlz26296** [comment]
可以修改 [z-index](https://vxetable.cn/#/table/start/global) 解决层级问题
```Javascript
VXETable.setup({
  zIndex: 3000
})
```

**Comment by ye-xue** [comment]
> 

这个值怎么确定呢?我设置成3000确实解决了.但是为什么呢?

**Comment by adoin** [comment]
> > 
> 
> 这个值怎么确定呢?我设置成3000确实解决了.但是为什么呢?

因为绝对定位才能动态在不同位置展现，而 这时候脱离了文档层，他的z轴就是相对于relative那层（一般是body）的咯然后模态框和遮罩一般会比这个relative的高

**Comment by adoin** [comment]
> > 
> 
> 这个值怎么确定呢?我设置成3000确实解决了.但是为什么呢?

因为绝对定位才能动态在不同位置展现，而 这时候脱离了文档层，他的z轴就是相对于relative那层（一般是body）的咯然后模态框和遮罩一般会比这个relative的高

**Comment by ye-xue** [comment]
> > > 
> > 
> > 
> > 这个值怎么确定呢?我设置成3000确实解决了.但是为什么呢?
> 
> 因为绝对定位才能动态在不同位置展现，而 这时候脱离了文档层，他的z轴就是相对于relative那层（一般是body）的咯然后模态框和遮罩一般会比这个relative的高

非常感谢解答
