### ISSUE TITLE
vxe-grid下使用expand无法展开内容

### ISSUE THREAD

**Issue by metoogo** [x-extends/vxe-table#1932]
### 可复现的链接：

https://jsrun.net/hP7Kp/edit

### 问题描述与截图：

在vxe-table下，expand可以通过content的slot写出自定义的展开模板。
但是在vxe-gird下，没有content的slot，设计expand后无法展开内容。

### 期望的结果：

修复

### 操作系统：

windows10

### 浏览器版本：

Microsoft Edge 版本 108.0.1462.46 (正式版本) (64 位)

### vue 版本：

2.6.0

### vxe-table 版本：

3.6.9

**Comment by metoogo** [comment]
不好意思，文档没看细，自己解决了

**Comment by lazyggm** [comment]
@metoogo 怎么解决的能告诉一下么，找了好久文档没找到如何解决
