### ISSUE TITLE
form 组件 form-item key 希望可以改为 item.field

### ISSUE THREAD

**Issue by xiaogaofudao** [x-extends/vxe-table#1956]
### 这个需求解决了什么问题：

![微信截图_20230213150500](https://user-images.githubusercontent.com/9261849/218399144-64d98057-16fc-4898-8132-4ffed97b1d95.png)
form 组件 form-item key 希望可以改为 item.field。3.5.0 版本之前的key 为 数组下标 index。之后的版本包括4.x 改为了 item.id。
每次动态修改 formConfig 的数据，会导致 form-item 的 key item.id 变化引起 form-item 组件销毁重新渲染，产生不必要性能浪费，建议改为 key: item.field 来确保唯一，优化此问题

**Comment by xlz26296** [comment]
field 是非必填的，不一定有值

**Comment by xiaogaofudao** [comment]
感觉可以加上兼容，item.field || item.id 如果用户设置了 field 就使用，没有走 item.id 逻辑。一般没有field 的都是最后的按钮之类的，不影响

**Comment by xiaogaofudao** [comment]
如果用户使用自定义渲染器实现的 控件，比如级联场景，会更改其他form-item 的下拉选项，就会频繁造成组件重复渲染，多次触发 created，造成不必要浪费，如果itemRender 使用的其他三方控件，这个重复渲染问题不明显，不容易发现，建议大佬有时间优化下啊

**Comment by xiaogaofudao** [comment]
最新版本已修复此问题。非常感谢

**Comment by senningsoft** [comment]
gridOptions.formConfig.items里面的field不支持深层次绑定吗？如下
data:{ 
  stockCheck: {
          devInfo: {
            title: "",
          },
        },
},
items: [
      {
        field: "stockCheck.devInfo.title",
        title: "设备名称",
        itemRender: { name: "VxeInput" },
      },
]
@xiaogaofudao @xuliangzhan
