### ISSUE TITLE
滚动卡

### ISSUE THREAD

**Issue by joseph-lv** [x-extends/vxe-table#1976]
### 可复现的链接：

.

### 问题描述与截图：

700多行数据，设置了合并行，滚动卡顿。不设置merge-cells的话，就正常滚动

### 期望的结果：

解决方法

### 操作系统：

win10

### 浏览器版本：

chrome 100

### vue 版本：

3.0

### vxe-table 版本：

4.3

**Comment by zhuminghuan** [comment]
请问解决了吗？ 数据一多设置了合并行就很卡，虚拟列表也不起了作用

**Comment by joseph-lv** [comment]
> 请问解决了吗？ 数据一多设置了合并行就很卡，虚拟列表也不起了作用

有点忘了，好像我们数据不多，就没管了
