### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by yuntao1997** [x-extends/vxe-table#2011]
### 可复现的链接：

无

### 问题描述与截图：

我用 codesandbox 试了一下，没报错，所以没链接

代码如下：
```vue
<el-popover placement="right" width="400" trigger="click">
      <vxe-table border :data="tableData">
        <vxe-column type="checkbox" width="60"></vxe-column>
        <vxe-column field="name" title="Name"></vxe-column>
        <vxe-column field="sex" title="Sex"></vxe-column>
        <vxe-column field="date" title="Date"></vxe-column>
        <vxe-column field="address" title="Address"></vxe-column>
      </vxe-table>
      <el-button slot="reference">click 激活</el-button>
</el-popover>
```

```vue
<el-tabs v-model="activeName">
      <el-tab-pane label="用户管理" name="first">
        <vxe-table border auto-resize :data="tableData">
          <vxe-column type="checkbox" width="60"></vxe-column>
          <vxe-column field="name" title="Name"></vxe-column>
          <vxe-column field="sex" title="Sex"></vxe-column>
          <vxe-column field="date" title="Date"></vxe-column>
          <vxe-column field="address" title="Address"></vxe-column>
        </vxe-table>
      </el-tab-pane>
      <el-tab-pane label="配置管理" name="second">
        <vxe-table border auto-resize :data="tableData">
          <vxe-column type="checkbox" width="60"></vxe-column>
          <vxe-column field="name" title="Name"></vxe-column>
          <vxe-column field="sex" title="Sex"></vxe-column>
          <vxe-column field="date" title="Date"></vxe-column>
        </vxe-table>
      </el-tab-pane>
```

将vxe-table放在el-popover、el-tabs 这类组件时就会报错

删除 vxe-table 部分就不会报错，所以能确定是 vxe-table 引起的

ResizeObserver loop limit exceeded
    at eval (webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.13.1_debug@4.3.4+webpack@5.76.3/node_modules/webpack-dev-server/client/overlay.js:296:58)

### 操作系统：

windows

### 浏览器版本：

chrome 111

### vue 版本：

2.6.0

### vxe-table 版本：

3.6.12

**Comment by yuntao1997** [comment]
经过测试，将 **auto-resize**  设为false，即可解决。但是在文档中， auto-resize 默认为false

再看了一下源码  **vxe-table\packages\v-x-e-table\src\conf.js**      auto-resize 属性默认为true 

全局配置
```js
Vue.use(VXETable, {
    size: 'small',
    table: {
        autoResize: false,
        resizeConfig: {
            refreshDelay: 1000              # 设置了这个 auto-resize=true 依然会报错，不知道有啥用。。 
        },
    },
})

```


但是当auto-resize属性为false时，会导致渲染异常，希望作者能解决一下

![微信截图_20230412153257](https://user-images.githubusercontent.com/24284389/231406592-e4193a0c-883c-4e8a-b870-471164cf3f6e.png)

**Comment by Yuwenjun1997** [comment]
解决了吗

**Comment by yuntao1997** [comment]
上面写了解决办法呀

**Comment by lzw540623371** [comment]
用sync-resize就行
`:sync-resize="activeName"`

**Comment by yuntao1997** [comment]
> 用sync-resize就行 `:sync-resize="activeName"`

用这个属性能解决我下面这个问题吗，我试了一下，不行诶。。 

![微信截图_20230412153257](https://user-images.githubusercontent.com/24284389/231406592-e4193a0c-883c-4e8a-b870-471164cf3f6e.png)

**Comment by lzw540623371** [comment]
我这用这个属性不会报错了 你把autoResize的配置去掉试试

**Comment by yuntao1997** [comment]
> 我这用这个属性不会报错了 你把autoResize的配置去掉试试

auto-resize 要显式设为false，  vxe的源码里默认是true。   这个报错我知道咋解决，上面也写了。  不过又衍生出新的问题。

**Comment by lzw540623371** [comment]
你后面的问题是设置autoResize引起的,你把他去掉 用`sync-resize`解决不就行了吗

**Comment by yuntao1997** [comment]
噢噢， 确实可以，刚刚 v-model="activeName" 放错地方了，感谢
