### ISSUE TITLE
虚拟滚动,数据量达到几千条,滚动鼠标滚轮或拖拽滚动条表格白屏,用老版本的谷歌浏览器不白屏,内核100以内的好像都可以,新版本的都白屏

### ISSUE THREAD

**Issue by lingyih** [x-extends/vxe-table#2053]
### 可复现的链接：

https://vxetable.cn/v4/#/table/scroll/fullCols

### 问题描述与截图：

虚拟滚动,数据量达到千条,滚动鼠标滚轮或拖拽滚动条表格白屏。用老版本的谷歌浏览器不白屏,内核100以内的好像都可以,
![](https://files.catbox.moe/50c74r.jpg)

### 期望的结果：

希望尽快修复.

### 操作系统：

window 7  window10

### 浏览器版本：

chrome 109.0.5414.120

### vue 版本：

3.2.37

### vxe-table 版本：

4.3.14

**Comment by lingyih** [comment]
内核100以内的好像都可以,我试了86, 98都可以, 最新版本的浏览器就会白屏.

**Comment by MSK0379** [comment]
![image](https://github.com/x-extends/vxe-table/assets/22637327/d615fd81-2741-4535-afcb-d7878898ecd5)
虚拟滚动有固定列的时候，拖动滚动条特别明显，右侧的固定列内容直接就看不到了。

这个问题可以修复么 ?

**Comment by MSK0379** [comment]
> ![image](https://user-images.githubusercontent.com/22637327/241899425-d615fd81-2741-4535-afcb-d7878898ecd5.png) 虚拟滚动有固定列的时候，拖动滚动条特别明显，右侧的固定列内容直接就看不到了。
> 
> 这个问题可以修复么 ?

这个在edge 上就不会出现emm 这是什么 情况哇

**Comment by qq1031824970** [comment]
有没有老哥有解决方法？这个的确听影响体验，滚动快了或者拉滚动条就白屏

**Comment by sanxin-lin** [comment]
我走弯路解决了

**Comment by HongxuanG** [comment]
> 我走弯路解决了

老哥怎么解决的

**Comment by xuliangzhan** [comment]
#2740
