### ISSUE TITLE
vxe-table 4.4.0最新版,引入vxe-table-plugin-antd 报错,项目无法启动.老版本引入无问题.

### ISSUE THREAD

**Issue by lingyih** [x-extends/vxe-table#2065]
### 可复现的链接：

无

### 问题描述与截图：

不引入vxe-table-plugin-antd项目可以正常运行,引入就会报如下错误
代码
![](https://files.catbox.moe/2yq0c6.png)
报错信息
![](https://files.catbox.moe/1sv5cm.jpg)
![](https://files.catbox.moe/vc3xmx.png)
### 期望的结果：

希望尽快修复.

### 操作系统：

window 10

### 浏览器版本：

chrome 109.0.5414.120

### vue 版本：

3.2.37

### vxe-table 版本：

4.4.0

**Comment by adoin** [comment]
类型错误，你要想启动可以把script里面的类型检测 vue-tsc那段删了，但是问题是作者的类型是错的。。。

**Comment by adoin** [comment]
作者你类型出现递归了吗？
vue-tsc爆炸，我没引入antd插件，但是还是一样的问题。

**Comment by adoin** [comment]
复现链接： https://codesandbox.io/p/sandbox/reproduce-vue-tsc-ignore-not-working-luyz63?file=%2Fpackage.json%3A12%2C33

**Comment by adoin** [comment]
不用插件直接手写的 复现链接： https://codesandbox.io/p/sandbox/vue-tsc-antdv-crash-reporduce-p8yxsy?file=%2Fsrc%2Fmain.ts%3A11%2C17

**Comment by adoin** [comment]
> 不用插件直接手写的 复现链接： https://codesandbox.io/p/sandbox/vue-tsc-antdv-crash-reporduce-p8yxsy?file=%2Fsrc%2Fmain.ts%3A11%2C17

这个依然是错的。。。
@xuliangzhan

**Comment by adoin** [comment]
> 复现链接： https://codesandbox.io/p/sandbox/reproduce-vue-tsc-ignore-not-working-luyz63?file=%2Fpackage.json%3A12%2C33

还是坏的。。。版本不是4.4.2吗？

**Comment by lingyih** [comment]
好像还是没解决,而且引入4.4.6类型校验报的错更多了,添加自定义渲染器也开始报错了,只能暂时忽略plugins文件夹的类型校验了.

**Comment by YueCHEN195** [comment]
请问解决了吗？怎么解决的？目前最新的4.5.9运行vue-tsc依然报错

**Comment by YueCHEN195** [comment]
> > 复现链接： https://codesandbox.io/p/sandbox/reproduce-vue-tsc-ignore-not-working-luyz63?file=%2Fpackage.json%3A12%2C33
> 
> 还是坏的。。。版本不是4.4.2吗？

请问解决了吗？怎么解决的？目前最新的4.5.9运行vue-tsc依然报错
