### ISSUE TITLE
为什么vxe-cell--label空值时包裹的是一个‘ ’这样的占位 

### ISSUE THREAD

**Issue by lllianreg** [x-extends/vxe-table#2112]
### 可复现的链接：

none

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/21689406/5c0a4fbe-25d4-4477-8957-ac025663af71)
我觉得是不合理的  这样的话 css:empty 都用不了  必须slot:default 但是又多了个层级

### 期望的结果：

希望是没有占位的情况

### 操作系统：

win10

### 浏览器版本：

108

### vue 版本：

3.2

### vxe-table 版本：

4

**Comment by xlz26296** [comment]
可以修改配置
```
VXETable.setup({
  emptyCell: ''
})
```
