### ISSUE TITLE
树形表格 expand-config="{ reserve: true } ，刷新数据后， 列表没有保持展开

### ISSUE THREAD

**Issue by zjh0667** [x-extends/vxe-table#2120]
### 可复现的链接：

https://codesandbox.io/embed/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-wnsznk?fontsize=14&hidenavigation=1&theme=dark

### 问题描述与截图：

树形表格

设置了
: expand-config="{ reserve: true } ，
:row-config="{ keyField: 'id' }

刷新数据后， 列表没有保持展开

### 期望的结果：

保持展开的状态

### 操作系统：

 Mac

### 浏览器版本：

chrome  114.0.5735.198

### vue 版本：

2.6.10

### vxe-table 版本：

3.6.13

**Comment by xlz26296** [comment]
`expand-config.reserve` 是展开行并不是树节点，树节点应该使用 [`tree-config.reserve`](https://vxetable.cn/#/table/api?q=tree-config)

**Comment by zjh0667** [comment]
噢，大意了呀
