### ISSUE TITLE
组件行内编辑存在2个现象:1.官网手工例子中编辑后取消时，值没有回滚 2.编辑值后，点击其他地方，保存 取消消失，值保留了下来

### ISSUE THREAD

**Issue by z954134** [x-extends/vxe-table#2126]
### 可复现的链接：

官网的例子https://vxetable.cn/#/table/grid/edit

### 问题描述与截图：

组件行内编辑存在2个现象:1.官网手工例子中编辑后取消时，值没有回滚 2.编辑值后，点击其他地方，保存 取消消失，值保留了下来

### 操作系统：

win10

### 浏览器版本：

edge

### vue 版本：

3.x

### vxe-table 版本：

4.4.2

**Comment by lhbDesign** [comment]
您好，这个bug没有解决吖， 为什么这个 issue 关闭了呢

**Comment by HWTsang** [comment]
同问, 这个还没解决
