### ISSUE TITLE
在树形结构下设置 checkboxConfig.range = true，以及虚拟滚动，不能够正常勾选子节点

### ISSUE THREAD

**Issue by mark0176** [x-extends/vxe-table#2134]
### 可复现的链接：

https://slfgdq.csb.app/

### 问题描述与截图：

问题描述
	vue3过程中，vxe-table升级到了4.4.1版本，在树形结构下设置 checkboxConfig.range = true，以及虚拟滚动，
鼠标拖动框选子节点，会选中子节点在当前层级的位置，所对应的整颗树的数据。（例如：子节点在当前层级顺序为0，
框选会选中当前树的第一条数据，而不是勾选当前框选的子节点。）而在vxe-table 3.4.12上不存在这个问题，想请问下
	
	1、控制态一直报错。树结构不支持 "checkbox-config.range"，是否4.x在树形结构上完全不支持 checkboxConfig.range = true？
	2、查看了vxe-table 4.x版本和3.x版本对 checkboxConfig.range 的实现发现问题在 getVTRowIndex的实现方式上
3.x版本	getVTRowIndex是根据 row 获取相对于当前所有数据中的索引，而在4.x版本上的getVTRowIndex 获取的是 row 
相对于当前层级的数据中的索引。是否可在 getCheckboxRangeRows 中对树形结构进行兼容一下？

### 期望的结果：

在树形结构下设置 checkboxConfig.range = true，以及虚拟滚动，能够正常框选节点

### 操作系统：

window10

### 浏览器版本：

chrome 114

### vue 版本：

3.2.23

### vxe-table 版本：

4.4.1

**Comment by xuliangzhan** [comment]
不管v3还是v4树结构都是不支持checkbox-config.range的，不建议这样用，目前不支持
