### ISSUE TITLE
最新的beta 版本 Formatter加了cellFormatMethod，但是文档没有说明怎么对应修改，生产环境报错

### ISSUE THREAD

**Issue by adoin** [x-extends/vxe-table#2137]
### 可复现的链接：

略，只有生产环境复现

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/20517172/e9ddb2e6-dad1-4e6a-a13d-6b8c81fadcbf)

### 期望的结果：

增加cellFormatMethod的话 对应的格式化文档也更新下，虽然不知道为啥这么改

### 操作系统：

win10

### 浏览器版本：

chrome101

### vue 版本：

3.3

### vxe-table 版本：

4.5.0-beta.19

**Comment by xuliangzhan** [comment]
最新版已修复

**Comment by adoin** [comment]
beta.20的文档对了！这里既然有cellFormatMethod 是否后续有别的扩展呢？
