### ISSUE TITLE
平铺表格设置了，checkBoxConfig.range后数据量较大的情况下鼠标拖动选中卡顿，setCheckboxRow选中数据也卡顿

### ISSUE THREAD

**Issue by mark0176** [x-extends/vxe-table#2139]
### 可复现的链接：

https://slfgdq.csb.app/

### 问题描述与截图：

平铺表格设置了，checkBoxConfig.range = true后数据量较大的情况下鼠标拖动选中卡顿,
大致是因为在鼠标拖动事件的时候调用了三次 getCheckboxRecords方法，且该方法中调用的 xeUtils.filterTree耗时过大

### 期望的结果：

设置 checkboxConfig.range = true，框选节点不卡顿

### 操作系统：

window10

### 浏览器版本：

chrome 114

### vue 版本：

3.2.23

### vxe-table 版本：

4.4.1

**Comment by mark0176** [comment]
setCheckboxRow选中数据也卡顿

**Comment by mark0176** [comment]
添加checkField可解决

**Comment by jipengju-GitHub** [comment]
你好，请问vue2.6， v3版本没找到 checkField 这个配置项， 是没有吗
![image](https://github.com/x-extends/vxe-table/assets/47650295/1dbc48f2-e50e-4fee-9137-b1e9586503a4)
@mark0176
