### ISSUE TITLE
3.7.0-beta.15虚拟滚动失效了

### ISSUE THREAD

**Issue by zqy233** [x-extends/vxe-table#2157]
### 可复现的链接：

拉取v3分支代码

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/57588553/49dc7026-ba53-46a4-8195-ff96419fe11a)
检查元素发现虚拟滚动失效了，500个元素全部渲染了
往前回退到3.6.16版本的commit记录，就正常了，只渲染十个左右元素

### 期望的结果：

只渲染可视区域内的，只渲染十个左右元素

### 操作系统：

window10

### 浏览器版本：

chrome最新版

### vue 版本：

2+

### vxe-table 版本：

v3分支最新

**Comment by xuliangzhan** [comment]
v3.7开启默认不启用虚拟滚动，可以通过全局设置默认启用 [setup](https://vxetable.cn/v3/#/table/start/global)
