### ISSUE TITLE
grid.js 报错  Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by eivmosn** [x-extends/vxe-table#2162]
### 可复现的链接：

暂无

### 问题描述与截图：

这里可以判断一下 el.parentNode 是否是 HTML 节点

### 操作系统：

macOS Monterey 12.4

### 浏览器版本：

Version 102.0.5005.61 (Official Build) (arm64)

### vue 版本：

3.3.4

### vxe-table 版本：

4.5.6

**Comment by chandq** [comment]
我在项目中也经常遇到这个问题，导致经常页面无响应

**Comment by lixsh8** [comment]
我也遇到这个问题：vxe-table版本4.5.12
vxe-table.9e08ed8a.js:4 Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getParentHeight (vxe-table.9e08ed8a.js:4:127581)
    at Kt (vxe-table.9e08ed8a.js:4:81069)
    at Object.recalculate (vxe-table.9e08ed8a.js:4:107519)
    at vxe-table.9e08ed8a.js:4:95644

**Comment by lixsh8** [comment]
楼主的解决了吗？
