### ISSUE TITLE
能否增加黑暗主题切换，通过html或者body添加属性方式(scss太麻烦了)

### ISSUE THREAD

**Issue by zxuanhong** [x-extends/vxe-table#2171]
### 这个需求解决了什么问题：

现在很多ui框架都有黑暗模式，能否增加黑暗模式切换功能

### 建议的 API 是什么样的：

1. 通过传一个theme变量或者添加html或body属性方式比如html上添加theme="dark"等

### 是否已有其他不错的替代方案：

1. 替换变量必须要引入scss,我只想引用css文件，不想在引入scss的东西。太麻烦了

**Comment by rex-ll** [comment]
目前最新版有css var方案，可以用css var自己制作主题，下面这个只包含基础的样式，遇到什么自己改就行

`
html.dark {
  @bg-color: #151515;
  @tooltip-bg-color: #303133;
  @text-color: #c9d1d9;
  @border-color: #4e4a4a;
  @selected-bg-color: #262626;
  @striped-bg-color: #2b2929;

  --vxe-form-background-color: @bg-color;
  --vxe-pager-background-color: @bg-color;
  --vxe-button-default-background-color: lighten(@bg-color, 15%);
  --vxe-table-header-background-color: lighten(@bg-color, 5%);
  --vxe-font-color: darken(@text-color, 12%);
  --vxe-table-header-font-color: @text-color;
  --vxe-table-footer-font-color: @text-color;
  --vxe-table-body-background-color: @bg-color;
  --vxe-table-footer-background-color: @bg-color;
  --vxe-table-row-striped-background-color: @striped-bg-color;
  --vxe-table-border-color: @border-color;
  --vxe-table-row-hover-background-color: lighten(@bg-color, 10%);
  --vxe-table-row-hover-striped-background-color: lighten(@striped-bg-color, 10%);
  --vxe-table-row-current-background-color: fade(@primary-color-hover, 20%);
  --vxe-table-row-hover-current-background-color: fade(@primary-color-hover, 20%);
  --vxe-table-column-hover-background-color: fade(@primary-color-hover, 20%);
  --vxe-table-column-current-background-color: fade(@primary-color-hover, 20%);
  --vxe-table-row-checkbox-checked-background-color: fade(@warning-color-active, 15%);
  --vxe-table-row-hover-checkbox-checked-background-color: fade(@warning-color-active, 20%);
  --vxe-table-menu-background-color: lighten(@tooltip-bg-color, 10%);
  --vxe-table-filter-panel-background-color: lighten(@bg-color, 5%);
  --vxe-grid-maximize-background-color: @bg-color;
  --vxe-pager-perfect-background-color: @bg-color;
  --vxe-pager-perfect-button-background-color: lighten(@bg-color, 15%);
  --vxe-input-background-color: @bg-color;
  --vxe-input-border-color: @border-color;
  --vxe-select-panel-background-color: @bg-color;
  --vxe-table-popup-border-color: @border-color;
  --vxe-select-option-hover-background-color: lighten(@selected-bg-color, 15%);
  --vxe-pulldown-panel-background-color: @bg-color;
  --vxe-table-fixed-left-scrolling-box-shadow: 8px 0px 10px -5px rgba(255, 255, 255, 0.12);
  --vxe-table-fixed-right-scrolling-box-shadow: -8px 0px 10px -5px rgba(255, 255, 255, 0.12);
  --vxe-loading-background-color: rgba(0, 0, 0, 0.5);
  --vxe-tooltip-dark-background-color: lighten(@tooltip-bg-color, 25%);
  --vxe-modal-header-background-color: @selected-bg-color;
  --vxe-modal-body-background-color: @tooltip-bg-color;
  --vxe-modal-border-color: @border-color;
  --vxe-toolbar-panel-background-color: @bg-color;
  --vxe-input-disabled-color: lighten(@striped-bg-color, 20%);
  --vxe-input-disabled-background-color: lighten(@striped-bg-color, 25%);
  --vxe-checkbox-icon-background-color: lighten(@selected-bg-color, 15%);
  --vxe-checkbox-checked-icon-border-color: @border-color;
  --vxe-checkbox-indeterminate-icon-background-color: lighten(@selected-bg-color, 15%);
}
`

**Comment by mrmyn** [comment]
> 目前最新版有css var方案，可以用css var自己制作主题，下面这个只包含基础的样式，遇到没覆盖的自己改就行
> 
> 下面是我自己项目中的less
> 
> ```css-less
> html.dark {
>   @bg-color: #151515;
>   @tooltip-bg-color: #303133;
>   @text-color: #c9d1d9;
>   @border-color: #4e4a4a;
>   @selected-bg-color: #262626;
>   @striped-bg-color: #2b2929;
> 
>   --vxe-form-background-color: @bg-color;
>   --vxe-pager-background-color: @bg-color;
>   --vxe-button-default-background-color: lighten(@bg-color, 15%);
>   --vxe-table-header-background-color: lighten(@bg-color, 5%);
>   --vxe-font-color: darken(@text-color, 12%);
>   --vxe-table-header-font-color: @text-color;
>   --vxe-table-footer-font-color: @text-color;
>   --vxe-table-body-background-color: @bg-color;
>   --vxe-table-footer-background-color: @bg-color;
>   --vxe-table-row-striped-background-color: @striped-bg-color;
>   --vxe-table-border-color: @border-color;
>   --vxe-table-row-hover-background-color: lighten(@bg-color, 10%);
>   --vxe-table-row-hover-striped-background-color: lighten(@striped-bg-color, 10%);
>   --vxe-table-row-current-background-color: fade(@primary-color-hover, 20%);
>   --vxe-table-row-hover-current-background-color: fade(@primary-color-hover, 20%);
>   --vxe-table-column-hover-background-color: fade(@primary-color-hover, 20%);
>   --vxe-table-column-current-background-color: fade(@primary-color-hover, 20%);
>   --vxe-table-row-checkbox-checked-background-color: fade(@warning-color-active, 15%);
>   --vxe-table-row-hover-checkbox-checked-background-color: fade(@warning-color-active, 20%);
>   --vxe-table-menu-background-color: lighten(@tooltip-bg-color, 10%);
>   --vxe-table-filter-panel-background-color: lighten(@bg-color, 5%);
>   --vxe-grid-maximize-background-color: @bg-color;
>   --vxe-pager-perfect-background-color: @bg-color;
>   --vxe-pager-perfect-button-background-color: lighten(@bg-color, 15%);
>   --vxe-input-background-color: @bg-color;
>   --vxe-input-border-color: @border-color;
>   --vxe-select-panel-background-color: @bg-color;
>   --vxe-table-popup-border-color: @border-color;
>   --vxe-select-option-hover-background-color: lighten(@selected-bg-color, 15%);
>   --vxe-pulldown-panel-background-color: @bg-color;
>   --vxe-table-fixed-left-scrolling-box-shadow: 8px 0px 10px -5px rgba(255, 255, 255, 0.12);
>   --vxe-table-fixed-right-scrolling-box-shadow: -8px 0px 10px -5px rgba(255, 255, 255, 0.12);
>   --vxe-loading-background-color: rgba(0, 0, 0, 0.5);
>   --vxe-tooltip-dark-background-color: lighten(@tooltip-bg-color, 25%);
>   --vxe-modal-header-background-color: @selected-bg-color;
>   --vxe-modal-body-background-color: @tooltip-bg-color;
>   --vxe-modal-border-color: @border-color;
>   --vxe-toolbar-panel-background-color: @bg-color;
>   --vxe-input-disabled-color: lighten(@striped-bg-color, 20%);
>   --vxe-input-disabled-background-color: lighten(@striped-bg-color, 25%);
>   --vxe-checkbox-icon-background-color: lighten(@selected-bg-color, 15%);
>   --vxe-checkbox-checked-icon-border-color: @border-color;
>   --vxe-checkbox-indeterminate-icon-background-color: lighten(@selected-bg-color, 15%);
> }
> ```

请问这段代码加在哪里。。。

**Comment by lucio-c** [comment]
针对上边的样式，我做了一份css变量的，不需要引入less就可以直接使用的
```
html.dark {
    --bg-color: #151515;
    --tooltip-bg-color: #303133;
    --text-color: #c9d1d9;
    --border-color: #4e4a4a;
    --selected-bg-color: #262626;
    --striped-bg-color: #2b2929;

    --vxe-form-background-color: var(--bg-color);
    --vxe-pager-background-color: var(--bg-color);
    --vxe-button-default-background-color: color-mix(var(--bg-color), 15%);
    --vxe-table-header-background-color: color-mix(var(--bg-color), 5%);
    --vxe-font-color: color-mix(var(--text-color), -12%);
    --vxe-table-header-font-color: var(--text-color);
    --vxe-table-footer-font-color: var(--text-color);
    --vxe-table-body-background-color: var(--bg-color);
    --vxe-table-footer-background-color: var(--bg-color);
    --vxe-table-row-striped-background-color: var(--striped-bg-color);
    --vxe-table-border-color: var(--border-color);
    --vxe-table-row-hover-background-color: color-mix(var(--bg-color), 10%);
    --vxe-table-row-hover-striped-background-color: color-mix(var(--striped-bg-color), 10%);
    --vxe-table-row-current-background-color: fade(@primary-color-hover, 20%);
    --vxe-table-row-hover-current-background-color: fade(@primary-color-hover, 20%);
    --vxe-table-column-hover-background-color: fade(@primary-color-hover, 20%);
    --vxe-table-column-current-background-color: fade(@primary-color-hover, 20%);
    --vxe-table-row-checkbox-checked-background-color: fade(@warning-color-active, 15%);
    --vxe-table-row-hover-checkbox-checked-background-color: fade(@warning-color-active, 20%);
    --vxe-table-menu-background-color: color-mix(var(--tooltip-bg-color), 10%);
    --vxe-table-filter-panel-background-color: color-mix(var(--bg-color), 5%);
    --vxe-grid-maximize-background-color: var(--bg-color);
    --vxe-pager-perfect-background-color: var(--bg-color);
    --vxe-pager-perfect-button-background-color: color-mix(var(--bg-color), 15%);
    --vxe-input-background-color: var(--bg-color);
    --vxe-input-border-color: var(--border-color);
    --vxe-select-panel-background-color: var(--bg-color);
    --vxe-table-popup-border-color: var(--border-color);
    --vxe-select-option-hover-background-color: color-mix(var(--selected-bg-color), 15%);
    --vxe-pulldown-panel-background-color: var(--bg-color);
    --vxe-table-fixed-left-scrolling-box-shadow: 8px 0px 10px -5px rgba(255, 255, 255, 0.12);
    --vxe-table-fixed-right-scrolling-box-shadow: -8px 0px 10px -5px rgba(255, 255, 255, 0.12);
    --vxe-loading-background-color: rgba(0, 0, 0, 0.5);
    --vxe-tooltip-dark-background-color: color-mix(var(--tooltip-bg-color), 25%);
    --vxe-modal-header-background-color: var(--selected-bg-color);
    --vxe-modal-body-background-color: var(--tooltip-bg-color);
    --vxe-modal-border-color: var(--border-color);
    --vxe-toolbar-panel-background-color: var(--bg-color);
    --vxe-toolbar-background-color: var(--bg-color);
    --vxe-input-disabled-color: color-mix(var(--striped-bg-color), 20%);
    --vxe-input-disabled-background-color: color-mix(var(--striped-bg-color), 25%);
    --vxe-checkbox-icon-background-color: color-mix(var(--selected-bg-color), 15%);
    --vxe-checkbox-checked-icon-border-color: var(--border-color);
    --vxe-checkbox-indeterminate-icon-background-color: color-mix(var(--selected-bg-color), 15%);
}
```
感谢 @rex-ll

**Comment by zl7261** [comment]
import VxeUI from '@vxe-ui/core'  

VxeUI.setTheme(isDark?'dark':  'light')
