### ISSUE TITLE
当前环境不支持访问，建议更换浏览器试试！

### ISSUE THREAD

**Issue by transtone** [x-extends/vxe-table#2174]
### 可复现的链接：

https://vxetable.cn/

### 问题描述与截图：

当前环境不支持访问，建议更换浏览器试试！

### 操作系统：

windows 11

### 浏览器版本：

Microsoft Edge 版本 116.0.1938.69 (正式版本) (64 位)

### vue 版本：

x.x.x

### vxe-table 版本：

x.x.x

**Comment by zcvvvbb** [comment]
可能是adblock的原因，我关掉adblock就好了

**Comment by zzw105** [comment]
> 可能是adblock的原因，我关掉adblock就好了

感谢，确实是这个原因，关掉就好了，不过这个广告是这两天才加的？

**Comment by summer1874** [comment]
无痕模式都不行

**Comment by coderedeng** [comment]
uBlock Origin和无痕模式都打不开

**Comment by Sun79** [comment]
官网加了去广告检测
```js
function e(e) {
  e &&
    e.textContent !== o &&
    (e.innerHTML =
      '<h1 style="text-align: center;width: 100%;padding: 2em;">' +
      o +
      '</h1>')
}
function t() {
  var o = document.querySelector('.pagead-right'),
    r = document.querySelector('.page-container'),
    c = document.querySelector('.pagead-right .wwads-cn'),
    a = document.querySelector('.pagead-right .wwads-img')
  o || e(r),
    c || e(r),
    a || e(r),
    c && a ? clearTimeout(n) : ((E += 200), (n = setTimeout(t, E)))
}
```

**Comment by hzhoup** [comment]
😰😰😰

**Comment by zhangjun620** [comment]
没装拦截广告的，本来开的局部代理，后来用全局代理可以访问

**Comment by starxg** [comment]
我怎么都没想到，访问一个 cn 域名还需要开全局代理

**Comment by AtWhuhu** [comment]
光白名单都不行，还得把代理的广告屏蔽去了，写个[油猴]反一下检测

**Comment by xlz26296** [comment]
#2234

**Comment by kiccer** [comment]
公司网络控制的很严格，只给了必须的几个网址白名单，其他一律无法访问，像这种广告地址肯定批不下来的，在公司里完全没法看文档。

**Comment by xlz26296** [comment]
> 公司网络控制的很严格，只给了必须的几个网址白名单，其他一律无法访问，像这种广告地址肯定批不下来的，在公司里完全没法看文档。

也并不是完全不允许访问，官网只是会在特定时间段会检查是否屏蔽广告，绝大部分时间都是可以访问官网的
