### ISSUE TITLE
官方文档：https://vxetable.cn/v3/当前环境不支持访问，建议更换浏览器试试！

### ISSUE THREAD

**Issue by doujiangbaozi** [x-extends/vxe-table#2190]
### 可复现的链接：

https://vxetable.cn/v3/#/table/tree/lazy

### 问题描述与截图：

：https://vxetable.cn/v3/
当前环境不支持访问，建议更换浏览器试试！

### 期望的结果：

期望能够尽快解决

### 操作系统：

Linux Deepin 20.9

### 浏览器版本：

Chrome115,Firefox 117

### vue 版本：

2.6.0

### vxe-table 版本：

3.6.17

**Comment by doujiangbaozi** [comment]
看了别人的，既然adblock 的问题，提示应该是关闭adblock才对啊。

**Comment by xlz26296** [comment]
#2234
