### ISSUE TITLE
4.5.11版本设置全局参数zIndex不生效

### ISSUE THREAD

**Issue by carryidv** [x-extends/vxe-table#2195]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-whszp7

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/92970827/cedd9ad5-20e6-48ae-9d99-76000527c71b)
最新版本设置全局参数zIndex不生效
VXETable.config({
  zIndex: 1999,
})

### 操作系统：

win10

### 浏览器版本：

chrome

### vue 版本：

3.2.31

### vxe-table 版本：

v4.5.11

**Comment by xuliangzhan** [comment]
4.5+，组件库不在维护 z-index，由 [dom-zindex](https://www.npmjs.com/package/dom-zindex) 统一管理，对于其他也使用了 [dom-zindex](https://www.npmjs.com/package/dom-zindex) 的库可以无缝共享 z-index

```javascript
import domZindex from 'dom-zindex'

domZindex.setCurrent(999)
```

**Comment by wen403** [comment]
@xuliangzhan 能否共享给 element-ui ？
