### ISSUE TITLE
3.7.2版本在打包时css压缩报错

### ISSUE THREAD

**Issue by zhoufenfens** [x-extends/vxe-table#2201]
### 可复现的链接：

https://codesandbox.io/p/sandbox/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-x9xjky?file=%2Fsrc%2Fmain.js%3A12%2C17

### 问题描述与截图：

您好，请看下这个问题。升级到3.7版本后，在打包时报错，错误信息如下
<img width="588" alt="image" src="https://github.com/x-extends/vxe-table/assets/3303836/9ed304e8-e50c-43e5-ae0f-04e4d75a2fc3">
您可以点击上面的链接，运行 npm run build
<img width="608" alt="image" src="https://github.com/x-extends/vxe-table/assets/3303836/668771d4-0bf2-4cf0-9007-7329f35aa309">
因为我用的是Node14版本，所以node-saas, sass-loader都不是最新版，不确定是不是这些因素影响的。

### 期望的结果：

构建成功

### 操作系统：

macos

### 浏览器版本：

edge beta for mac 118

### vue 版本：

2.6.14

### vxe-table 版本：

3.7.2

**Comment by Nextdrive-NeilChen** [comment]
您好，
https://github.com/x-extends/vxe-table/issues/2123
我有嘗試用 v3.7.4 ， 打包出錯的問題就不發生了，您可以試試看，謝謝。

**Comment by zhoufenfens** [comment]
> 您好， #2123 我有嘗試用 v3.7.4 ， 打包出錯的問題就不發生了，您可以試試看，謝謝。

感谢。早晨重新试了一下确实恢复了。
