### ISSUE TITLE
编辑表格嵌套element plus 的el-select组件时  el-select会失效 无法v-model值 change方法也无法触发

### ISSUE THREAD

**Issue by joufulpen** [x-extends/vxe-table#2249]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-wjwzsv

### 问题描述与截图：

编辑表格嵌套element plus 的el-select组件时  el-select会失效 无法v-model值 change方法也无法触发; elelment plus 版本2.3.12

![20231115184912_rec_](https://github.com/x-extends/vxe-table/assets/38034583/3bacc469-0334-44cb-8052-34f05981cf12)

![image](https://github.com/x-extends/vxe-table/assets/38034583/720d77c4-277e-4bea-a7e6-40aabc050d9c)

### 期望的结果：

可以修改这个bug 让编辑表格嵌套el-select也可以正常使用

### 操作系统：

window11

### 浏览器版本：

Chrome 118.0.5993.70（正式版本） 

### vue 版本：

3.3.4

### vxe-table 版本：

4.5.13

**Comment by xlz26296** [comment]
要安装适配插件，文档都有说明
https://vxetable.cn/other4/#/table/other/element

**Comment by Yangxiaomei888** [comment]
但是那个插件不支持vxe-table4版本以上啊，现在用的vxe-table是4版本以上

**Comment by joufulpen** [comment]
> 要安装适配插件，文档都有说明 https://vxetable.cn/other4/#/table/other/element

谢谢 当时没找到这个文档
