### ISSUE TITLE
使用树层级结构的树形表格，无法开启虚拟滚动

### ISSUE THREAD

**Issue by LXQLab** [x-extends/vxe-table#2251]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-dsz5hq

### 问题描述与截图：

![截屏2023-11-20 09 53 39](https://github.com/x-extends/vxe-table/assets/15071470/41a37ac7-b780-461f-aac5-5d8da16664e9)

如图，点击”展开所有“后，可看到很多的tr节点被创建出来。

### 期望的结果：

期望树层级结构的树形表格，也能支持虚拟滚动

### 操作系统：

mac

### 浏览器版本：

所有浏览器

### vue 版本：

3.2.32

### vxe-table 版本：

4.5.13

**Comment by xuliangzhan** [comment]
[虚拟树](https://vxetable.cn/#/table/scroll/tree)只支持数组形式，不支持带层级的树。
如果本身是树结构，可以[将树结构拍平](https://vxetable.cn/xe-utils/#/?to=toTreeArray)后再去渲染。
```javascript

```
