### ISSUE TITLE
vxe-grid 高级表格 columns中 编辑插槽中 a-select使用bug

### ISSUE THREAD

**Issue by Jitianpeng** [x-extends/vxe-table#2304]
### 可复现的链接：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-nv5wnj?file=%2Fsrc%2Fviews%2FDemo1.vue%3A42%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrzxfeqz00063b6fs7kjsi9h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrzxfeqz00023b6fox49rx4l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrzxfeqz00033b6flktemn2b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrzxfeqz00053b6f9y67woma%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrzxfeqz00023b6fox49rx4l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrzxfeqz00013b6fttwg2za0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fassets%252Flogo.png%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrzzh2ks00023b6fz4io7nzb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A42%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A42%252C%2522endColumn%2522%253A36%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fviews%252FDemo1.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrzzk2h600023b6fa7gmw9cp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrzxfeqz00023b6fox49rx4l%2522%252C%2522activeTabId%2522%253A%2522clrzzh2ks00023b6fz4io7nzb%2522%257D%252C%2522clrzxfeqz00053b6f9y67woma%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrzxfeqz00043b6f7q0mzlba%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrzxfeqz00053b6f9y67woma%2522%252C%2522activeTabId%2522%253A%2522clrzxfeqz00043b6f7q0mzlba%2522%257D%252C%2522clrzxfeqz00033b6flktemn2b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrzxfeqz00033b6flktemn2b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/45327138/6cc5fffd-e9a0-4b36-81c3-223dcdc2fb5a)
编辑插槽返回 Vnode 点击进入编辑模式后未显示已选中项，切换选中项退出编辑模式后，数据未发生变化，若v-model改为v-model:value 直接出错，无法渲染下拉选择框,将a-select改为vxe-select后 表现正常
![image](https://github.com/x-extends/vxe-table/assets/45327138/11a3e11f-6c3c-4555-b5fc-13f305f343a3)

### 期望的结果：

编辑渲染插槽使用a-select与vxe-select效果相同

### 操作系统：

maxos sonoma 14.1.1

### 浏览器版本：

chrome 121.0.6167.85（正式版本） (x86_64)

### vue 版本：

3.231

### vxe-table 版本：

4.1.21

**Comment by Jitianpeng** [comment]
复现demo地址： https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-yrt2gz?file=%2Fsrc%2Fviews%2FDemo1.vue

**Comment by xlz26296** [comment]
集成第三方库需要安装[适配插件](https://vxetable.cn/other4/#/table/other/antd)

**Comment by BadLiar-B** [comment]
+1
change事件不生效
怎么修改
