### ISSUE TITLE
vxe-table配合vxe-input使用，每个单元格都需要双击才可以进行输入

### ISSUE THREAD

**Issue by macarthor** [x-extends/vxe-table#2309]
### 可复现的链接：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-fqfdvd?file=%2Fsrc%2Fviews%2FDemo1.vue%3A106%2C13

### 问题描述与截图：

如上边的codesanbox的demo，我给表格设置了`:edit-config="{trigger: 'click', mode: 'row'}`，但是还是需要双击单元格才能显示光标和输入

### 期望的结果：

单击单元格就可以显示光标和输入

### 操作系统：

windows 10

### 浏览器版本：

Microsoft Edge 版本 121.0.2277.98 (正式版本) (64 位)

### vue 版本：

3.3.11

### vxe-table 版本：

4.5.18

**Comment by macarthor** [comment]
感觉这个bug是这样：`vxe-input`的`type="integer"`时，点击一次会显示上下的控件，再点击一次才会显示光标和接受输入。
而当加入`:controls="false"`时，不再显示上下控件，但延续了点击两次才可以显示光标和接受输入的逻辑

**Comment by xuliangzhan** [comment]
文档有例子的，https://vxetable.cn/#/table/edit/click
需要通过 autofocus 设置聚焦的元素，就可以实现激活编辑后自动聚焦

**Comment by macarthor** [comment]
> 文档有例子的，https://vxetable.cn/#/table/edit/click 需要通过 autofocus 设置聚焦的元素，就可以实现激活编辑后自动聚焦

是的，已经解决了，感谢
