### ISSUE TITLE
「TreeTable」开启懒加载后，通过 insertNextAt 对懒加载的数据插入新行会同时插入两行(_X_ROW_KEY 相同)

### ISSUE THREAD

**Issue by Clover-You** [x-extends/vxe-table#2320]
### 可复现的链接：

https://vxe-table-bug-example.ctong.top/2320

### 问题描述与截图：

以下两个位置为写入 children 相关数据相关操作源码。在调试时发现， 173 行写入后，188 行的 child 存在 173 写入的数据，导致在 188 行重复写入！猜测 children 和 child 地址可能相同，但是奇怪的是，当第二次插入新行时一切都恢复正常!!

- [/packages/edit/src/hook.ts#L188](https://github.com/x-extends/vxe-table/blob/5619b2b9fdbf6eb860886fcaea4d12667fc71a13/packages/edit/src/hook.ts#L173)
- [/packages/edit/src/hook.ts#L173](https://github.com/x-extends/vxe-table/blob/5619b2b9fdbf6eb860886fcaea4d12667fc71a13/packages/edit/src/hook.ts#L188)

<img width="1228" alt="image" src="https://github.com/x-extends/vxe-table/assets/50982977/a5724d2e-2bbf-48e2-8ade-b81f9df32b58">

<img width="742" alt="image" src="https://github.com/x-extends/vxe-table/assets/50982977/628db6f7-379e-4a5d-a27d-f255405eb15a">

复现项目启动后访问：http://localhost:5173/two-rows-of-the-same-data-when-a-new-row-is-insertee-when-layz-enable

### 操作系统：

MacOS/Windows

### 浏览器版本：

Chrome  121.0.6167.139

### vue 版本：

^3.4.19

### vxe-table 版本：

4.5.20

**Comment by Clover-You** [comment]
https://github.com/x-extends/vxe-table/assets/50982977/f55d42c3-e527-422e-9bd8-48456da395e3

**Comment by headwww** [comment]
我也遇到一样的情况

**Comment by YUAN-C-J** [comment]
我也遇到了，开启懒加载之后，第一次插入重复插入了一条，第二次就正常了，博主现在解决了吗？困扰我好久了，收到了麻烦回复一下，或者联系我微信：helloxy0

**Comment by Clover-You** [comment]
> 我也遇到了，开启懒加载之后，第一次插入重复插入了一条，第二次就正常了，博主现在解决了吗？困扰我好久了，收到了麻烦回复一下，或者联系我微信：helloxy0

我提了个修复 PR 作者没合并。我把我修复后的版本上传到 npm 了，[vxe-table-cfc](https://www.npmjs.com/package/vxe-table-cfc)。你下载后在 vite.config 添加别名映射就好，等正式版修复后再移除 cfc 版本转到正式版。注意在使用时应该引入 vxe-table 而不是 vxe-table-cfc

```ts
// vite.config.ts

export default () => {
  return defineConfig({
    resolve: {
      alias: {
        'vxe-table': 'vxe-table-cfc',
      },
    },
  })
})
```

**Comment by YUAN-C-J** [comment]
> > 我也遇到了，开启懒加载之后，第一次插入重复插入了一条，第二次就正常了，博主现在解决了吗？困扰我好久了，收到了麻烦回复一下，或者联系我微信：helloxy0
> 
> 我提了个修复 PR 作者没合并。我把我修复后的版本上传到 npm 了，[vxe-table-cfc](https://www.npmjs.com/package/vxe-table-cfc)。你下载后在 vite.config 添加别名映射就好，等正式版修复后再移除 cfc 版本转到正式版。注意在使用时应该引入 vxe-table 而不是 vxe-table-cfc
> 
> ```ts
> // vite.config.ts
> 
> export default () => {
>   return defineConfig({
>     resolve: {
>       alias: {
>         'vxe-table': 'vxe-table-cfc',
>       },
>     },
>   })
> })
> ```

可以了，多谢多谢，对了你是直接改的源码吗，能看一下是咋改的吗？还有就是我应该用你的哪个版本呢？

**Comment by Clover-You** [comment]
> > > 我也遇到了，开启懒加载之后，第一次插入重复插入了一条，第二次就正常了，博主现在解决了吗？困扰我好久了，收到了麻烦回复一下，或者联系我微信：helloxy0
> > 
> > 
> > 我提了个修复 PR 作者没合并。我把我修复后的版本上传到 npm 了，[vxe-table-cfc](https://www.npmjs.com/package/vxe-table-cfc)。你下载后在 vite.config 添加别名映射就好，等正式版修复后再移除 cfc 版本转到正式版。注意在使用时应该引入 vxe-table 而不是 vxe-table-cfc
> > ```ts
> > // vite.config.ts
> > 
> > export default () => {
> >   return defineConfig({
> >     resolve: {
> >       alias: {
> >         'vxe-table': 'vxe-table-cfc',
> >       },
> >     },
> >   })
> > })
> > ```
> 
> 可以了，多谢多谢，对了你是直接改的源码吗，能看一下是咋改的吗？还有就是我应该用你的哪个版本呢？

#2321

**Comment by YUAN-C-J** [comment]
> > 还有就是我应该用你的哪个版本呢？
> 
> 用最新的就好

兄弟，1个小时前可以用，但是刚刚又报错了
<img width="449" alt="微信图片_20240506145849" src="https://github.com/x-extends/vxe-table/assets/31686676/394917e6-9a2e-4a9f-b4ed-4d02aec5acc6">

**Comment by Clover-You** [comment]
> > > 还有就是我应该用你的哪个版本呢？
> > 
> > 
> > 用最新的就好
> 
> 兄弟，1个小时前可以用，但是刚刚又报错了 <img alt="微信图片_20240506145849" width="449" src="https://private-user-images.githubusercontent.com/31686676/328100776-394917e6-9a2e-4a9f-b4ed-4d02aec5acc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzkwODMsIm5iZiI6MTcxNDk3ODc4MywicGF0aCI6Ii8zMTY4NjY3Ni8zMjgxMDA3NzYtMzk0OTE3ZTYtOWEyZS00YTlmLWI0ZWQtNGQwMmFlYzVhY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDdjNzhlYTM4ZGViZDhlOGM2YWJjMGU5N2Q2NmMyMDBiYzNhOWFhMjc0ZmU1YzlhZjNiZjAwMzZhYTg2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6eLUCAfKXARkEsrd8RulgKIARjDPdkOj3Zr4P2rFMpM">

![0c679c2a32ee1fc2000e1e593be3ff4d](https://github.com/x-extends/vxe-table/assets/50982977/ab998890-c5e5-420a-9f40-7d5126557d94)

**Comment by Clover-You** [comment]
#2477 修复
