### ISSUE TITLE
希望在micro-app中作为子应用使用时，能兼容table的tooltips

### ISSUE THREAD

**Issue by AaronWangCong** [x-extends/vxe-table#2326]
### 这个需求解决了什么问题：

作为子应用时，表格的tooltips会有偏移问题

### 是否已有其他不错的替代方案：

初步查看应该为window获取计算的问题。需要根据microapp的方式兼容获取真实的window。
或者暴露出tooltip的偏移量，在真实业务中自定义处理。
![image](https://github.com/x-extends/vxe-table/assets/40055730/a5060e3c-c928-4207-b5ef-5fb69ae73758)

**Comment by AaronWangCong** [comment]
![image](https://github.com/x-extends/vxe-table/assets/40055730/1f4b6e06-67e3-4a30-ae1f-b5a9a2401a55)

**Comment by AaronWangCong** [comment]
![image](https://github.com/x-extends/vxe-table/assets/40055730/42c59825-43ec-47ef-a4d3-c3ca8bdfa6c8)

**Comment by taoqiyang** [comment]
请问这个问题你的解决方案是啥，能指教下么

**Comment by makai1027** [comment]
> 请问这个问题你的解决方案是啥，能指教下么

自己写 cell-mouseenter事件，
配置对象内
tooltipConfig: {
enterDelay: 200, // 默认 500，测试之后200差不多
      enterable: true
}

const cellMouseHandler = debounce(() => {
  if (非微前端) return;
  const { left, top } = document.body.getBoundingClientRect();
  const tooltip = document.body.querySelector(
    ".vxe-table--tooltip-wrapper.is--visible"
  );
  if (!tooltip || !tooltip.style) return;
  const _l = parseInt(tooltip.style.left);
  const _t = parseInt(tooltip.style.top);
  tooltip.style.left = _l - left + "px";
  tooltip.style.top = _t - top + "px";
}, 220);

**Comment by 498755303** [comment]
这个问题现在有解决方案了么， 是不是可以tooltip增加一个prop，传入真实window

**Comment by cjb263** [comment]
```js
const $body = document.querySelector('body')!;

const initAppOffset = () => {
	const { left = 0, top = 0 } = $body.getBoundingClientRect();
	$body.style.setProperty('--app-offset-left', `${left}px`);
	$body.style.setProperty('--app-offset-top', `${top}px`);
};
```

```scss
.vxe-tooltip--wrapper {
	transform: translate(calc(-1 * var(--app-offset-left)), calc(-1 * var(--app-offset-top)));
	.vxe-tooltip--content {
		white-space: nowrap;
	}
}
```
