### ISSUE TITLE
在arco.design vue的Modal 对话框中使用show-overflow，鼠标悬浮时的黑色气泡显示层级有问题

### ISSUE THREAD

**Issue by cloud-nine-GitHub** [x-extends/vxe-table#2355]
### 可复现的链接：

无

### 问题描述与截图：

在arco.design vue的Modal 对话框中使用show-overflow，鼠标悬浮时的黑色气泡显示层级有问题
![image](https://github.com/x-extends/vxe-table/assets/92359509/5d53a83e-9a52-4441-baf3-9ba54efc1f6e)

### 操作系统：

win10

### 浏览器版本：

Microsoft Edge 版本 123.0.2420.81 (正式版本) (64 位)

### vue 版本：

3.3.7

### vxe-table 版本：

4.5.13

**Comment by lait233** [comment]
你需要全局配置一下zIndex
```js
    // vxeTable 公共配置信息
    VXETable.setup( {
        zIndex: 3000, //防止弹出层有table 无法鼠标移入有省略号字段的 tip显示完整内容
        table:{scrollX:{enabled:true},scrollY:{enabled:true, scrollToTopOnChange:true}},
    } );
```

**Comment by cloud-nine-GitHub** [comment]
好的 已经解决了 非常感谢
