### ISSUE TITLE
按需加载vxe-grid样式无效

### ISSUE THREAD

**Issue by vela666** [x-extends/vxe-table#2374]
### 可复现的链接：

https://github.com/vela666/demo

### 问题描述与截图：
使用该方式样式无效
![image](https://github.com/x-extends/vxe-table/assets/69613314/2e0c4e47-98dd-4c60-9e6d-2c013fdfb564)

![image](https://github.com/x-extends/vxe-table/assets/69613314/14d283cb-af3c-44f3-96cc-6b3cf0ea1e5d)

### 期望的结果：

正常显示

### 操作系统：

win10

### 浏览器版本：

chrome 124.0.6367.61

### vue 版本：

3.4.25

### vxe-table 版本：

4.6.6

**Comment by xlz26296** [comment]
检查一下主题变量是否导入，看一下官网下方的 [使用说明](https://vxetable.cn/#/table/start/use)  
<img width="632" alt="image" src="https://github.com/x-extends/vxe-table/assets/34787386/ddc45602-6957-41a2-8be0-b6d56ba68e70">

**Comment by vela666** [comment]
> 检查一下主题变量是否导入，看一下官网下方的 [使用说明](https://vxetable.cn/#/table/start/use) <img alt="image" width="632" src="https://private-user-images.githubusercontent.com/34787386/326343625-ddc45602-6957-41a2-8be0-b6d56ba68e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzE3OTksIm5iZiI6MTcxNDM3MTQ5OSwicGF0aCI6Ii8zNDc4NzM4Ni8zMjYzNDM2MjUtZGRjNDU2MDItNjk1Ny00MWEyLThiZTAtYjZkNTZiYTY4ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2MTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzg0YzM4ZTMzNjNlNWVmMzJlZDBjODFkZWI0ZTQwOTI5M2UwOTdkYWZhNThlMjc2YzMzNWQ1ZmY2OWY5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2g27bPb7MdIjlA82cBf2i6Gy6tuqPHQI3_snY1wKkc">

直接复制官网的示例

**Comment by xlz26296** [comment]
加上这个[试试](https://github.com/x-extends/vxecli/tree/main/import-unplugin-vue-components)
```
VxeTableResolver({
  importStyle: true
})
```

**Comment by vela666** [comment]
> 加上这个[试试](https://github.com/x-extends/vxecli/tree/main/import-unplugin-vue-components)
> 
> ```
> VxeTableResolver({
>   importStyle: true
> })
> ```

没有用。。。

**Comment by xlz26296** [comment]
我看官网的 [demo](https://github.com/xuliangzhan/vxe-table-demo/tree/master/vxe-table-by-vue3-vite-typescript-demand2) 是可以的，我跑你的看看

**Comment by xlz26296** [comment]
按需加载应该是有个问题，必须要使用过 ```<vxe-table>``` 才行

**Comment by vela666** [comment]
> 按需加载应该是有个问题，必须要使用过 `<vxe-table>` 才行

绝了哈哈

**Comment by xuliangzhan** [comment]
[unplugin-vue-component](https://github.com/unplugin/unplugin-vue-components/issues/162) 这个插件目前为主是不支持导入非 template 里引用的组件样式，如果没有在template显性使用过的话必须手动去导入对于的样式，该插件是不会自动导入的

**Comment by vela666** [comment]
> [unplugin-vue-component](https://github.com/unplugin/unplugin-vue-components/issues/162) 这个插件目前为主是不支持按需导入非 template 里引用的组件样式，如果没有在template显性使用过的话必须手动去导入对应的样式，不然该插件是不会自动导入样式的
> 
> 例如：
> 
> ```
> import 'vxe-table/es/table/style.css'
> ```

好的 明白了 谢谢

**Comment by zhangchenna** [comment]
还是需要手动注册  app.use(Menu).use(Tooltip); 才能显示菜单跟超出悬浮提示
