### ISSUE TITLE
工具栏里的自定义列拖拽排序如何在simple模式下实现

### ISSUE THREAD

**Issue by yd-coder** [x-extends/vxe-table#2377]
### 这个需求解决了什么问题：

工具栏新增的自定义列拖拽排序功能看文档目前只支持mode=popup 有效，如果想在simple模式的小窗里使用有没有简单快速的方法？

### 是否已有其他不错的替代方案：

![image](https://github.com/x-extends/vxe-table/assets/73770046/966d20a4-2c2b-4dc5-9fd0-80fb1c8c0a59)
![image](https://github.com/x-extends/vxe-table/assets/73770046/bc1cc8e0-051a-47de-a4aa-5943fdb9150f)

**Comment by tujianglin** [comment]
貌似storage 也不生效

**Comment by lecansoft** [comment]
工具栏新增的自定义列拖拽排序功能看文档目前只支持mode=popup 有效。请问你在那个文档中看见这个？我在vxe-table官方文档都没有找到这个，也没有看见相关例子。能否告知？谢谢

**Comment by yd-coder** [comment]
4.7.5+已经支持了

**Comment by Bana0** [comment]
如何在自定义列中实现列的数据排序(倒序/升序)
