### ISSUE TITLE
v3版本 getAbsolutePos方法被覆盖了，commit号：996a7427532089d7d9aa1291664cd7a4f8d48656

### ISSUE THREAD

**Issue by makai1027** [x-extends/vxe-table#2391]
### 可复现的链接：

请自行查看代码提交记录

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/24761813/faf92c8e-a582-45a9-b327-7ab1ba7a11b1)
commit号：996a7427532089d7d9aa1291664cd7a4f8d48656

计算位置时需要计算外层body的边界，你删掉了，那么在微前端中则会造成tooltip，popover之类的弹出层位置偏移

### 期望的结果：

帮忙处理一下

### 操作系统：

mac os

### 浏览器版本：

124.0.6367.158

### vue 版本：

vue 2.6

### vxe-table 版本：

3.8.6

**Comment by xuliangzhan** [comment]
该 [pr](#2244) 改动存在问题，暂时还原

**Comment by makai1027** [comment]
> 该 [pr](https://github.com/x-extends/vxe-table/pull/2244) 改动存在问题，暂时还原

好的

**Comment by makai1027** [comment]
> 该 [pr](https://github.com/x-extends/vxe-table/pull/2244) 改动存在问题，暂时还原

![image](https://github.com/x-extends/vxe-table/assets/24761813/f7a9ba58-2026-4279-af4e-fefba866a1cd)
你好 4.7.x 版本  getAbsolutePos 方法需要改一下
