### ISSUE TITLE
稳定版v4.6.17 - 数据更新但视图不更新

### ISSUE THREAD

**Issue by sweihub** [x-extends/vxe-table#2409]
### 可复现的链接：

[这里](https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-4jglj4?file=%2Fsrc%2Fviews%2FDemo1.vue%3A25%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwra5wqh0006356j18xd84zl%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwra5wqh0002356j4lu8acyi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwra5wqh0003356jtti1vunc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwra5wqh0005356j5mm65y3d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwra5wqh0002356j4lu8acyi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwra5wqh0001356jzj3jqwh4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwra7gwa0035356jcu8bgr91%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fviews%252FDemo1.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwra5wqh0002356j4lu8acyi%2522%252C%2522activeTabId%2522%253A%2522clwra7gwa0035356jcu8bgr91%2522%257D%252C%2522clwra5wqh0005356j5mm65y3d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwra5wqh0004356jlpakof18%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwra5wqh0005356j5mm65y3d%2522%252C%2522activeTabId%2522%253A%2522clwra5wqh0004356jlpakof18%2522%257D%252C%2522clwra5wqh0003356jtti1vunc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwra5wqh0003356jtti1vunc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 问题描述与截图：

使用vue3，vxe-table 不更新数据行，请问要如何解决？
```js
const data = ref([{
id: 1,
name: "Tom",
}]);

data.value[0] = {id: 1, name: "Jack"};
// vxe-table 不更新数据行

```

### 操作系统：

win11

### 浏览器版本：

124.0.6367.210

### vue 版本：

vue3

### vxe-table 版本：

4.6.17

**Comment by xlz26296** [comment]
不能直接改数组的

不支持：
```javascript
cosnt tableData = ref([])
tableData.value[0] = {xx: 11}
```

应该改成
```javascript
cosnt tableData = ref([])

tableData.value[0].xx = 11
tableData.value = [{xx: 11}]
tableData.value.push({xx: 11})
tableData.value[0].xx = 11
Object.assign(tableData.value[0], {xx: 11})
```

**Comment by sweihub** [comment]
原来是vue3数据绑定机制的问题， 已解决，谢谢！

**Comment by c-sopoo** [comment]
> 对于数组类型行数据的修改：
> 
> 不支持：
> 
> ```js
> cosnt tableData = ref([
>   { xx: 22 }
> ])
> 
> tableData.value[0] = {xx: 11}
> ```
> 
> 应该改成
> 
> ```js
> cosnt tableData = ref([
>   { xx: 22 }
> ])
> 
> tableData.value[0].xx = 11
> tableData.value = [{xx: 11}]
> tableData.value.push({xx: 11})
> tableData.value[0].xx = 11
> Object.assign(tableData.value[0], {xx: 11})
> ```

使用splice也不能更新吗，数据是变了，但视图没变，求教

**Comment by sweihub** [comment]
1. 首先在外部构造数据 data
2. 然后修改 vue ref，比如 dataRef.value = data
3. 再更新ref的属性才可以，比如 dataRef.value.abc = 100,

**Comment by sweihub** [comment]
是vue3 proxy 更新机制问题。

当赋值给vue3 ref 时候，vue3 会递归的生成新的代理对象，所以如果想同步数据到界面，需要直接修改ref 的属性。调用其它方法或者赋值一个新对象，会导致修改的数据没有被vue3 监控到。

**Comment by c-sopoo** [comment]
![image](https://github.com/user-attachments/assets/9a152c7a-e5ef-4155-ae31-2f8709c1a077)
但是文档已经表明splice是会更新的，就把我搞懵了，我上面的操作就是dada.value.splice()

**Comment by dongivan** [comment]
遇到同样的问题，从pinia获取的数据使用proxyConfig的query填入vxe table后，更新pinia中的数据，vxe table不会同步。
高度怀疑vxe table没有保持数据的响应性。
