### ISSUE TITLE
希望能添加一个api,该api返回由rou和column确定的cell元素

### ISSUE THREAD

**Issue by RanMaoting** [x-extends/vxe-table#2444]
### 这个需求解决了什么问题：

在某些情况下需要使用单元格元素进行操作,现在查找元素不好操作

### 建议的 API 是什么样的：
类似getElement(rowKey, columnName)
返回HTMLelement
_No response_

**Comment by xuliangzhan** [comment]
支持的，通过获取 [getCellElement](https://vxeui.com/#/table/api?q=getCellElement)

**Comment by RanMaoting** [comment]
谢谢,那应该是grid的文档有误,在grid中没有这个api文档
![image](https://github.com/x-extends/vxe-table/assets/62940878/5fa2cdfb-b4f7-4993-a2c5-9773b0eae387)
