### ISSUE TITLE
table.scss缺少变量编译报错

### ISSUE THREAD

**Issue by GitOfZGT** [x-extends/vxe-table#2449]
### 可复现的链接：

无

### 问题描述与截图：

vxe-table/styles/table.scss 缺少变量 $vxe-table-cell-active-area-background-color

![image](https://github.com/x-extends/vxe-table/assets/21262000/695ac89e-41e7-4cac-b41c-4edb86c440b0)

### 操作系统：

mac os

### 浏览器版本：

126.0.6478.63

### vue 版本：

2.7.16

### vxe-table 版本：

3.8.8

**Comment by xlz26296** [comment]
[variable.scss](https://github.com/x-extends/vxe-table/blob/6f433e0bc2a94ecdd786a320ee071829c1cce411/styles/variable.scss#L110)

**Comment by GitOfZGT** [comment]
我是要按需引入 vxe-table/styles/table.scss， 这个文件里面没有 @import "./variable.scss"

**Comment by GitOfZGT** [comment]
ok,  我把variable.scss提取出来再组装到一个总的.scss
