### ISSUE TITLE
组树耗时太长

### ISSUE THREAD

**Issue by liangyb-a** [x-extends/vxe-table#2453]
### 可复现的链接：

暂无

### 问题描述与截图：

vex-table 设置tree-config属性，loadData加载时，1300条数据耗时8s
![vxe-table](https://github.com/x-extends/vxe-table/assets/174005857/950495df-a2d6-4ebb-820a-c6c23cb68cf6)

### 期望的结果：

怎么减少渲染耗时

### 操作系统：

win10

### 浏览器版本：

chrome 100.0.4896.60

### vue 版本：

2.6.11

### vxe-table 版本：

3.7.4

**Comment by xlz26296** [comment]
可以看[官网](https://vxeui.com/#/component/table/scroll/tree)几千条行毫秒级
