### ISSUE TITLE
虚拟滚动不支持，浏览器Ctrl+F 查询

### ISSUE THREAD

**Issue by 729993031** [x-extends/vxe-table#2459]
### 可复现的链接：

https://vxetable.cn/#/component/table/scroll/hv

### 问题描述与截图：

通过浏览器提供的 Ctrl+F 功能进行表头搜索
![image](https://github.com/x-extends/vxe-table/assets/13050361/b1c77b4f-892f-450e-9e49-d0cfe96e5afa)
检索到了对应的关键词，但是点击下一项icon时、不能跳转到对应的位置。
![image](https://github.com/x-extends/vxe-table/assets/13050361/1c362376-1633-46d0-a1ac-d2a9f1c61378)

### 期望的结果：

搜索到结果之后，跳转到对应的位置。

### 操作系统：

win10

### 浏览器版本：

chorme

### vue 版本：

3.4

### vxe-table 版本：

4.7

**Comment by ryanryanorient** [comment]
不可能支持，浏览器的CTRL+F是查询DOM,虚拟滚动并不是全量渲染，故而搜索不到

**Comment by xlz26296** [comment]
要浏览器的功能是需要关闭虚拟滚动的。目前只有[企业版](https://vxetable.cn/pluginDocs/table/#/extendCellArea/grid/areaScroll)可以支持带虚拟滚动的搜索

**Comment by fourteendp** [comment]
你可以自定义一个

**Comment by 729993031** [comment]
@xlz26296  感觉是我们的实现方式的问题，导致浏览器不能跳转到指定的表头？
 [tanstack-table](https://tanstack.com/table/latest/docs/framework/react/examples/virtualized-rows) 是支持的，可参考下面的GIF图
![动画](https://github.com/x-extends/vxe-table/assets/13050361/15bc64a3-f13d-45df-878d-f08a828808b6)
这部分数据是表格头部的，并不会因为虚拟滚动而没有展示出来
