### ISSUE TITLE
表格组件的多选框样式丢失

### ISSUE THREAD

**Issue by aifeng12** [x-extends/vxe-table#2465]
### 可复现的链接：

https://github.com/x-extends/vxe-table/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

### 问题描述与截图：

![微信图片_20240705104838](https://github.com/x-extends/vxe-table/assets/128198472/71f10c9d-2518-4731-bb9a-b28bc8844f1f)
第一列多选框样式丢失。
全局引入
import Vue from 'vue'
import VXETable from 'vxe-table'
import 'vxe-table/lib/style.css'
Vue.use(VXETable)

以下是我的项目依赖：
{
  "name": "test",
  "version": "1.0.0",
  "description": "项目描述",
  "author": "CGN",
  "private": true,
  "scripts": {
    "start": "npm run dev",
    "dev": "node --max_old_space_size=8192 node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --progress --config build/webpack.dev.conf.js",
    "prod": "node --max_old_space_size=8192 build/build.js",
    "test": "node --max_old_space_size=8192 build/build-test.js",
    "pre": "node --max_old_space_size=8192 build/build-pre.js",
    "entry": "node --max_old_space_size=8192 build/build-entry.js"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "crypto-js": "^4.0.0",
    "echarts": "^5.4.3",
    "psc-module": "1.0.0",
    "vue": "^2.5.2",
    "vue-axios": "^2.1.4",
    "vue-code-diff": "0.0.4",
    "vue-router": "^3.0.1",
    "vue-scroll": "^2.1.13",
    "core-js": "^3.6.5",
    "lodash": "4.17.21",
    "exceljs": "^4.3.0",
    "file-saver": "^2.0.5",
    "jspdf": "^2.5.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "@smallwei/avue": "^2.8.18",
    "monaco-editor": "^0.22.3",
    "vue-codemirror": "^4.0.6",
    "vuedraggable": "^2.24.3",
    "avue-plugin-ueditor": "^0.2.2",
    "babel-core": "^6.22.1",
    "babel-plugin-import": "^1.13.5",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.11",
    "element-ui": "^2.13.2",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "mockjs": "^1.0.1-beta3",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.14.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "qs": "^6.6.0",
    "rimraf": "^2.6.0",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^2.0.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-element-extends": "^1.0.9",
    "vue-i18n": "^8.9.0",
    "vue-infinite-scroll": "^2.0.2",
    "vue-loader": "^13.3.0",
    "vue-quill-editor": "^3.0.6",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "vuex": "^3.1.0",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0",
    "webpack-server": "^0.1.2",
    "vxe-table": "^3.6.6",
    "xe-utils": "^3.5.6",
    "qrcodejs2": "^0.0.2",
    "jsbarcode": "^3.11.5",
    "vue-print-nb": "^1.5.0", 
    "compression-webpack-plugin": "^1.1.12",
    "postcss-pxtorem": "^5.1.1",
    "vue-pdf-cs": "^1.0.2",
    "vue-pdf": "^4.3.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

### 期望的结果：

多选样式能够正常显示

### 操作系统：

window10

### 浏览器版本：

charome 80.0.3987.149

### vue 版本：

2.6.14

### vxe-table 版本：

3.8.9

**Comment by xlz26296** [comment]
去掉 ^ 改成"vxe-table": "3.6.6",

**Comment by aifeng12** [comment]
@xlz26296 这是什么原理，试了一下，还是不行

**Comment by xlz26296** [comment]
要重新依赖

**Comment by xlz26296** [comment]
#2437
#2435

**Comment by aifeng12** [comment]
@xlz26296 所以是要再引一下vxe-pc-ui这个库吗？

**Comment by xlz26296** [comment]
v4.7+才需要，老版本不需要

**Comment by aifeng12** [comment]
@xlz26296 那要怎么解决这个问题？

**Comment by xlz26296** [comment]
啥问题

**Comment by aifeng12** [comment]
@xlz26296 就是这个表格多选框样式丢失的问题

**Comment by xlz26296** [comment]
去掉 ^ 改成"vxe-table": "3.6.6",

**Comment by aifeng12** [comment]
@xlz26296 我是内网开发，这个包我是先在外网下载好了，然后装进这个项目的

**Comment by aifeng12** [comment]
@xlz26296 去掉 ^ 改成"vxe-table": "3.6.6", 删掉 node_modules，更新依赖
我是不是应该改成3.8.9指定这个版本，因为我的vxe-table是这个版本的

**Comment by xlz26296** [comment]
> @xlz26296 我是内网开发，这个包我是先在外网下载好了，然后装进这个项目的

那你要去外网再更新一次

**Comment by aifeng12** [comment]
@xlz26296 我在外网是直接npm i vxe-table@3.8.9，并不是在上面的package.json的基础上进行npm i的

**Comment by aifeng12** [comment]
@xlz26296 去掉 ^ 改成"vxe-table": "3.6.6", 删掉 node_modules，更新依赖
还是不行

**Comment by xlz26296** [comment]
去检查一下依赖，锁定版本号就行了

**Comment by jiubo** [comment]
> 去掉 ^ 改成"vxe-table": "3.6.6", 删掉 node_modules，更新依赖

4.7.17版本复选框也看不到，也需要在package.json依赖中把……去掉吗？

**Comment by aifeng12** [comment]
@xlz26296 有没有可能是我的webpack版本太低导致的，我用的是webpack3

**Comment by xlz26296** [comment]
> @xlz26296 有没有可能是我的webpack版本太低导致的，我用的是webpack3

可以去准备好复现demo

**Comment by aifeng12** [comment]
@xlz26296 @jiubo  解决了，去掉display:none 并且将伪元素的content去掉再去掉2px的border就可以了
