### ISSUE TITLE
懒加载树表格，首次调用 insertAt 时，会出现两条记录

### ISSUE THREAD

**Issue by road2coder** [x-extends/vxe-table#2477]
### 可复现的链接：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-mv45lw

### 问题描述与截图：

懒加载树表格，首次调用 insertAt 时，会出现两条记录

### 期望的结果：

正确显示一条记录

### 操作系统：

windows11 23H2

### 浏览器版本：

126.0.6478.127

### vue 版本：

3.4.31

### vxe-pc-ui 版本：

4.0.71

### vxe-table 版本：

4.6.18

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by Clover-You** [comment]
#2320 #2321

**Comment by xuliangzhan** [comment]
https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-nx4krt

**Comment by road2coder** [comment]
经验证最新版本（4.7.56）已解决，关闭问题
