### ISSUE TITLE
如果存在新增数据，getRowIndex 函数返回的序号错误

### ISSUE THREAD

**Issue by Clover-You** [x-extends/vxe-table#2479]
### 可复现的链接：

https://vxe-table-bug-example.ctong.top/2479

### 问题描述与截图：

https://github.com/user-attachments/assets/2333a051-c9f2-46a1-8c47-b6eb1e2be105

### 操作系统：

MacOS/Windows

### 浏览器版本：

Chrome 121.0.6167.139

### vue 版本：

3.4.19

### vxe-pc-ui 版本：

^4.0.46

### vxe-table 版本：

^4.7.53

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xlz26296** [comment]
[文档](https://vxeui.com/#/table/api?q=getRowIndex)都有说明的，返回的是 data 的索引

**Comment by Clover-You** [comment]
> [文档](https://vxeui.com/#/table/api?q=getRowIndex)都有说明的，返回的是 data 的索引

那应该怎么样才能正确获取某一行的索引？我需要在指定行之前或之后插入一行。提供的函数好像都无法做到？

**Comment by xlz26296** [comment]
你可以用 getVTRowIndex，文档其实都说很清楚了
[getRowIndex](https://vxeui.com/#/table/api?q=getRowIndex) 获取相对于 data 中的索引
[getVTRowIndex](https://vxeui.com/#/table/api?q=getVTRowIndex) 获取相对于当前数据中的索引
[getVTRowIndex](https://vxeui.com/#/table/api?q=getVTRowIndex) 获取渲染中的虚拟索引

**Comment by Clover-You** [comment]
> getVTRowIndex

这几个函数我试过了，不行

**Comment by Clover-You** [comment]
需要使用 getVTRowIndex 函数，看错了用了 getVMRowIndex

**Comment by hijack-621** [comment]
我也碰到了。已经有一行数据，然后加一行，使用getVTRowIndex 或者getRowIndex   都会得到 0  1 2  三条记录的索引

**Comment by hijack-621** [comment]
但是我打印表格的数据，确实只有两条记录，怎么会得到 三个记录的索引呢。导致一直报错。求救啊啊啊
