### ISSUE TITLE
使用 setRow 函数时，控制台报错: setRow is not a function

### ISSUE THREAD

**Issue by iwengx** [x-extends/vxe-table#2484]
### 可复现的链接（包含复现链接与示例代码）：

https://codesandbox.io/p/devbox/sweet-hooks-t8jw97

### 问题描述与截图：

如题，使用 `setRow` 函数时，控制台报错: 

```
setRow is not a function
```

### 期望的结果：

正常使用 setRow 函数

### 操作系统：

window10

### 浏览器版本：

Edge 126.0.2592.113 (正式版本) (64 位)

### vue 版本：

3.4.15

### vxe-pc-ui 版本：

无

### vxe-table 版本：

4.7.56

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
fix [4.7.57](https://github.com/x-extends/vxe-table/releases/tag/4.7.57)

**Comment by iwengx** [comment]
谢谢你的回复和修复 👍
