### ISSUE TITLE
自定义列拖动排序缓存失效

### ISSUE THREAD

**Issue by aifeng12** [x-extends/vxe-table#2488]
### 可复现的链接（包含复现链接与示例代码）：

https://github.com/x-extends/vxe-table/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

### 问题描述与截图：

  自定义列只有显示和隐藏有缓存，sort和fixed都没有缓存

<vxe-table
          :loading="loading"
          border
          resizable
          id="inspectionDetail"
          ref="multipleSelection"
          @checkbox-all="selectAllChange"
          @checkbox-change="selectChangeEvent"
          :custom-config="{
            mode: 'popup',
            storage: true,
          }"
          :data="tableData"
          :checkbox-config="{ checkMethod: checkboxMethod }"
        >

### 期望的结果：

sort和fixed缓存生效

### 操作系统：

window10

### 浏览器版本：

charome 80.0.3987.149

### vue 版本：

2.6.14

### vxe-pc-ui 版本：

00

### vxe-table 版本：

3.8.11

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by wangtaoSir** [comment]
我也碰到了这个问题。我项目用的是vue2.  vxe-table 最多升级到3.8.16。升级到3.8.16。还是有这个问题

**Comment by xuliangzhan** [comment]
#2510
