### ISSUE TITLE
表格自定义列读取缓存失效

### ISSUE THREAD

**Issue by aifeng12** [x-extends/vxe-table#2489]
### 可复现的链接（包含复现链接与示例代码）：

https://github.com/x-extends/vxe-table/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

### 问题描述与截图：

  当我点击工具栏对表格进行拖动排序，以及控制列显示和隐藏后点击确定，此时表格显示正常，当我重新进入这个页面，发现只有表格的显示隐藏被缓存了，于是我查看了缓存的数据，发现缓存是对的，只是表格初始化的时候没有读取到排序的缓存，只读取了显示和隐藏的缓存
<vxe-table
          :loading="loading"
          border
          resizable
          id="inspectionDetail"
          ref="multipleSelection"
          @checkbox-all="selectAllChange"
          @checkbox-change="selectChangeEvent"
          :custom-config="{
            mode: 'popup',
            storage: true,
          }"
          :data="tableData"
          :checkbox-config="{ checkMethod: checkboxMethod }"
        >

### 期望的结果：

sort缓存生效

### 操作系统：

window10

### 浏览器版本：

charome 80.0.3987.149

### vue 版本：

2.6.14

### vxe-pc-ui 版本：

00

### vxe-table 版本：

3.8.11

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by Over-reaction** [comment]
你这个使用3.8.9版本吧 我测试过了3.8.9 restoreStore属性刚出来 这个版本行  3.8.10到目前的3.8.16都不行

**Comment by aifeng12** [comment]
我这边已经解决了

**Comment by Over-reaction** [comment]
你这是换了我说的那个版本行了？还是别的方式解决了

**Comment by Over-reaction** [comment]
治标不治本  3.8.10到目前的3.8.16都不行 我很好奇这是什么原因导致的 是api改了 还是这个属性不能用了😐

**Comment by aifeng12** [comment]
我现在其实还不能完全确定是因为组件库的版本导致的，因为我的node版本之前也不太对，我现在再去换个其它版本试试

**Comment by Over-reaction** [comment]
你可以试一试 我3.8.10到目前的3.8.16都试了 是不行的

**Comment by aifeng12** [comment]
我有试了一下真的不可以，像你描述的那样👍

**Comment by aifeng12** [comment]
我又发现一个bug，在ie11版本下，自定义列的下拉框会跑出去，头疼

**Comment by Over-reaction** [comment]
所以这个到底咋回事 是api变动了 还是bug vue3版本我去试了 是可以的 vue2 3.8.10到目前的3.8.16 这么多版本都不行 如果是bug那太太太太持久了 就没人反馈🤨

**Comment by Over-reaction** [comment]
我改了源码 作者加了一个判断 我把判断去掉3.8.16 也可以了

**Comment by aifeng12** [comment]
你去提个bug去，把去掉判断的这个截图给他放上去，和加了判断导致的问题给他描述一下，看看他们怎么解决

**Comment by aifeng12** [comment]
你真棒

**Comment by wangtaoSir** [comment]
不知道3.8.16版本什么时候能修复这个bug

**Comment by wangtaoSir** [comment]
> 我改了源码 作者加了一个判断 我把判断去掉3.8.16 也可以了

求教，这个判断在哪里

**Comment by wangtaoSir** [comment]
@Over-reaction 求教，这个判断在哪里

**Comment by wangtaoSir** [comment]
找到了。

**Comment by wangtaoSir** [comment]
![Uploading 微信图片_20240807160200.png…]()

**Comment by wangtaoSir** [comment]
![微信图片_20240807160200](https://github.com/user-attachments/assets/6696874e-2878-4a6c-8c66-897d6c454798)

**Comment by wangtaoSir** [comment]
![11111111111](https://github.com/user-attachments/assets/3d92f978-022f-4b88-ae4c-67fc1c112b74)

**Comment by wangtaoSir** [comment]
作者这里判断  支持一级。 是什么意思呢

**Comment by aifeng12** [comment]
![D91C99C9-EBE5-46c9-82FF-ECF81E7779E3](https://github.com/user-attachments/assets/f74c5d19-5b9c-472d-9133-7dcdcd717f68)

**Comment by wangtaoSir** [comment]
这种应该很好改。css覆盖下。这个框的 滚动样式。应该就可以

**Comment by aifeng12** [comment]
ie浏览器很难调试，根本打不开f12

**Comment by wangtaoSir** [comment]
你项目比较牛逼，我们都用最新的谷歌浏览器。

**Comment by wangtaoSir** [comment]
![22222222](https://github.com/user-attachments/assets/84a3a885-df8a-46c7-9ba5-59209d89784b)

**Comment by wangtaoSir** [comment]
我电脑上只有edg. 你自己看着class 去覆盖喽

**Comment by aifeng12** [comment]
很无奈，打不开你这个界面，你明白吗，ie浏览器根本打不开这个元素页签

**Comment by wangtaoSir** [comment]
难道你电脑上没有别的浏览器。知道了dom 结构。还不是一样写css

**Comment by aifeng12** [comment]
ie浏览器和谷歌浏览器相同的css但是它的表现是不一样的，在谷歌浏览器并不会出现这种情况

**Comment by wangtaoSir** [comment]
是的，也挺难得。只能去试

**Comment by xuliangzhan** [comment]
#2510

**Comment by Over-reaction** [comment]
@wangtaoSir  不好意思😬刚看到 我一般不看邮箱 我也是去掉了那个判断

**Comment by Over-reaction** [comment]
@aifeng12 你这个应该是css不兼容
