### ISSUE TITLE
[vxe table v4.7.60] 缺少 "vxe-loading" 组件，请检查是否正确安装

### ISSUE THREAD

**Issue by aonoa** [x-extends/vxe-table#2505]
### 可复现的链接（包含复现链接与示例代码）：

https://vxetable.cn/#/component/table/base/full

### 问题描述与截图：

安装方式
```
pnpm install vxe-table@next
```
然后在vue文件中按需导入使用
```
import {VxeTable, VxeColumn, VxeUI, VxeColumnPropTypes} from 'vxe-table'
import 'vxe-table/lib/style.css'
```
使用部分代码使用文档完成案例`ts`代码 
`https://vxetable.cn/#/component/table/base/full` 

![image](https://github.com/user-attachments/assets/bf7d937a-3001-46bc-b5b5-ff5a1bb25ebc)

### 期望的结果：

正常加载

### 操作系统：

ubuntu22.04

### 浏览器版本：

Google Chrome 版本 112.0.5615.165（正式版本） （64 位）

### vue 版本：

3.4.35

### vxe-pc-ui 版本：

无

### vxe-table 版本：

4.7.60

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by aonoa** [comment]
使用全量导入导入table和vxe-ui后没问题，可能是我漏导入了组件

**Comment by moliyu** [comment]
仅导入table，使用loading插槽也报这个错误，而且loading不生效

**Comment by picking-zichun** [comment]
请问如何解决这个问题

**Comment by Limoer96** [comment]
如果只使用Table，loading功能无效，且没有任何可以在表格内部实现此功能的能力，所以不得不为了一个loading引入一个组件库

**Comment by EwanChen0917** [comment]
1. 从vxe-pc-ui引入VxeLoading组件
`import { VxeLoading } from 'vxe-pc-ui'`
2. 安装VxeLoading
`app.use(VxeLoading)`
