### ISSUE TITLE
自定义顺序列，不使用缓存自定义列

### ISSUE THREAD

**Issue by wangtaoSir** [x-extends/vxe-table#2510]
### 可复现的链接（包含复现链接与示例代码）：

ddddd

### 问题描述与截图：

![333333333333](https://github.com/user-attachments/assets/9daeaa02-29ef-406c-b149-0a16f4b51846)
parent 变量应该是写错了，这里这里不需要用parent。只支持一级的话。forEach 就之循环第一层。。望尽快修改此bug

### 期望的结果：

ddd

### 操作系统：

window10

### 浏览器版本：

3.8.16

### vue 版本：

2.7.14

### vxe-pc-ui 版本：

3.8.16

### vxe-table 版本：

3.8.16

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by wangtaoSir** [comment]
v4.7 的版本 修复了这个问题。用的是_xeUtils.default.eachTree(collectColumn, (column, index, items, path, parent) => {  。所以这里就是写错了。望及时修改 @

**Comment by xuliangzhan** [comment]
#2489
#2488

**Comment by wangtaoSir** [comment]
**感谢，作者修复此问题。v3.8.18 修复了此问题**
