### ISSUE TITLE
虚拟列表使用 reloadData 或 loadData 重载数据后，scrollToRow 以及 scrollTo 均无效

### ISSUE THREAD

**Issue by caroundsky** [x-extends/vxe-table#2512]
### 可复现的链接（包含复现链接与示例代码）：

https://stackblitz.com/edit/vitejs-vite-qspknm?file=App.vue

### 问题描述与截图：

详情看复现链接

### 操作系统：

win10

### 浏览器版本：

谷歌 127.0.6533.89

### vue 版本：

5.4.0

### vxe-pc-ui 版本：

无

### vxe-table 版本：

4.7.45

### 是否使用当前最新版本？

- [x] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
fix https://stackblitz.com/edit/vitejs-vite-wsoctt
