### ISSUE TITLE
vue2版本的更新计划

### ISSUE THREAD

**Issue by TuT-UI** [x-extends/vxe-table#2528]
### 这个需求解决了什么问题：

友爱的开源贡献者们
    你们好！有两个疑惑帮忙解答：1、是否计划对vue2的LTS；2、v3.9开放了一段时间又关闭了，是否按照计划考虑将各组件剥离。谢谢！

### 是否已有其他不错的替代方案：

否

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xuliangzhan** [comment]
目前已经分离 v3.9
