### ISSUE TITLE
vue2  3.8.24 版本在当前行下新增调用的insertAt，导致是在行上方新增，并且insertNextAt 方法报错（文档中的调用示例是错误的，且 insertNextAt 方法在此版本也是undefind）

### ISSUE THREAD

**Issue by flymaner** [x-extends/vxe-table#2542]
### 可复现的链接（包含复现链接与示例代码）：

https://vxetable.cn/v3.8/#/table/tree/crud

### 问题描述与截图：
![Uploading image.png…]()

### 操作系统：

windows11

### 浏览器版本：

都可以

### vue 版本：

2.6.11

### vxe-pc-ui 版本：

未使用

### vxe-table 版本：

 3.8.24

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by Gerib0y** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by flymaner** [comment]
![Uploading Snipaste_2024-09-04_21-32-24.png…]()
