### ISSUE TITLE
调用setAllCheckboxRow方法会选中禁用行

### ISSUE THREAD

**Issue by xiyure** [x-extends/vxe-table#2549]
### 可复现的链接（包含复现链接与示例代码）：

null

### 问题描述与截图：

![image](https://github.com/user-attachments/assets/8352ca64-63d0-4e57-87db-4d3020f808cc)
![image](https://github.com/user-attachments/assets/a75a7523-9faa-4337-b354-0192288d6b75)

### 期望的结果：

调用setCheckboxRow和setAllCheckboxRow方法时不会选中禁用行

### 操作系统：

window 11

### 浏览器版本：

126.0.6478.183

### vue 版本：

3.4.21

### vxe-pc-ui 版本：

4.0.82

### vxe-table 版本：

4.7.78

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xlz26296** [comment]
禁用选中是指用户的点击行为，并不是指手动调用代码去设置选中
