### ISSUE TITLE
外层使用flex自适应宽度时，表格宽度自适应有问题，每次窗口自适应都会有一个较长的变化过程

### ISSUE THREAD

**Issue by wekerSnail** [x-extends/vxe-table#2560]
### 可复现的链接（包含复现链接与示例代码）：

https://jsrun.net/xBDKp

### 问题描述与截图：

外层使用flex自适应宽度时，表格宽度自适应有问题，每次窗口自适应都会有一个较长的变化过程，使用最新版本依然如此

### 期望的结果：

正常自适应宽度

### 操作系统：

win11

### 浏览器版本：

Microsoft Edge 版本 128.0.2739.79 (正式版本) (64 位)

### vue 版本：

3.4.38

### vxe-pc-ui 版本：

4.1.29

### vxe-table 版本：

4.7.80

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by wekerSnail** [comment]
使用float布局则可以正常，flex布局有问题

**Comment by xlz26296** [comment]
看[文档](https://vxeui.com/#/component/table/base/autoHeight)的说明

**Comment by wekerSnail** [comment]
感谢，给父级增加overflow:hidden测试确实正常了

**Comment by xuliangzhan** [comment]
#2584
