### ISSUE TITLE
希望可以设置编辑状态下的行高,方便实现更人性化的编辑界面

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#2568]
### 这个需求解决了什么问题：

目前row-config.height可以设置行高,希望也能设置编辑行的行高, 这样可以在编辑行rendder更过方便编辑的控件,如多个checkbox,Textarea等,实现更人性化的编辑界面.

### 建议的 API 是什么样的：

row-config {
 height
 .....
 edit-height
}

### 是否已有其他不错的替代方案：

无

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xuliangzhan** [comment]
row-config.height 可以支持编辑模式了

**Comment by jianliulin** [comment]
> row-config.height 可以支持编辑模式了
感谢关注我的提议.  目前设置 row-config.height=30 后不管是编辑状态还是正常状态行高都是30了, 希望能有另外一个参数设置编辑状态下的行高,如正常状态下row-config.height=30 ,编辑状态下 row-config.edit-height=150 ,  当编辑状态下当前行高为150,退出编辑好就能恢复正的30, 这样在编辑状态下有150的行高的空间, 可以在上面摆放更多自定义的组建

另外: 更新后发现编辑状态下, 之前所有空间是上下居中,目前变成顶端对齐.
![image](https://github.com/user-attachments/assets/509d4859-73cf-4cea-b5d4-17d5a96286f2)

**Comment by jianliulin** [comment]
更新到4.7.82后 原来水平居中的checkbox 都顶端对齐了. 觉得还是4.7.81版水漂居中比较好看
![image](https://github.com/user-attachments/assets/f82b64db-72c5-4c84-b02f-4aaadc545624)
