### ISSUE TITLE
vxe-input 里的date-prev和date-next 有错误

### ISSUE THREAD

**Issue by Coding-Journey-Studio** [x-extends/vxe-table#2569]
### 可复现的链接（包含复现链接与示例代码）：

无

### 问题描述与截图：

date-prev和date-next 无法取value的值。不解构没有value
![image](https://github.com/user-attachments/assets/220e178f-c399-4157-9db6-ab8f60e9c210)
不知道切换月时，怎么能获取到月份的值。

### 操作系统：

windows10

### 浏览器版本：

Edge 129.0.2792.52

### vue 版本：

3.3.4

### vxe-pc-ui 版本：

无

### vxe-table 版本：

4.6.19

### 是否使用当前最新版本？

- [x] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
fix 4.7.82+

**Comment by Coding-Journey-Studio** [comment]
4.6版本不再修复了吗？

> 修复 4.7.82+

**Comment by xuliangzhan** [comment]
> 4.6版本不再修复了吗？
> 
> > 修复 4.7.82+

在没停止维护之前都会更新的，建议使用最新版本

**Comment by Coding-Journey-Studio** [comment]
> > 4.6版本不再修复了吗？
> > > 修复 4.7.82+
> 
> 在没停止维护之前都会更新的，建议使用最新版本

谢谢，静等4.6版本修复。
