### ISSUE TITLE
footer数据可以借用列数据的formatter来格式化显示数据

### ISSUE THREAD

**Issue by liuhaozhi** [x-extends/vxe-table#2588]
### 这个需求解决了什么问题：

目前的情况是，当我们设置了列内容的formatter以后，比如说货币格式，百分比等，footer数据没有被处理，还需要单独处理footer数据，一般情况下当我们formatter列数据以后，footer的数据也是需要的。

### 建议的 API 是什么样的：

null

### 是否已有其他不错的替代方案：

null

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xlz26296** [comment]
[文档](https://vxeui.com/#/component/table/footer/footerFormat) 都是有的

**Comment by liuhaozhi** [comment]
sorry,没有看仔细😁

**Comment by coder-xiaotian** [comment]
footerFormatter是哪个版本新加的，我用的4.6.25好像没有这个属性
