### ISSUE TITLE
在codesandbox.io 上如何才能用最新版的vxe-tble做demo反馈bug

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#2598]
### 这个需求解决了什么问题：

在codesandbox.io 上如何才能用最新版的vxe-tble做demo, 上面更新最新版只到4.6.x

![image](https://github.com/user-attachments/assets/fd771361-4d9a-44b5-a500-870a989c84d5)

### 建议的 API 是什么样的：

无

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xlz26296** [comment]
置顶公告都有的 #390

**Comment by jianliulin** [comment]
这demo就是从置顶公告fork的

**Comment by xlz26296** [comment]
package.json 就是所有包的版本号
