### ISSUE TITLE
form上的按钮不水平对齐

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#2605]
### 可复现的链接（包含复现链接与示例代码）：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-wwkxcf

### 问题描述与截图：

![image](https://github.com/user-attachments/assets/c9e3ec59-9cf4-48ce-a3af-50032d02afe3)

### 操作系统：

win2016

### 浏览器版本：

chrome

### vue 版本：

3.3.4

### vxe-pc-ui 版本：

4.2.20

### vxe-table 版本：

4.7.87

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
你这个链接没设置公开，看不到

**Comment by jianliulin** [comment]
不要意思, 现在可以了.

**Comment by xuliangzhan** [comment]
fix https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-r5yf83

**Comment by jianliulin** [comment]
谢谢
