### ISSUE TITLE
单独安装table 提示index.ts:133  [vxe table v4.7.91] 缺少 "vxe-tooltip" 组件，请检查是否正确安装。 

### ISSUE THREAD

**Issue by jeffhuien** [x-extends/vxe-table#2608]
### 可复现的链接（包含复现链接与示例代码）：

1

### 问题描述与截图：

![image](https://github.com/user-attachments/assets/fdd2ed17-68ff-4363-80eb-b23758abad9b)

### 操作系统：

win11

### 浏览器版本：

1

### vue 版本：

3.5

### vxe-pc-ui 版本：

没有安装

### vxe-table 版本：

4.7.91

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xlz26296** [comment]
4.7+ 的纯表格是不带任何 UI 组件的，就仅仅只是表格

**Comment by jeffhuien** [comment]
好的。 按照官网教程按需引入vxeUI , table ,打包后js文件1200kb ， css文件 900kb 
是正常的吗?  体积感觉不太正常

**Comment by jeffhuien** [comment]
> 4.7+ 的纯表格是不带任何 UI 组件的，就仅仅只是表格

按照官网教程按需引入vxeUI , table ,打包后js文件1200kb ， css文件 900kb
是正常的吗? 体积感觉不太正常

**Comment by FugitiveLc** [comment]
属性改一下就行了 
 show-overflow="title"
 show-header-overflow="title"
 show-footer-overflow="title"

**Comment by junjie-lean** [comment]
3.9.20版本也有问题

**Comment by nyy-2017** [comment]
[vxe table v4.13.31] 缺少必要的 "footer-data | footer-method" 参数，这可能会导致出现错误

**Comment by secrectFG** [comment]
所以说到底怎么解决？

**Comment by ldf19910914** [comment]
这个问题难道至今都么有优化好吗？我现在还存在这个问题，时好时坏的
