### ISSUE TITLE
设置全局 zIndex 后，弹窗表格中的 VxeSelect 组件无法进行搜索

### ISSUE THREAD

**Issue by PurpleNoon** [x-extends/vxe-table#2612]
### 可复现的链接（包含复现链接与示例代码）：

https://github.com/PurpleNoon/vxe-select-filterable-bug-recurrent

### 问题描述与截图：

在弹窗中使用可编辑表格，使用 VxeSelect 时，发现弹窗遮挡了面板，因此在 src/main.ts 中设置了 zIndex: 3000，此时发现弹窗中可编辑表格的 VxeSelect 组件无法进行搜索
![image](https://github.com/user-attachments/assets/7b1a139c-436e-4177-af0e-d23d7f82a2a5)

### 期望的结果：

期望表格中 VxeSelect 可以正常输入并筛选

### 操作系统：

window10

### 浏览器版本：

130.0.6723.59

### vue 版本：

3.5.12

### vxe-pc-ui 版本：

4.2.26

### vxe-table 版本：

4.7.94

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xlz26296** [comment]
这个是你用的组件库用了 vueuc 这个库，会拦截任何挂在 body 元素的 focus 事件，就算你用 n-date-picker 自己的也一样无法使用，跟 vxe 没任何关系

```html
<NModal
      v-model:show="isShowUserConfigModel"
      preset="card"
      size="huge"
      title="用户配置"
      transform-origin="mouse"
      width="1300px"
    >
      <NDatePicker v-model:value="timestamp" type="datetime" to="body" />
    </NModal>
```

**Comment by PurpleNoon** [comment]
确实如此，不好意思，我去排查一下
