### ISSUE TITLE
在edit表格中，插槽方式使用第三方Ui组件的时候，无法选中第三方UI数据

### ISSUE THREAD

**Issue by liuhaozhi** [x-extends/vxe-table#2624]
### 可复现的链接（包含复现链接与示例代码）：

无

### 问题描述与截图：

1:表格edit状态
2:使用slots插入第三方Ui组件（我使用的是naive-ui的下拉框和日期)
3:点击选项或日期后，组件弹窗直接消失，没有触发选择数据动作

### 期望的结果：

可以在触发完组件的动作以后，再关闭编辑弹窗

### 操作系统：

macos

### 浏览器版本：

charom 

### vue 版本：

3.3.34

### vxe-pc-ui 版本：

4.7.44

### vxe-table 版本：

4.7.44

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by khan97z** [comment]
我觉得你可以在下拉框的组件类名添加一个vxe-table--ignore-clear

**Comment by khan97z** [comment]
我觉得你可以在popper组件上添加一个类名vxe-table--ignore-clear  [https://vxetable.cn/#/global/interceptor/table/base](https://vxetable.cn/#/global/interceptor/table/base)

**Comment by xlz26296** [comment]
需要[安装第三方兼容扩展插件](https://vxeui.com/other4/#/plugin-render-naive/install)就可以了

**Comment by liuhaozhi** [comment]
感谢二位解惑。
