### ISSUE TITLE
warning 问题

### ISSUE THREAD

**Issue by MitchellRyrie-evanBuck** [x-extends/vxe-table#2625]
### 可复现的链接（包含复现链接与示例代码）：

-

### 问题描述与截图：

当我自定义导入样式时
<img width="729" alt="image" src="https://github.com/user-attachments/assets/dfee706c-1e61-4ac0-bb0a-48b98b3067ed">
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/c707d44e-c4b2-48e9-ab52-ac8847c16e6a">

### 期望的结果：

修复 bug Warning

### 操作系统：

MacOs 15.1

### 浏览器版本：

版本 130.0.6723.92（正式版本） (arm64)

### vue 版本：

3.4.25

### vxe-pc-ui 版本：

4.2.40

### vxe-table 版本：

4.7.86

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by haohaitao** [comment]
上面的问题不是仓库的问题，是sass的语法规则变化。

**Comment by MitchellRyrie-evanBuck** [comment]
> 上面的问题不是仓库的问题，是sass的语法规则变化。

我知道是语法规则变化问题 ，但问题是是安装的依赖里面报的 不还是仓库源代码的问题吗？
