### ISSUE TITLE
【需要帮助】使用loadData加载数据后，滚动条会回到顶部

### ISSUE THREAD

**Issue by c-sopoo** [x-extends/vxe-table#2632]
### 可复现的链接（包含复现链接与示例代码）：

https://codepen.io/c-sopoo/pen/MWNzVJB

### 问题描述与截图：

vue2.7,
loadData后保持滚动条位置，看文档scrollToTopOnChange默认为false，即使手动设置为false也不管用

### 期望的结果：

保持位置

### 操作系统：

win10

### 浏览器版本：

130.0.6723.117

### vue 版本：

2.7

### vxe-pc-ui 版本：

^3.2.15

### vxe-table 版本：

^3.10.8

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by zyf540860996** [comment]
确实存在，需求要局部更新数据，比如滚动后更新 第1000~1100行数据，更新后直接回顶部了，4.8.8 版本也存在这问题，4.2.6不会回到顶部，但是4.2.6有树结构高亮bug

**Comment by c-sopoo** [comment]
试试最新版本，好像修复了
