### ISSUE TITLE
横向滚动时，行高会变化

### ISSUE THREAD

**Issue by richex-cn** [x-extends/vxe-table#2652]
### 可复现的链接（包含复现链接与示例代码）：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-lkw6c5?workspaceId=58424a35-60e4-471b-9b63-348d150a3f6e

### 问题描述与截图：

如视频所示，分别展示了用鼠标拖动滚动条和使用 Shift + 鼠标滚轮 进行横向滚动的效果：

https://github.com/user-attachments/assets/90dbefc0-fa0d-40dd-b33c-ee2eccdf95e3

### 期望的结果：

行高不应出现变化

### 操作系统：

Windows 11

### 浏览器版本：

Chrome 131.0.6778.86

### vue 版本：

3.5.13

### vxe-pc-ui 版本：

4.3.1

### vxe-table 版本：

4.9.1

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
[fix](https://codesandbox.io/p/sandbox/vxe-table-4-x-cell-height-issue-forked-5dh9m5)

**Comment by richex-cn** [comment]
你好，当 table.show-overflow 为 true 时，该问题还是会出现，我更新了复现链接的代码：
https://codesandbox.io/p/sandbox/dank-leaf-lkw6c5

```js
...
        showOverflow: true,
        columns: [
          { field: "name", title: "Name", width: 100, showOverflow: false },
          {
            field: "avatar",
            title: "Avatar",
            width: 200,
            showOverflow: false, // 这里如果不设置，图片会溢出单元格显示
            cellRender: { name: "CellImage", props: { height: 200 } },
          },
...
```
