### ISSUE TITLE
当 `table.show-overflow` 为 `true` 时，行高还是有问题

### ISSUE THREAD

**Issue by richex-cn** [x-extends/vxe-table#2667]
当 `table.show-overflow` 为 `true` 时，行高还是有问题，复现链接：
https://codesandbox.io/p/sandbox/dank-leaf-lkw6c5

```js
...
        showOverflow: true,
        columns: [
          { field: "name", title: "Name", width: 100, showOverflow: false },
          {
            field: "avatar",
            title: "Avatar",
            width: 200,
            showOverflow: false, // 这里如果不设置，图片会溢出单元格显示
            cellRender: { name: "CellImage", props: { height: 200 } },
          },
...
```

https://github.com/user-attachments/assets/a82158c7-2d9f-4935-9b09-3113c051b04d

_Originally posted by @richex-cn in https://github.com/x-extends/vxe-table/issues/2652#issuecomment-2505676943_

**Comment by richex-cn** [comment]
> 表格如果加上`table.show-overflow`必须是等行高，要动态高度需要去掉才行

看起来现在还不能同时支持动态高度以及文本溢出，有办法支持这种情况吗？

如果无法支持，建议在文档相关位置添加说明避免有人再次在相同的地方耗费时间。

**Comment by xlz26296** [comment]
> > 表格如果加上`table.show-overflow`必须是等行高，要动态高度需要去掉才行
> 
> 看起来现在还不能同时支持动态高度以及文本溢出，有办法支持这种情况吗？
> 
> 如果无法支持，建议在文档相关位置添加说明避免有人再次在相同的地方耗费时间。

你要动态行高就不需要加 ·```table.show-overflow```，这个是固定行的用法

**Comment by richex-cn** [comment]
好的了解了，谢谢。
如果需要动态行高的同时实现单元格，可以在单元格内通过 cell render 等方式自行实现。
