### ISSUE TITLE
表格动态高度计算问题

### ISSUE THREAD

**Issue by super-programmer** [x-extends/vxe-table#2685]
### 可复现的链接（包含复现链接与示例代码）：

http://esuat.zhonghongji.com.cn/proof/proof-shop/proof-shop-line

### 问题描述与截图：

height设置为auto和100%的，并且有分页的情况下，动态表格高度计算未减去分页器的高度

### 期望的结果：

减去分页器高度

### 操作系统：

windows10

### 浏览器版本：

131.0.6778.109

### vue 版本：

^2.6.14

### vxe-pc-ui 版本：

3.1.28

### vxe-table 版本：

3.9.3

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by zkzgs** [comment]
你挂个项目地址干什么

**Comment by super-programmer** [comment]
这个本地复现 ，随便挂的地址
