### ISSUE TITLE
启用列配置和横向滚动导致表格空白

### ISSUE THREAD

**Issue by ChobitsSP** [x-extends/vxe-table#2688]
### 可复现的链接（必须为公开链接，仅包含能复现问题的示例代码）：

https://codepen.io/chobitssp/pen/OPLRKNd

### 问题描述与截图：

启用scroll-x时
表格列配置restoreStore 和 数据刷新间隔时间过短
会有概率导致表格空白

### 操作系统：

windows10

### 浏览器版本：

chrome 131.0.6778.86

### vue 版本：

2.7.14

### vxe-pc-ui 版本：

3.3.30

### vxe-table 版本：

3.11.26

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
[fix v3.11.29+](https://codepen.io/xuliangzhan/pen/OPLbLQb)
