### ISSUE TITLE
开启动态行高虚拟滚动时，拉到表格最下方显示空白，往上慢滚表格数据闪烁

### ISSUE THREAD

**Issue by this-me0** [x-extends/vxe-table#2713]
### 可复现的链接（必须为公开链接，仅包含能复现问题的示例代码）：

https://github.com/user-attachments/assets/5c18490e-5d2b-4c87-b4c9-e9580501290a

### 是否已准备好复现 demo？

- [ ] 我已确认要求提供复现链接与示例代码

### 问题描述与截图：

![xiding1](https://github.com/user-attachments/assets/5c18490e-5d2b-4c87-b4c9-e9580501290a)

### 操作系统：

windows10

### 浏览器版本：

131.0.6778.205

### vue 版本：

2.6.11

### vxe-pc-ui 版本：

3.9.1

### vxe-table 版本：

3.9.1

### 是否使用当前最新版本？

- [x] 我已确认是使用最新版本并已按要求提供复现链接与示例代码

**Comment by AgentXiangsu** [comment]
遇到了同样的问题，快速滚动会有一段白屏，请问是怎么处理的
