### ISSUE TITLE
最后一个表头的筛选，可以不超过表格右侧吗？

### ISSUE THREAD

**Issue by C-Ella** [x-extends/vxe-table#430]
### 请填写问题描述 Describe

![image](https://user-images.githubusercontent.com/13741967/66879854-c81d5380-eff2-11e9-8ff2-a7d76736232b.png)

如果table贴近页面右侧，会撑开布局，强制隐藏后盖住部分无法点击使用。

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by Fishcyz** [comment]
2.6版本已解决

**Comment by hamal-ho** [comment]
> 2.6版本已解决

3.6.9版本还是存在，如果第一次点击“最后一个表头的筛选”，会超过表格右侧
