### ISSUE TITLE
小白的一个修改建议

### ISSUE THREAD

**Issue by QhdSuperMan** [x-extends/vxe-table#432]
所有版本
大佬 你再定义参数的时候能不能规避一些常用参数   我们项目中有全局minin然后跟你的prop冲突
程序员常用的参数可以加一些前缀。。我们再愁怎么改呢。另外这个组件很棒，我相信这个插件肯定会越来越火的 我们会帮你推的。拉更多的人下水才有生态。哈哈

**Comment by xuliangzhan** [comment]
各个组件的参数都会用到一些常用的属性，这都是正常的用法，如果你要使用全局minin，那应该是就要在项目中要把属性命名私有化，不然改了这个属性，要是用了另外的组件也要相同的属性，那还是一样出问题。
