### ISSUE TITLE
表格设置showOverflow首次渲染列宽瞬间列宽跳动

### ISSUE THREAD

**Issue by napai** [x-extends/vxe-table#445]
### （必填）请填写问题描述 Describe the bug

暂时用这样的方法解决 
```js
//修复初始加载跳动问题
if(this.firstLoad){
    this.$refs.dataTable.recalculate().then(()=>{
        this.firstLoad = false;
        this.$refs.dataTable.$el.querySelector('.vxe-table--body').style.visibility='visible';
    });
}
```

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior
要么直接修复这样的问题,     要么添加 recalculate 的回调方法
 ?

### （必填）请填写版本号 Version
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by napai** [comment]
建议给bodywraper不可见， 等列宽度渲染完成后显示！

**Comment by napai** [comment]
AJAX获取数据后处理方法, 虽然可以解决! 如果有 recalculate 的回调事件 就好了!
//修复初始加载跳动问题if(this.firstLoad){ this.$refs.dataTable.recalculate().then(()=>{ this.firstLoad = false; this.$refs.dataTable.$el.querySelector('.vxe-table--body').style.visibility='visible'; }); }

**Comment by xlz26296** [comment]
可以设置 optimization.cloak 试下
