### ISSUE TITLE
这个组件在ie11上使用会有些兼容性问题

### ISSUE THREAD

**Issue by yanglujie** [x-extends/vxe-table#521]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 ?解决ie11兼容性问题

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?ie11会报 Unhandled promise rejection TypeError: 对象不支持“find”属性或方法 这个错误

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
这是面向现代浏览器的表格组件，IE11你可以使用 babel-polyfill

**Comment by yanglujie** [comment]
使用了这个插件，在ie中显示也有问题，还是说找不到find方法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: abc <notifications@github.com&gt;
发送时间: 2019年11月14日 16:18
收件人: xuliangzhan/vxe-table <vxe-table@noreply.github.com&gt;
抄送: yanglujie <619383909@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xuliangzhan/vxe-table] 这个组件在ie11上使用会有些兼容性问题 (#521)




这是面向现代浏览器的表格组件，IE11你可以使用 babel-polyfill
