### ISSUE TITLE
分辨率 1920*1080  屏幕缩放 125% 出现横纵滚动条抖动

### ISSUE THREAD

**Issue by q21syj** [x-extends/vxe-table#579]
### （必填）请填写问题描述 Describe the bug
分辨率 1920*1080  屏幕缩放 100% 150% 正常使用
在屏幕缩放  125%时 出现抖动  感觉像计算宽高的问题
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
 ?
![image](https://user-images.githubusercontent.com/6267983/70305434-55389800-183f-11ea-8157-febf69c704d5.png)
![image](https://user-images.githubusercontent.com/6267983/70305457-641f4a80-183f-11ea-8771-44cbbcf9f2b4.png)
一会儿 有滚动条 一会儿 没有滚动条 来回闪动

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version
2.6
- os: windows 10
- browser:  谷歌
- vue: 2.6.10
- vxe-table: 2.6.22

**Comment by xingyuebaobei** [comment]
遇到同样的滚动条抖动问题

**Comment by sonicwang1989** [comment]
同样，有解决的吗

**Comment by codehyd** [comment]
有解决的办法吗

**Comment by sunjinbo321** [comment]
只要保证他的父容器或祖先容器不要用felx：1属性，有固定高度或者宽度，如果父容器或者祖先容器宽高要改动最好用css改变他的大小有需要可以加上动画。他这个和echars也有echarts如果父容器有flex：1他的resize也会有问题
