### ISSUE TITLE
请问编辑状态不能有多行吗？

### ISSUE THREAD

**Issue by Peterpig** [x-extends/vxe-table#583]
### 请填写问题描述 Describe
问题1：我现在的vxe-grid 需要一个批量编辑的功能，即多行处于编辑状态，但是发现，无论如何，只会有一行处于编辑状态。

问题2：如果表格列过多，每次setActiveRow 会自动重置左右滚动条
### 请填写版本号 Version

- os: mac 
- browser: chrome78
- vue: 2.7
- vxe-table: 2

**Comment by ChillyBreeze1998** [comment]
same problem
