### ISSUE TITLE
当固定列和show-header-overflow show-overflow这两个属性同时使用时，出现表头表体错位

### ISSUE THREAD

**Issue by NicholasZhaoS** [x-extends/vxe-table#606]
当左侧固定一列后，并且使用show-header-overflow show-overflow这两个属性时，当列不能完全显示，产生左右滑动时，从第二列到第八列，表头和表体产生错位

链接：https://jsrun.pro/c5WKp

**Comment by virycs** [comment]
终于有人遇到和我一样的问题了，错位还好，主要是在表格只有很少列的时候，错位导致body宽度超过100%，出现了水平滚动条

**Comment by NicholasZhaoS** [comment]
@virycs 你用的哪个版本，他最新的版本更新了这个问题，但是向右滑动到最后还有问题，我把修复的代码改到2.6.21版本暂时没有问题

**Comment by virycs** [comment]
我从1.8到2.6.0都有问题。我几个月前就提过了，但是没有线上重现链接作者也没给解决。这个问题在某种分辨率下是没问题的，改变了电脑分辨率就出现了。我开发过程经常台式显示器和笔记本之间切换，所以一直出现这个问题

**Comment by virycs** [comment]
https://github.com/xuliangzhan/vxe-table/issues/599
开始我以为是样式冲突导致，所以直接下载了作者的demo工程，把vxe-table改为了vxe-grid，只有三列就错位出现水平滚动条。错位其实表格不用boder还能接受，但是水平滚动条这个有点难搞

**Comment by xlz26296** [comment]
2.7.5+没发现有这个问题。你可以更新试试
