### ISSUE TITLE
当出现纵向和横向滚动条时，表头与表体错位

### ISSUE THREAD

**Issue by NicholasZhaoS** [x-extends/vxe-table#620]
当出现纵向和横向滚动条时，表头和表体错位
当使用show-header-overflow和show-overflow属性时，表格右侧结尾向右偏移
当不使用上边两个属性时，表体整体向左偏移

重现链接  https://jsrun.pro/c5WKp

**Comment by superhos** [comment]
?????又是没处理就关闭了？把bot关掉吧
