### ISSUE TITLE
筛选渲染器 filter-render使用方法求助

### ISSUE THREAD

**Issue by tclqlove** [x-extends/vxe-table#624]
使用CDN 
<script src="https://cdn.jsdelivr.net/npm/xe-utils"></script>
<script src="https://cdn.jsdelivr.net/npm/vxe-table"></script>
如何使用filter-rende

**Comment by airzg** [comment]
两种方式
1、template中，请参考 https://xuliangzhan.github.io/vxe-table/#/table/advanced/manualFilter
2、render中
filters: [{ data: '' }],
          filterMultiple: false,
          slots: {
            default: ({ row, column }) => {
              return [
                <Icon type="ios-radio-button-on" color={ this.getIconColor(row) } size="20" />
              ]
            },
            filter: ({ column, context }) => {
              return column.filters.map(option => {
                return <table-filter current={ this.currentSel } onFilter={ (val) => this.filters(val) }></table-filter>
              })
            }
          }
