### ISSUE TITLE
设置 :mouse-config="{selected: true}"之后不能复制单元格内容

### ISSUE THREAD

**Issue by qq592304796** [x-extends/vxe-table#626]
### （必填）请填写问题描述 Describe

设置 :mouse-config="{selected: true}"

不能复制单元格内容

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://jsrun.pro/HAWKp/edit

### （必填）请填写版本号 Version

- os: windows10
- browser: chrome-79.0.3945.88
- vue: 2.6.10
- vxe-table: 2.7.14

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试
