### ISSUE TITLE
table column 自定义插槽问题

### ISSUE THREAD

**Issue by airzg** [x-extends/vxe-table#631]
### （必填）请填写问题描述 Describe

 网站demo 运行ok
https://xuliangzhan.github.io/vxe-table/#/table/grid/template
vxe-table v2.7.18集成到现有环境中，使用自定义插槽
跟示例--自定义插槽 name_default类似
cell.js中 slots.default 报错，不是函数
renderCell: function renderCell(h, params) {
    if (slots && slots.default) {
      return slots.default(params, h);
    }

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os:  win
- browser:  chrome
- vue: 2.6.10
- vxe-table: 2.7.18

**Comment by xlz26296** [comment]
那是 2.7.19+ 才支持的

**Comment by airzg** [comment]
> 那是 2.7.19+ 才支持的

你好，对vxe-table二次封装后，父组件中使用自定义插槽，会报错，插槽不存在

<vxe-table-grid
      :tableColumn="tableColumn"
      :tableData="tableData"
    >
      <template v-slot:name_default="{ row, column }">
        <span>
          <span style="color: red;">{{ row.name }}</span>
        </span>
      </template>
    </vxe-table-grid>

![image](https://user-images.githubusercontent.com/54803505/71890581-9219e680-317f-11ea-97a6-bdcb6174d89f.png)

**Comment by hellolex** [comment]
遇到了同样问题，二次封装时插槽提示不存在，有什么解决方案吗？

**Comment by docodocool** [comment]
你好, 请问这个问题是怎么解决的?
