### ISSUE TITLE
table-column 添加快捷菜单

### ISSUE THREAD

**Issue by yan695432** [x-extends/vxe-table#637]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 同一个table中，不同的column对应的快捷菜单是不同的

### （必填）建议的 API 是什么样的 What does the proposed API look like

 和table一样

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 否

**Comment by xlz26296** [comment]
快捷菜单的权限控制本身就是精确到某个单元格
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/menuPrivilege
