### ISSUE TITLE
excel导出分页的全部数据

### ISSUE THREAD

**Issue by HappyDongD** [x-extends/vxe-table#638]
### 请填写问题描述 Describe

表格分页之后，导出功能只导出的是当前页的，想能否有一个全部导出的功能。
比如选择全部数据后，对后台发起请求，pagesize设置成totalPage即可？？？

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
不是可以自定义 data 的吗
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/export

**Comment by HappyDongD** [comment]
导出数据这边的确是有，集成的vxe-table-plugin-excel并没有全部导出的功能，如果能和bootstrap table一样就好了
