### ISSUE TITLE
树表格子类排序问题

### ISSUE THREAD

**Issue by ccc-chan** [x-extends/vxe-table#639]
### （必填）请填写问题描述 Describe
需求：希望排序树表格里面的子类，父类不变

     <vxe-table
      border
      :tree-config="tableTreeConfig"
      height="300"
      highlight-hover-row
      show-overflow
      :checkbox-config="{labelField: 'name'}"
      :data="tableData"
      @select-change="selectChangeEvent"
      :sort-config="{remote: 'true'}"
      @sort-change="sortMethod"
      >
    
      <vxe-table-column type="seq" width="100" fixed="left"></vxe-table-column>
      <vxe-table-column class="main" field="name" title="Name" width="300" tree-node type="checkbox"></vxe-table-column>
      <vxe-table-column field="tel" title="Role" width="300" remote-sort></vxe-table-column>

 ?

### （必填）请填写能重现问题的链接
sortMethod({ column, property, order }){
      console.log( column, property, order )
}
这个函数应该怎么返回才可以得到想要的结果呢？

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.5.2
- vxe-table: 2.7.2

**Comment by xuliangzhan** [comment]
这个是不支持的，可以通过自定义排序解决
