### ISSUE TITLE
将单元格渲染成可编辑 是不推荐的用法吗？

### ISSUE THREAD

**Issue by Theone21** [x-extends/vxe-table#641]
### 将单元格渲染成可编辑 是不推荐的用法吗？
就像下图所示的一样
![image](https://user-images.githubusercontent.com/29767834/72163834-850b2a80-33ff-11ea-9ce8-c4ccf56f27ea.png)

**Comment by senbrid** [comment]
![image](https://user-images.githubusercontent.com/30211186/73633709-513bc180-469a-11ea-8397-33bbc72a2338.png)
