### ISSUE TITLE
希望 【内容溢出显示为省略号】可以支持自定义行数 或者双行

### ISSUE THREAD

**Issue by wupeiwen233** [x-extends/vxe-table#654]
### （必填）这个需求解决了什么问题 What problem does this feature solve

某些场景下 我希望单元格里的文本内容可以在超过两行时才显示为空格 
现在要想再vxe-table实现这个需求  只能自定义模板无法复用   希望可以自定行数 

### （必填）建议的 API 是什么样的 What does the proposed API look like

  只要改下根据参数更改样式即可  -webkit-line-clamp: 2;

### 是否已有其他不错的替代方案 Describe alternatives you've considered

无

**Comment by xuliangzhan** [comment]
这个样式相关的可能不会支持的，你可以根据不同的业务创建不同的渲染器，这样就可以实现复用了
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/default

**Comment by wupeiwen233** [comment]
> 这个样式相关的可能不会支持的，你可以根据不同的业务创建不同的渲染器，这样就可以很简单的实现复用了
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/default

我有想过 但感觉很麻烦 
1、您的tooltip组件没有共享出来，我用element-popover还要再去解决组件兼容问题 
2、请教一下您是怎么判断文本是否溢出的呢
