### ISSUE TITLE
[vxe-table] 横向虚拟滚动不支持分组表头

### ISSUE THREAD

**Issue by mylysddp** [x-extends/vxe-table#671]
### （必填）请填写问题描述 Describe

 使用vxe-grid ,制作表单，大概有110列，都其中几列做分组表头，提示[vxe-table] 横向虚拟滚动不支持分组表头。这是本身控件就不支持，还是我的配置有问题呢。

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6
- vxe-table: 2.7.24

**Comment by xlz26296** [comment]
你可以关闭横向虚拟滚动，启用后是不支持分组表头的
```
:optimization="{scrollX: {gt: 400}}"
```
