### ISSUE TITLE
Solt 事件设置

### ISSUE THREAD

**Issue by yan695432** [x-extends/vxe-table#673]
### （必填）请填写问题描述 Describe

 通过:columns="tableColumn" 设置vxe-grid的列，{
              field: 'col1',
              title: '列',
              slots: {
                default: ({ row, column }) => {
                  return [
                    <el-button
                      type="text"
                      size="mini"
                    >
                      {row[column.property]}
                    </el-button>
                  ]
                }
              },
              width: 80
            }
怎么给这个自定义模板中的button响应按钮事件

### （必填）请填写版本号 Version

os: win10
browser: chrome
vue: 4.1.1
vxe-table: 2.7.24

**Comment by LiuduZero** [comment]
你这里面没有 button 啊，我从 button 上 emit 事件然后接收的，可以实现

**Comment by yan695432** [comment]
slots: {
            default: ({ row, column }) => {
              return [<el-Button>{row[column.property]}</el-Button>]
            }
          } 这种方法，如果要加button的click事件要怎么实现

**Comment by LiuduZero** [comment]
> slots: {
> default: ({ row, column }) => {
> return [{row[column.property]}]
> }
> } 这种方法，如果要加button的click事件要怎么实现

return [<button on-click="click">{row[column.property]}</button>]

**Comment by yan695432** [comment]
slots: {
            default: ({ row, column }) => {
              return [<el-Button>{row[column.property]}</el-Button>]
            }
          } 前面的发错了

**Comment by yan695432** [comment]
slots: {
            default: ({ row, column }) => {
              return [<Button>{row[column.property]}</Button>]
            }
          }

**Comment by yan695432** [comment]
slots: {
            default: ({ row, column }) => {
              return [<Button>{row[column.property]}<Button>]
            }
          }

**Comment by yan695432** [comment]
[<el-Button>{row[column.property]}</el-Button>]

**Comment by yan695432** [comment]
return的是button，好像button发不出去，就是return后面的是button

**Comment by yan695432** [comment]
怎么在slots中写emit事件

**Comment by LiuduZero** [comment]
> 怎么在slots中写emit事件

单元格渲染器？
