### ISSUE TITLE
行编辑时，增加treeSelect组件

### ISSUE THREAD

**Issue by iamascv** [x-extends/vxe-table#682]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 选项非常多，需要分成列举，比如说选择县区，层级可以分为：国家->省->市->县区

### （必填）建议的 API 是什么样的 What does the proposed API look like

（1） 提供是否能选择非叶子节点.（2）多选 ，暂时只有这两个

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
没看出这个功能不能实现 
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/elementPage
