### ISSUE TITLE
expand-config展开配置需求

### ISSUE THREAD

**Issue by yan695432** [x-extends/vxe-table#685]
### （必填）请填写问题描述 Describe

 :expand-config="{accordion: true,lazy: true, loadMethod: loadContentMethod}" 同时设置 懒加载和手风琴效果，但是第一次展开时无法展开，只有已经进行懒加载完成之后的行才有效果

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

os: win10
browser: chrome
vue: 4.1.1
vxe-table: 2.7.24

**Comment by geLouTingFengSheng** [comment]
同问
