### ISSUE TITLE
建议新增tr 整行点击

### ISSUE THREAD

**Issue by qiuguanyou** [x-extends/vxe-table#691]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 解决点击某行数据，打开查看该行详情的需求

### （必填）建议的 API 是什么样的 What does the proposed API look like

 rowclick

**Comment by yinglong** [comment]
这个功能可以用cell-click完成，因为这个属性时配置在整个表格里的，所以点击任意单元格均可触发，效果和点击行触发是一致的
