### ISSUE TITLE
中英文排序，顺序不对

### ISSUE THREAD

**Issue by zhangya5847** [x-extends/vxe-table#694]
### （必填）请填写问题描述 Describe the bug
中英文排序的顺序不对。排序结果是中英文分类，分别排序

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://codesandbox.io/s/vxe-table-ceshide-demo-ewf3p

### （必填）请填写期望的结果 Expected behavior
期望能够整体排序，而不要分类排序

### （必填）请填写版本号 Version

- os: Mac 10.14.5
- browser: chrome 80.0
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by xlz26296** [comment]
如果默认的排序不能满足特殊需求，可以使用自定义排序
https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?filterName=sort-method

**Comment by Zachary-zm** [comment]
这bug现在一直有，用了sort-change的话英文排序也不对，sort-method又废弃了。
