### ISSUE TITLE
新追加的行不能直接反应到table中

### ISSUE THREAD

**Issue by linling0103** [x-extends/vxe-table#698]
### （必填）请填写问题描述 Describe
在table中追加一行新的数据，
 sample：
    姓名       年龄
    aa          19
    BB          20
    新追加的数据( xTable.insertAt(record,  this.tableData[row]))
    dd          24
当从下往上做删除操作时(xTable.remove(xTable.getCurrentRecord());)
删除dd继续删除的话，会跳过新追加的数据  而直接删除BB。
也就是说新追加的数据没有被识别。为什么呢？有什么方法能直接
将新追加的数据加载到tabledata中吗？请告知  谢谢
注:新追加的数据  返回的row-index为 -1

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### （必填）请填写版本号 Version
最新版

**Comment by Pancho2wang** [comment]
使用const { fullData } = this.xTable.getTableData(); 获取到全量的数据
使用$rowIndex 替代 rowIndex
