### ISSUE TITLE
通过代码选中行

### ISSUE THREAD

**Issue by furuihe** [x-extends/vxe-table#699]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 通过代码选中行。
我想实现类Excel的一个功能，需要通过代码选中行，当前设置
:mouse-config="{selected: true, checked: true}“
:keyboard-config="{ isArrow: true, isDel: true, isTab: true, isCut: true, isEnter: true, isEdit: true }"

### （必填）建议的 API 是什么样的 What does the proposed API look like
setMouseCheckeds(rows)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 无

**Comment by xuliangzhan** [comment]
不会考虑支持这样功能的哦，需要注意 checked 也仅仅是实验功能，要实现 excel 建议参考其他组件，例如 handsontable
