### ISSUE TITLE
怎么获序号值

### ISSUE THREAD

**Issue by lizhishuo** [x-extends/vxe-table#704]
第一列type=seq,我需要获取整个表格第一列的序号值，这个应该样获取

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by DoveAz** [comment]
序号不就是 第一行是1，第二行是2吗，这有啥好获取的

**Comment by lizhishuo** [comment]
我使用的是树结构，自动生序号后，要返回给后台，辛苦啦，真不知道怎么获取

**Comment by DoveAz** [comment]
目前似乎没有这样的方法，你只能自己重新计算了，像下面这样
```javascript
function c(list,parent){
         list.forEach((e,index)=>{
           if(parent){
             e.seq = parent.seq + '.' + (index + 1 )
           }else{
             e.seq = index + 1
           }
           if(e.children){
             c(e.children,e)
           }
         })
         return list
       }
c(this.tableData)

```

**Comment by lizhishuo** [comment]
> 目前似乎没有这样的方法，你只能自己重新计算了，像下面这样
> 
> ```js
> function c(list,parent){
>          list.forEach((e,index)=>{
>            if(parent){
>              e.seq = parent.seq + '.' + (index + 1 )
>            }else{
>              e.seq = index + 1
>            }
>            if(e.children){
>              c(e.children,e)
>            }
>          })
>          return list
>        }
> c(this.tableData)
> ```

好的，非常感谢您的方法

**Comment by ly1989abc** [comment]
> 我使用的是树结构，自动生序号后，要返回给后台，辛苦啦，真不知道怎么获取

API里有getRowIndex可用，需要传入该行的对象

**Comment by lizhishuo** [comment]
> API里有getRowIndex可用，需要传入该行的对象

getRowIndex获取到的不是自动生成的序号

**Comment by xlz26296** [comment]
还是头一次听说获取序号，不管前端还是后端，把数据遍历一下索引+1不就是序号

**Comment by ly1989abc** [comment]
> > API里有getRowIndex可用，需要传入该行的对象
> 
> getRowIndex获取到的不是自动生成的序号

既然你要返回后台使用了，为啥要前端自动生成，不应该使用后端自动生成的id吗
