### ISSUE TITLE
希望展开行收起时，可以根据需要阻止收起。

### ISSUE THREAD

**Issue by fls1215** [x-extends/vxe-table#705]
### （必填）这个需求解决了什么问题 What problem does this feature solve
我在展开行里写了表单，我需要在校验失败时阻止行收起，但现在没有办法阻止。

### （必填）建议的 API 是什么样的 What does the proposed API look like

希望出个方法，像上传前的校验一样，如果返回false,不进行收起动作。

### 是否已有其他不错的替代方案 Describe alternatives you've considered

没有，现在只能在提交时打开所有行再校验一次，体验不好。

重现地址
https://jsrun.pro/D3fKp/edit

**Comment by xuliangzhan** [comment]
可以考虑支持

**Comment by fls1215** [comment]
> 下版本可以考虑支持
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/expandIcon

非常感谢!我更新了之后有个问题，现在可以在参数里加上rowIndex吗？我需要获取当前行然后校验。麻烦了！
