### ISSUE TITLE
固定列时列内容显示空白

### ISSUE THREAD

**Issue by lgw8186** [x-extends/vxe-table#711]
固定列时列内容显示空白， 不显示 “”按钮1” “按钮2”
 ?

<template>
  <div class="mod-config">

      <vxe-table
          border
          resizable
          height="300"
          highlight-hover-row
          :data="tableData">
          <vxe-table-column type="seq" width="60" fixed="left"></vxe-table-column>
          <vxe-table-column field="name" title="Name" width="300"></vxe-table-column>
          <vxe-table-column field="role" title="Role" width="300"></vxe-table-column>
          <vxe-table-column field="sex" title="Sex" width="300"></vxe-table-column>
          <vxe-table-column field="date" title="Date" width="300"></vxe-table-column>
          <vxe-table-column title="操作" fixed="right" width="200">
            <template>
              <vxe-button type="text">按钮1</vxe-button>
              <vxe-button type="text">按钮2</vxe-button>
            </template>
          </vxe-table-column>
        </vxe-table>
</div>

</template>

<script>
  export default {
    data () {
      return {
        tableData: [{'name': 'name'}]
      }
    },
    created () {
    }
  }
</script>

  "vxe-table": "^2.7.24",
   "xe-utils": "^2.3.1",

**Comment by LudanArch** [comment]
用一个容器把这两个 vxe-button 包起来
