### ISSUE TITLE
v2.8.22以后的版本vxe-modal 的z-index有问题

### ISSUE THREAD

**Issue by tclqlove** [x-extends/vxe-table#718]
v2.8.24以后的版本vxe-modal 的z-index有问题，无法遮罩住别的元素,设置z-index属性也无效。同样的代码使用低版本(v2.8.22)vxe-table.js就不会出现此问题。

**Comment by ly1989abc** [comment]
> v2.8.24以后的版本vxe-modal 的z-index有问题，无法遮罩住别的元素,设置z-index属性也无效。同样的代码使用低版本(v2.8.22)vxe-table.js就不会出现此问题。

加上transfer就好了，作者没说明这个

**Comment by tclqlove** [comment]
> > v2.8.24以后的版本vxe-modal 的z-index有问题，无法遮罩住别的元素,设置z-index属性也无效。同样的代码使用低版本(v2.8.22)vxe-table.js就不会出现此问题。
> 
> 加上transfer就好了，作者没说明这个
加上之后真的解决了我的问题，实在太感谢你了！

**Comment by marissagroves** [comment]
怎么加呀？我加上也没用。。。
