### ISSUE TITLE
编辑行的blur事件，点击之后取到的row的数据更新了，但是直接调用row.XX的数据为上一次的值

### ISSUE THREAD

**Issue by fls1215** [x-extends/vxe-table#723]
### （必填）请填写问题描述 Describe the bug
大神啊！
这个情况直到前天都是好的，昨天就突然不行了，今天一看官网也这样了，怀疑人生了。
编辑行的blur事件，点击之后取到的row的数据更新了，但是直接调用row.XX的数据为上一次的值。

同时，上次问的希望[展开行收起时，可以根据需要阻止收起](https://github.com/xuliangzhan/vxe-table/issues/705)。这个问题还需要帮助，我需要取rowIndex的值，写在评论最后一条了。大神能不能给加上，拜托了！

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://jsrun.pro/bUfKp/edit

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/21237474/76921314-b117c000-6908-11ea-967c-d86189006211.png)

### （必填）请填写期望的结果 Expected behavior
希望直接调用属性的值也同时更新。

### （必填）请填写版本号 Version

- os:window
- browser: chrome
- vue: 2.6.11
- vxe-table:2.8.8

**Comment by xlz26296** [comment]
单元格编辑是不能使用 blur 事件的，应该设置为 [immediate](https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?filterName=immediate) 或者 [edit-closed](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=edit-closed) 事件
