### ISSUE TITLE
如何使内容在单元格内换行并且使用tooltip

### ISSUE THREAD

**Issue by nekorrrr** [x-extends/vxe-table#726]
### （必填）请填写问题描述 Describe

 > 现在有这样一个需求，有一段多行文本，要求在单元格内多行显示。
 > 并且超过三行的时候加上省略号，当鼠标放在单元格上的时候使用tooltip显示全部内容。
 > 如果要实现这个需求的话只能使用自定义模板进行换行加省略号的操作。
 > 但是这样的话tooltip的显示不知道该怎么做。
 > 有没有大神可以指导一下，给个思路。谢谢

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 > http://jsrun.pro/sUfKp/edit
 > 这个链接并不能重现问题，只能给个大致的架子。

### （必填）请填写版本号 Version

- os: win10 
- browser: firefox 74.0
- vue: v2.6.11
- vxe-table: v2.8.28

**Comment by wupeiwen233** [comment]
可以实现加tooltip  但是没办法判断文本是否溢出了吧  只能不管有没有溢出每个都加了
