### ISSUE TITLE
单元格渲染与行编辑同时存在

### ISSUE THREAD

**Issue by LiuduZero** [x-extends/vxe-table#727]
### （必填）请填写能重现问题的链接
https://jsrun.pro/F9fKp/edit

### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/24452177/77156093-9ea0b080-6ad9-11ea-8039-08cc36bb8e41.png)

### （必填）请填写版本号 Version
- os: macOs
- browser: chrome
- vue: 默认最新版本
- vxe-table: 默认最新版本

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下
