### ISSUE TITLE
格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常

### ISSUE THREAD

**Issue by chen3728060** [x-extends/vxe-table#733]
### （必填）请填写问题描述 Describe the bug

按照官方文档，局部format是正常的。但是全局format的mixin会发现
formatSex (**{ cellValue }**) {
   **console.log(cellValue) //得到的是undefined**
   return cellValue ? (cellValue === '1' ? '男' : '女') : ''
},

改为

formatSex (**cellValue** ) {
   **console.log(cellValue) //正常，得到单元格内的值，没有其他对象
   return cellValue ? (cellValue === '1' ? '男' : '女') : ''
},

### （必填）请填写能重现问题的链接，例如
官方文档
https://xuliangzhan_admin.gitee.io/vxe-table/v2/index.html#/table/base/format

### 填写报错信息或截图 Error message or screenshots

暂无

### （必填）请填写期望的结果 Expected behavior

 是bug还是我用法不对？

- vxe-table: 2.8.30

**Comment by chen3728060** [comment]
还有，jsrun.net 这个在线代码网站，挂了

**Comment by mylysddp** [comment]
你好，像请教下，我也是根据官方例子来写，但是在一开始调用VXETable.formats.add 的时候就提示找不到add、mixin 等参数，尝试着将console.log(VXETable) ,发现里面根本就没有formats 这个属性，是不是还需要安装什么插件。

**Comment by chen3728060** [comment]
不需要安装插件。应该是你写代码的位置不正确。你写在哪里？截图我看看------------------ 原始邮件 ------------------
发件人: "mylysddp"<notifications@github.com>
发送时间: 2020年3月26日(星期四) 上午9:37
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "chen3728060"<chen3728060@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)




 
你好，像请教下，我也是根据官方例子来写，但是在一开始调用VXETable.formats.add 的时候就提示找不到add、mixin 等参数，尝试着将console.log(VXETable) ,发现里面根本就没有formats 这个属性，是不是还需要安装什么插&#x4EF6;。
 
&mdash;

**Comment by yan695432** [comment]
> 你好，像请教下，我也是根据官方例子来写，但是在一开始调用VXETable.formats.add 的时候就提示找不到add、mixin 等参数，尝试着将console.log(VXETable) ,发现里面根本就没有formats 这个属性，是不是还需要安装什么插件。

我同样也遇到这样的情况，我将官方的代码放在main.js 里面 你解决了嘛？

**Comment by chen3728060** [comment]
你怎么写的mixin代码？截图看看

**Comment by yan695432** [comment]
![image](https://user-images.githubusercontent.com/51350693/77734357-7bc74c80-7043-11ea-97f9-25cf0f071e56.png)
我直接把网站上的代码贴到main.js

**Comment by yan695432** [comment]
![image](https://user-images.githubusercontent.com/51350693/77734407-97caee00-7043-11ea-8f7d-7004b7f1208b.png)
然后就会报错

**Comment by chen3728060** [comment]
能回复一个正常点的图片吗？用邮箱自带的，外部的图片，被qq过滤了····

**Comment by yan695432** [comment]
我是贴在main.js 里面，然后就会提示mixin是undefined


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen3728060"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午4:13
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"-.-"<125722066@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)





 能回复一个正常点的图片吗？用邮箱自带的，外部的图片，被qq过滤了····

**Comment by chen3728060** [comment]
那你试一下这样的顺序摆放代码。先不用add




import XEUtils from 'xe-utils'


import VXETable from 'vxe-table'
import 'vxe-table/lib/index.css'


Vue.use(VXETable)


//自定义全局的格式化处理函数
VXETable.formats.mixin({
	// 格式化真假
	formatTF(cellValue) {
		return cellValue === true ? '是' : '否'
	},

})

**Comment by yan695432** [comment]
也测试过了，也是不行的

**Comment by chen3728060** [comment]
你console.log(VxeTable)?mixin混入的时候，vue实例都还没创建，你打印啥呢？

**Comment by yan695432** [comment]
我没有console.log(VxeTable)，刚运行起来界面就一片空白，然后console里面就有这句话了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen3728060"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午4:28
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"-.-"<125722066@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)





 你console.log(VxeTable)?mixin混入的时候，vue实例都还没创建，你打印啥呢？

**Comment by chen3728060** [comment]
你的报错，应该不是main.js报的把？应该是你的业务页面报的吧？所以我问你，究竟你那些mixin代码，写哪里？

**Comment by yan695432** [comment]
我把main.js 里面的VXETable.formats.mixin({}) 代码去掉，就不会报错，其他地方都没有写mixin


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen3728060"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午4:33
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"-.-"<125722066@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)





 你的报错，应该不是main.js报的把？应该是你的业务页面报的吧？所以我问你，究竟你那些mixin代码，写哪里？

**Comment by chen3728060** [comment]
把你main js的代码复制给我看看

**Comment by yan695432** [comment]
import&nbsp;Vue&nbsp;from&nbsp;'vue'
import&nbsp;App&nbsp;from&nbsp;'./App.vue'
import&nbsp;router&nbsp;from&nbsp;'./router'
//&nbsp;vfd
import&nbsp;Antd&nbsp;from&nbsp;'ant-design-vue'
import&nbsp;'ant-design-vue/dist/antd.css'
import&nbsp;VueContextMenu&nbsp;from&nbsp;'vue-contextmenu'
import&nbsp;vcolorpicker&nbsp;from&nbsp;'vcolorpicker'
import&nbsp;'./plugins/element.js'
//&nbsp;导入字体图标
import&nbsp;'./assets/fonts/iconfont.css'
//&nbsp;导入全局样式表
import&nbsp;'./assets/css/global.css'
import&nbsp;'./assets/css/element-ui.css'
//&nbsp;加载公共组件
import&nbsp;plugins&nbsp;from&nbsp;'./components/index'
//&nbsp;导入axios
import&nbsp;axios&nbsp;from&nbsp;'axios'
import&nbsp;store&nbsp;from&nbsp;'./store'
//&nbsp;导入vxe-table
//&nbsp;import&nbsp;'xe-utils'
import&nbsp;XEUtils&nbsp;from&nbsp;'xe-utils'
import&nbsp;VXEUtils&nbsp;from&nbsp;'vxe-utils'
import&nbsp;VXETable&nbsp;from&nbsp;'vxe-table'
import&nbsp;'vxe-table/lib/index.css'
//&nbsp;v-charts
import&nbsp;VCharts&nbsp;from&nbsp;'v-charts'
//&nbsp;全局配置变量、方法
import&nbsp;globalFuncVariable&nbsp;from&nbsp;'@/uitls/index.js'
//&nbsp;导入md5.js
import&nbsp;Md5&nbsp;from&nbsp;'@/uitls/md5.js'
//&nbsp;本机设置基础URL
axios.defaults.baseURL&nbsp;=&nbsp;'http://localhost:5555'
Vue.prototype.$http&nbsp;=&nbsp;axios

//&nbsp;是否有请求在刷新token
window.isRefreshing&nbsp;=&nbsp;false
//&nbsp;被挂起的请求数组
let&nbsp;subscribesArr&nbsp;=&nbsp;[]

//&nbsp;push所有请求到数组中
function&nbsp;subscribeTokenRefresh(cb)&nbsp;{
&nbsp;&nbsp;subscribesArr.push(cb)
}

//&nbsp;用新token发起请求
function&nbsp;reloadSubscribesArr(token)&nbsp;{
&nbsp;&nbsp;subscribesArr.map(cb&nbsp;=&gt;&nbsp;cb(token))
}

/**
&nbsp;*&nbsp;快过期了&nbsp;和&nbsp;已经过期了
&nbsp;*&nbsp;@returns&nbsp;{boolean}
&nbsp;*/
function&nbsp;isTokenExpired()&nbsp;{
&nbsp;&nbsp;let&nbsp;expiredTime&nbsp;=&nbsp;store.state.expirationTime
&nbsp;&nbsp;if&nbsp;(expiredTime)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;nowTime&nbsp;=&nbsp;new&nbsp;Date().getTime()
&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;willExpired&nbsp;=&nbsp;(expiredTime&nbsp;-&nbsp;nowTime)&nbsp;/&nbsp;1000&nbsp;<&nbsp;10&nbsp;*&nbsp;60
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;willExpired
&nbsp;&nbsp;}
&nbsp;&nbsp;return&nbsp;false
}

function&nbsp;directLogin()&nbsp;{
&nbsp;&nbsp;router.push('/Login')
}

//&nbsp;http&nbsp;request&nbsp;请求拦截器
axios.interceptors.request.use(
&nbsp;&nbsp;config&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(config.headers.loading&nbsp;===&nbsp;undefined&nbsp;||&nbsp;config.headers.loading&nbsp;===&nbsp;true)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;store.dispatch('showloader')
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;config.headers.Authorization&nbsp;=&nbsp;'Bearer&nbsp;'&nbsp;+&nbsp;store.state.accessToken
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;return&nbsp;config
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;//&nbsp;如果是不需要token的接口直接返回即可
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(config.url.startsWith('/login')&nbsp;||&nbsp;config.url&nbsp;===&nbsp;'/login'&nbsp;||&nbsp;config.url&nbsp;===&nbsp;'/refresh-token')&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;config
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;获取token
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;token&nbsp;=&nbsp;store.state.accessToken
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;如果token存在，首先校验是否已经过期，如果已经过期，跳转到登录页面
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(token)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;refreshToken&nbsp;=&nbsp;store.state.refreshToken
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(isTokenExpired()&nbsp;&amp;&amp;&nbsp;config.url&nbsp;!==&nbsp;'/refresh-token')&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!window.isRefreshing)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window.isRefreshing&nbsp;=&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axios.post('/refresh-token',&nbsp;{&nbsp;accessToken:&nbsp;token,&nbsp;refreshToken:&nbsp;refreshToken&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.then(({&nbsp;data:&nbsp;res&nbsp;})&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window.isRefreshing&nbsp;=&nbsp;false
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(res.isSuccess)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;tokenVo&nbsp;=&nbsp;res.data
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;store.commit('set_accessToken',&nbsp;tokenVo)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reloadSubscribesArr(tokenVo)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;else&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;subscribesArr&nbsp;=&nbsp;[]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window.localStorage.clear()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directLogin()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.catch(()&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window.isRefreshing&nbsp;=&nbsp;false
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;subscribesArr&nbsp;=&nbsp;[]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window.localStorage.clear()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directLogin()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;retry&nbsp;=&nbsp;new&nbsp;Promise((resolve,&nbsp;reject)&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;subscribeTokenRefresh((newToken)&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;config.headers.Authorization&nbsp;=&nbsp;`Bearer&nbsp;${newToken}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolve(config)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;retry
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;else&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;config.headers.Authorization&nbsp;=&nbsp;`Bearer&nbsp;${token}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;config
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;else&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directLogin()
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;},
&nbsp;&nbsp;err&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Promise.reject(err)
&nbsp;&nbsp;}
)

//&nbsp;设置全局的请求次数，请求的间隙
axios.defaults.retry&nbsp;=&nbsp;4
axios.defaults.retryDelay&nbsp;=&nbsp;1000

axios.interceptors.response.use(function&nbsp;(response)&nbsp;{
&nbsp;&nbsp;store.dispatch('hideloader')
&nbsp;&nbsp;return&nbsp;response
},&nbsp;function&nbsp;axiosRetryInterceptor(err)&nbsp;{
&nbsp;&nbsp;var&nbsp;config&nbsp;=&nbsp;err.config
&nbsp;&nbsp;//&nbsp;If&nbsp;config&nbsp;does&nbsp;not&nbsp;exist&nbsp;or&nbsp;the&nbsp;retry&nbsp;option&nbsp;is&nbsp;not&nbsp;set,&nbsp;reject
&nbsp;&nbsp;if&nbsp;(!config&nbsp;||&nbsp;!config.retry)&nbsp;return&nbsp;Promise.reject(err)

&nbsp;&nbsp;//&nbsp;Set&nbsp;the&nbsp;variable&nbsp;for&nbsp;keeping&nbsp;track&nbsp;of&nbsp;the&nbsp;retry&nbsp;count
&nbsp;&nbsp;config.__retryCount&nbsp;=&nbsp;config.__retryCount&nbsp;||&nbsp;0

&nbsp;&nbsp;//&nbsp;Check&nbsp;if&nbsp;we've&nbsp;maxed&nbsp;out&nbsp;the&nbsp;total&nbsp;number&nbsp;of&nbsp;retries
&nbsp;&nbsp;if&nbsp;(config.__retryCount&nbsp;&gt;=&nbsp;config.retry)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Reject&nbsp;with&nbsp;the&nbsp;error
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Promise.reject(err)
&nbsp;&nbsp;}

&nbsp;&nbsp;//&nbsp;Increase&nbsp;the&nbsp;retry&nbsp;count
&nbsp;&nbsp;config.__retryCount&nbsp;+=&nbsp;1

&nbsp;&nbsp;//&nbsp;Create&nbsp;new&nbsp;promise&nbsp;to&nbsp;handle&nbsp;exponential&nbsp;backoff
&nbsp;&nbsp;var&nbsp;backoff&nbsp;=&nbsp;new&nbsp;Promise(function&nbsp;(resolve)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(function&nbsp;()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolve()
&nbsp;&nbsp;&nbsp;&nbsp;},&nbsp;config.retryDelay&nbsp;||&nbsp;1)
&nbsp;&nbsp;})

&nbsp;&nbsp;//&nbsp;Return&nbsp;the&nbsp;promise&nbsp;in&nbsp;which&nbsp;recalls&nbsp;axios&nbsp;to&nbsp;retry&nbsp;the&nbsp;request
&nbsp;&nbsp;return&nbsp;backoff.then(function&nbsp;()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;axios(config)
&nbsp;&nbsp;})
})
//&nbsp;设置请求超时时间
axios.defaults.timeout&nbsp;=&nbsp;60000
Vue.config.productionTip&nbsp;=&nbsp;false

VXETable.setup({
&nbsp;&nbsp;//&nbsp;表格的全局参数
&nbsp;&nbsp;size:&nbsp;'mini',
&nbsp;&nbsp;border:&nbsp;true,
&nbsp;&nbsp;resizable:&nbsp;true,
&nbsp;&nbsp;highlightCurrentRow:&nbsp;true,
&nbsp;&nbsp;highlightHoverRow:&nbsp;true
})

//&nbsp;自定义全局的格式化处理函数
VXETable.formats.mixin({
&nbsp;&nbsp;//&nbsp;格式化性别
&nbsp;&nbsp;formatSex({&nbsp;cellValue&nbsp;})&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cellValue&nbsp;?&nbsp;(cellValue&nbsp;===&nbsp;'1'&nbsp;?&nbsp;'男'&nbsp;:&nbsp;'女')&nbsp;:&nbsp;''
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;格式化下拉选项
&nbsp;&nbsp;formatSelect({&nbsp;cellValue&nbsp;},&nbsp;list)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;item&nbsp;=&nbsp;list.find(item&nbsp;=&gt;&nbsp;item.value&nbsp;===&nbsp;cellValue)
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;item&nbsp;?&nbsp;item.label&nbsp;:&nbsp;''
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;格式化日期，默认&nbsp;yyyy-MM-dd&nbsp;HH:mm:ss
&nbsp;&nbsp;formatDate({&nbsp;cellValue&nbsp;},&nbsp;format)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;XEUtils.toDateString(cellValue,&nbsp;format&nbsp;||&nbsp;'yyyy-MM-dd&nbsp;HH:mm:ss')
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;格式金额，默认2位数
&nbsp;&nbsp;formatAmount({&nbsp;cellValue&nbsp;},&nbsp;digits)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;XEUtils.commafy(cellValue,&nbsp;{&nbsp;digits:&nbsp;digits&nbsp;||&nbsp;2&nbsp;})
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;格式化银行卡，默认每4位隔开
&nbsp;&nbsp;formatBankcard({&nbsp;cellValue&nbsp;})&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;XEUtils.commafy(cellValue,&nbsp;{&nbsp;spaceNumber:&nbsp;4,&nbsp;separator:&nbsp;'&nbsp;'&nbsp;})
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;四舍五入,默认两位数
&nbsp;&nbsp;formatFixedNumber({&nbsp;cellValue&nbsp;},&nbsp;digits)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;XEUtils.toNumber(cellValue).toFixed(digits&nbsp;||&nbsp;2)
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;截取小数,默认两位数
&nbsp;&nbsp;formatCutNumber({&nbsp;cellValue&nbsp;},&nbsp;digits)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;XEUtils.toFixedString(cellValue,&nbsp;digits&nbsp;||&nbsp;2)
&nbsp;&nbsp;},
&nbsp;&nbsp;//&nbsp;转换&nbsp;moment&nbsp;类型为字符串
&nbsp;&nbsp;toMomentString(cellValue,&nbsp;format)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cellValue&nbsp;?&nbsp;cellValue.format(format)&nbsp;:&nbsp;''
&nbsp;&nbsp;}
})
//&nbsp;注意必须在构建Vue实例之前就将需要的组件注册进去
Vue.use(plugins)
//&nbsp;使用vxe-table
Vue.use(VXETable)
Vue.use(VXEUtils,&nbsp;XEUtils)
//&nbsp;vfd
Vue.use(Antd)
Vue.use(VueContextMenu)
Vue.use(vcolorpicker)
//&nbsp;引用全局方法
Vue.use(globalFuncVariable)
//&nbsp;//&nbsp;引用md5
Vue.prototype.$md5&nbsp;=&nbsp;Md5
//&nbsp;VCharts
Vue.use(VCharts)
new&nbsp;Vue({
&nbsp;&nbsp;router,
&nbsp;&nbsp;store,
&nbsp;&nbsp;render:&nbsp;h&nbsp;=&gt;&nbsp;h(App)
}).$mount('#app')







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen3728060"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午4:40
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"-.-"<125722066@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)





 把你main js的代码复制给我看看

**Comment by chen3728060** [comment]
跟我代码也差不多，那你要问问作者了，我暂时解答不了

**Comment by yan695432** [comment]
ok，我在找下原因，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen3728060"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午4:49
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"-.-"<125722066@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] 格式化列，使用全局化mixin，发现{CellValue}是undefined，去掉{}才正常 (#733)





 跟我代码也差不多，那你要问问作者了，我暂时解答不了
