### ISSUE TITLE
通过键盘导航到某个有值的单元格，按任意键会将被禁用的单元格数据置为空

### ISSUE THREAD

**Issue by monkey926** [x-extends/vxe-table#740]
### （必填）请填写问题描述 Describe the bug
index.umd.js第12532行先将单元格置为空，再调用handleActived()方法判断是否禁用编辑。正常逻辑应该先判断是否可编辑，再决定是否置为空。
![image](https://user-images.githubusercontent.com/33092695/77615379-2d924a80-6f6a-11ea-9e85-adf9c34af7b7.png)
![image](https://user-images.githubusercontent.com/33092695/77615496-81049880-6f6a-11ea-84b2-1e3806dfa1e6.png)

### （必填）请填写期望的结果 Expected behavior
希望此处能按如下步骤：
1.检查单元格是否可编辑
2.如果可编辑，则触发edit-actived事件，得到被覆盖之前的数据
3.覆盖数据

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.8.31

**Comment by adoniscyz** [comment]
同样的问题,  是否可增加一个配置,  是否需要默认清空列值

**Comment by adoniscyz** [comment]
可通过 keyboard-config    editMethod属性 重写默认的行为
