### ISSUE TITLE
vxe-table列虚拟滚动实现原理

### ISSUE THREAD

**Issue by livelyPeng** [x-extends/vxe-table#749]
### 请填写问题描述 Describe

?

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by mpz4life** [comment]
分组表头列虚拟，是否可以这样考虑？
在获取tableFullColumn时，就装配好每个叶子节点对应的树的最左叶子节点索引、最右叶子节点索引，以及根节点在collectColumns中索引。然后每次滚动时渲染完整的分组表头及数据
