### ISSUE TITLE
两个列使用同一个自定义的Filter出现污染问题

### ISSUE THREAD

**Issue by tuxming** [x-extends/vxe-table#750]
### （必填）请填写问题描述 Describe the bug

使用了这个FilterContent.vue， 同一个table使用了两个一样的FilterContent,

当我点击第一个后，再点击第二个，显示的列表还是第一个的Filter列表。

https://github.com/xuliangzhan/vxe-table/blob/master/examples/plugins/xtable/renderer/components/FilterContent.vue

使用方式： 
直接使用了这个文件，然后在main.js里面注入： VXETable.renderer.add('FilterContent'{});
```html
<vxe-table-column field="created" :title="msg('建单时间')" min-width="120" 
    sortable :filters="[{data: {vals: [], sVal: ''}}]" :filter-render="{name: 'FilterContent'}" >
</vxe-table-column>

<vxe-table-column field="shopOwner" :title="msg('店铺')" min-width="120" 
     sortable :filters="[{data: {vals: [], sVal: ''}}]" :filter-render="{name: 'FilterContent'}"
></vxe-table-column>
```
我点击第一个Filter后，会出现列表，然后点击第二个Filter， 出现的还是第一个的列表。

请问如何解决？

**Comment by mengqingmeng** [comment]
我也遇到这个问题，请问如何解决的

**Comment by quietdw** [comment]
加一个 key
```
renderFilter: (h, renderOpts, params) => [
    <filter-content key={params.columnIndex} params={params}></filter-content>
  ]
```
