### ISSUE TITLE
导出没有反应

### ISSUE THREAD

**Issue by MaDCen** [x-extends/vxe-table#752]
### （必填）请填写问题描述 Describe the bug
导出没有反应
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link
    this.$refs[tableName].openExport({ types: ['csv'] })
 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: 谷歌
- vue:     "vue": "2.6.10",
-     "vxe-table": "^2.8.33",

**Comment by MaDCen** [comment]
openExport(options) | 调用这个方法没有反应

**Comment by liangxp** [comment]
遇到同样的问题，不知道兄弟得到解决没有！

**Comment by Rexes** [comment]
解决了吗？   同样的问题  无法导出了！

**Comment by Rexes** [comment]
xuliang大神不知道可否拉个qq群进行建设维护？ 方便大家交流

**Comment by zhangchenna** [comment]
同求
