### ISSUE TITLE
定时更新列表数据，页面不在前端，会导致固定列空白

### ISSUE THREAD

**Issue by LudanArch** [x-extends/vxe-table#757]
### （必填）请填写问题描述 Describe the bug
问题复现条件：
1，setTimeout（6s更新一次）更新列表数据（:data=data 或者 loadData 都会出现问题）
2，页面不在前端（document.visibilityState 为hidden）
3，列表不在第一行（scrollTop 大于0）
4，过段时间（大概3-5分钟）切回页面（document.visibilityState 为visible）

### 填写报错信息或截图 Error message or screenshots

无报错，页面会自动回滚到第一行，固定列会变空白

### （必填）请填写版本号 Version

- os: win10
- browser: chrome 80.0.3987.122
- vue: 2.6.10
- vxe-table: 2.8.33

**Comment by woshicezai** [comment]
我也有同样的问题，正在看源码，定位。
