### ISSUE TITLE
 树形表格+斑马线条纹，显示错误

### ISSUE THREAD

**Issue by natee** [x-extends/vxe-table#761]
### （必填）请填写问题描述 Describe the bug

  树形表格+斑马线条纹，只有前两行背景色显示正常，之后的都识别成了 stripe 样式

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 http://jsrun.net/rxfKp/edit

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/4928035/78650251-3e8b7600-78f1-11ea-923c-8e554eb30f4a.png)

### （必填）请填写期望的结果 Expected behavior

 正确显示斑马条纹

### （必填）请填写版本号 Version

- os: Mac
- browser: Chrome
- vue: 2.6
- vxe-table: 2.8.31

**Comment by xuliangzhan** [comment]
树结构是不支持斑马线条纹的，你可以通过样式去实现
