### ISSUE TITLE
在展开行事件toggleMethod 中完成异步再返回return，不能起作用了

### ISSUE THREAD

**Issue by fls1215** [x-extends/vxe-table#767]
### （必填）请填写问题描述 Describe
我在展开行关闭时，需要进行数据校验，当我校验完再返回时，toggleMethod 似乎已经没有作用了，无论return什么，都无法关闭展开的行。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/HHfKp/edit

### 请填写报错信息或截图 Error message or screenshots

他就是接收不到我的信号了，不听话了。

### （必填）请填写版本号 Version

- os: windows
- browser: chrome
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
toggleMethod 是同步的，异步可以通过 toggle-row-expand 事件处理 http://jsrun.net/P5fKp/edit

**Comment by fls1215** [comment]
> toggleMethod 是同步的，异步可以通过 toggle-row-expand 事件处理 http://jsrun.net/P5fKp/edit
重新打开我需要重新校验数据，现在需要校验两遍，最好是别关闭。
