### ISSUE TITLE
showOverflow 在elementui的el-drawer 和 el-dialog上 hover无效

### ISSUE THREAD

**Issue by harryhan1989** [x-extends/vxe-table#773]
showOverflow 在elementui的el-drawer 和 el-dialog上 hover无效，猜测应该跟z-index有关，估计需要动态计算或者hover组件需要基于grid定位

**Comment by harryhan1989** [comment]
临时解决方案，VXETable.setup({
  zIndex: 3000, // 设置高点
})

**Comment by wen403** [comment]
el-drawer 和 el-dialog的z-index到了临界值就会有问题，这就是一个bug
