### ISSUE TITLE
分组表头 列固定时 fixed right 与 fixed left  出现异常

### ISSUE THREAD

**Issue by LiuduZero** [x-extends/vxe-table#780]
### （必填）请填写问题描述 Describe

分组列固定时 在列的最后一项设置 fixed='right'，再在前一项设置 fixed='left'，出现异常

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/pBfKp/edit

### 请填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/24452177/79410857-0c0a0900-7fd4-11ea-8b7f-7a778b5b4b14.png)
![image](https://user-images.githubusercontent.com/24452177/79410879-1926f800-7fd4-11ea-9320-5e646c7178c1.png)

### （必填）请填写版本号 Version

- os: windows
- browser: chrome
- vue: vxe文档在线运行代码时的版本
- vxe-table: vxe文档在线运行代码时的版本

**Comment by LiuduZero** [comment]
实际使用时还会出现
![image](https://user-images.githubusercontent.com/24452177/79411003-5b503980-7fd4-11ea-8b9d-a1490af55215.png)

**Comment by xuliangzhan** [comment]
旧版本：固定列必须要放在左右两侧 http://jsrun.net/DBfKp/edit
v2.9.3+：支持任意位置分组固定列 http://jsrun.net/HBfKp/edit

**Comment by LiuduZero** [comment]
谢谢，v2.9.3-beta.0 可以解决

**Comment by LiuduZero** [comment]
> 旧版本：固定列必须要放在左右两侧 http://jsrun.net/DBfKp/edit
> v2.9.3+：分组固定列不限制位置 http://jsrun.net/HBfKp/edit

使用 vxe-grid 时这个问题还是存在
http://jsrun.net/pBfKp/edit
这里添加了 自定义 锁定列与方向的按钮，供测试

**Comment by xlz26296** [comment]
建议先去看看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/group

**Comment by LiuduZero** [comment]
> 建议先去看看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/group

thanks ，之前没看到这个方法，还以为直接修改的

**Comment by LiuduZero** [comment]
> 建议先去看看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/group

而且 vxe-table 要用最新的 @2.9.3-beta.0  版本
