### ISSUE TITLE
当table里的数据被删空时，新插入的行随着最后一条非新增行数据的删除一起删掉了。

### ISSUE THREAD

**Issue by fls1215** [x-extends/vxe-table#782]
### （必填）请填写问题描述 Describe the bug
 
删除行时同时删除数据，当tableData的最后一条数据被删除时，所有的新增行都不见了。表格变成了暂无数据。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/2BfKp/edit

### 填写报错信息或截图 Error message or screenshots
没有数据了。

### （必填）请填写期望的结果 Expected behavior

希望只有插入行的时候，也能显示。

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: 2.8.28

**Comment by xuliangzhan** [comment]
一旦要自动操作 data 那么就是放弃表格内置的 CRUD 管理，这是取舍问题，所有增删改逻辑你应该自行通过 data 去控制

**Comment by fls1215** [comment]
> 一旦操作了 data 那么就必须放弃内置的 CRUD 管理，data 的操作与内置 CRUD 管理你只能选择一种方式，这是取舍问题。
> 使用内置的 CRUD 管理：不允许操作 data
> 放弃内置的 CRUD 管理：不能调用相关方法，好处是可以对 data 数据的操作更加自由，做更多的自定义业务逻辑

好的，解决了。
