### ISSUE TITLE
表格内的日历样式和网站上的样式不一样，请问怎么使用网站上的日历样式？

### ISSUE THREAD

**Issue by fls1215** [x-extends/vxe-table#784]
### （必填）请填写问题描述 Describe

表格内的日历样式和网站上的样式不一样，请问怎么使用网站上的日历样式？
另外，editRender里,name为input和$input有什么区别，我使用$input，日历就不出来了。
当type为month时能不能不要显示天，直接选择月份？

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/gRfKp/edit

希望是这样的样式
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/input
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/manual

应该怎么设置呢？

### 请填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/21237474/79530122-03333900-80a1-11ea-8cc0-f03a075f7936.png)
希望是这样的
![image](https://user-images.githubusercontent.com/21237474/79530143-1ba35380-80a1-11ea-86be-f5ce2c6061ca.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table:2.8.28

**Comment by LiuduZero** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/manual
![image](https://user-images.githubusercontent.com/24452177/79539095-3b924180-80b8-11ea-9797-72cbcab6ac75.png)

这两个渲染组件不一样的，文档中有示例

**Comment by fls1215** [comment]
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/manual
> ![image](https://user-images.githubusercontent.com/24452177/79539095-3b924180-80b8-11ea-9797-72cbcab6ac75.png)
> 
> 这两个渲染组件不一样的，文档中有示例
感谢回复，但我不是很懂啊，哪里不一样呢，即使是这个例子在线运行也是和网站样式不一样的呀！

**Comment by LiuduZero** [comment]
http://jsrun.net/NRfKp/edit

**Comment by fls1215** [comment]
> http://jsrun.net/NRfKp/edit

感谢！我终于知道为什么我用$input不好使了，element的弹框z-index比他高，盖住了它……
