### ISSUE TITLE
大数据列表虚拟滚动条，固定列，实现合并行后，固定列数据显示空白。

### ISSUE THREAD

**Issue by shawon1220** [x-extends/vxe-table#785]
### （必填）请填写问题描述 Describe

 大数据列表虚拟滚动条，固定列，实现合并行后，固定列数据显示空白。

### 请填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/10345404/79542340-0be63800-80be-11ea-97fd-6aaddb228be9.png)

### （必填）请填写版本号 Version
- vue: 2.6.11
- vxe-table: 3.x

**Comment by Chenhuif** [comment]
请问您这个问题现在解决了嘛，我也遇到了同样的问题

**Comment by xuliangzhan** [comment]
虚拟滚动不支持 span-method、footer-span-method 参数，请谨慎使用

**Comment by LiSiQinF** [comment]
最后有解决方案吗？
