### ISSUE TITLE
键盘导航失效

### ISSUE THREAD

**Issue by woshihanbao** [x-extends/vxe-table#787]
### （必填）请填写问题描述 Describe the bug

1、点击新增，默认选中单元格时（调用setActiveCell），键盘导航失效，按tab不能切换到下一个单元格。
当鼠标左键单击单元格时，键盘导航才重新生效。

2、希望键盘导航可编辑下拉框

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://jsfiddle.net/kLsg2ebz/1/

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/32451122/79629596-e3297580-8185-11ea-94d6-defe7662e5ee.png)

### （必填）请填写期望的结果 Expected behavior

如何让键盘导航生效，或如何模拟点击事件。

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.1
- vxe-table: 2.9.2

**Comment by xuliangzhan** [comment]
该问题会在 2.9.3+ 中修复
https://jsfiddle.net/tj45vxso/

**Comment by woshihanbao** [comment]
> 该问题会在 2.9.3+ 中修复
> https://jsfiddle.net/dub8t0Lf/

还有两点不知道是不是问题
1、你现在的2.9.3，mode改为row之后，键盘导航失效。
2、当前稳定版2.9.2，键盘导航无法进入下拉框。table中的下拉框只能手动点击编辑
