### ISSUE TITLE
vxe-toolbar无法通过$parent获取$xetable

### ISSUE THREAD

**Issue by akria00** [x-extends/vxe-table#788]
### （必填）这个需求解决了什么问题 What problem does this feature solve

vxe-toolbar 与 vxe-table 不是父子关系的时候 无法通过updateConf获取this.$xetable
来获取列字段信息

### 建议的 API 是什么样的 What does the proposed API look like

希望能够指定设置$xetable

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
你的这种用法，工具栏和表格已经不属于同一级组件了，表格已经被你用插槽放入el-main组件中，你这种情况就无法用工具栏了，得自己去实现了

**Comment by akria00** [comment]
> 你的这种用法，工具栏和表格已经不属于同一级组件了，表格已经被你用插槽放入el-main组件中，内置的工具栏和表格只能是一套组合，你这种情况就无法用工具栏了，得自己去实现了

目前只能手工实现 T T
```
    this.$refs.userToolbar.$xegrid = this.$refs.table
    this.$refs.table.connect({ toolbar: this.$refs.userToolbar })
    this.$refs.userToolbar.restoreCustomStorage()
    this.custom = true
```
但我更希望能够有其他方式来代替this.$parent来找$table

**Comment by xuliangzhan** [comment]
最新版是可以支持工具栏任意位置，建议更新到最新版本试下 http://jsrun.net/mY2Kp/edit
