### ISSUE TITLE
筛选按钮无法弹出输入框

### ISSUE THREAD

**Issue by karenali** [x-extends/vxe-table#792]
### （必填）请填写问题描述 Describe

使用vxe-grid发现tableColumn超过60个，scrollbar**滑至后面栏位时**，点击筛选按钮无法弹出输入框

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://jsfiddle.net/vxa0zp5h/4/
(范例放了61个object)

### 请填写报错信息或截图 Error message or screenshots

 
![圖片](https://user-images.githubusercontent.com/29136484/79830680-84a80580-83d8-11ea-8119-b058e797eeb8.png)

 **Error in nextTick: "TypeError: filterWrapper is undefined"**
![圖片](https://user-images.githubusercontent.com/29136484/79830760-b28d4a00-83d8-11ea-9f10-a62c240b6ac1.png)

### （必填）请填写版本号 Version

- os: windows7
- browser: firefox
- vue: 2.6.10
- vxe-table: 2.9.0

**Comment by xuliangzhan** [comment]
筛选报错问题会在 2.9.3+ 中修复 https://jsfiddle.net/rpu3tzxs/
