### ISSUE TITLE
vxe-grid 方式：树表格的移动，无法移动到第3层之下

### ISSUE THREAD

**Issue by bookser** [x-extends/vxe-table#797]
### （必填）请填写问题描述 Describe the bug
按照https://xuliangzhan_admin.gitee.io/vxe-table/#/table/other/sortableRow
例子，使用vxe-grid 方式：树表格移动，1、2层的移动是正常的，但将一个节点移动到第三层时就不行了，且移动时指向不清晰，是移动到之下或之上，还是之内，很难从操作效果上分辨出来；整体是个非常强的组件，希望下一版本对树型有改进。

目前跟换 https://www.mofazhuan.com/31.html
使用，虽然效果也不好，但指向非常清晰，能满足基本需求先。

### （必填）请填写版本号 Version
- os: win10
- browser: chrome 78、Firefox 75
- vue: @vue/cli 4.3.1
- vxe-table: 2.9.2

**Comment by xlz26296** [comment]
该表格从始至终都没说过会支持拖拽，示例只是用第三方的 sortablejs 库演示而已吧
