### ISSUE TITLE
你好，请问怎么把这个组件下载到本地使用

### ISSUE THREAD

**Issue by abcdisgreat** [x-extends/vxe-table#803]
### （必填）请填写问题描述 Describe

 我想在一个简单的html里引入这个组件，它只加载本地js文件，不通过cdn引入，请问要下载哪些到本地

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
这个问题很蠢，你既然都知道 cdn 可以引入，那就把 cdn 的js文件下到你本地啊
