### ISSUE TITLE
太过频繁的更改属性定义，造成每次升级都面临各种不确定问题，这点非常不友好

### ISSUE THREAD

**Issue by harryhan1989** [x-extends/vxe-table#805]
### 请填写问题描述 Describe

太过频繁的更改属性定义，造成每次升级都面临各种不确定问题，这点非常不友好希望开发者在做重构时考虑一个产品的升级平稳性。
一般一个大版本的属性不宜大动，升级大版本可以大改，不过最好考虑一下改动的必要性和价值。感觉最近的改动非但没给grid组件带来好的使用体验，反而感觉一些实用功能在减少。

**Comment by xuliangzhan** [comment]
抱歉，api 的变动只为更好的优化，一般情况下都会最大程度的保留向下兼容（极少数情况除外），普遍情况下属性变动都可以通过全局参数设置一下就行，具体[变更日志](https://github.com/xuliangzhan/vxe-table/issues/712)都会说明

**Comment by jianliulin** [comment]
每次变更都让vxe-table更优秀，变更是值得的！！

**Comment by natee** [comment]
同样不建议过于频繁调整dom+css,并不是每个版本都会升级,但现状是一旦升级,或多或少会有些地方得重写.
比如表头增加了`white-space: pre-line;`这样的改动,这意味着表头使用如下修改显示**换行**,不符合预期:
```
<template v-slot:header="{ column }">
      {{ column.title }}
     <span>test</span>
     <icon></icon>
</template>
```

**Comment by xlz26296** [comment]
> 同样不建议过于频繁调整dom+css,并不是每个版本都会升级,但现状是一旦升级,或多或少会有些地方得重写.
> 比如表头增加了`white-space: pre-line;`这样的改动,这意味着表头使用如下修改显示**换行**,不符合预期:
> 
> ```
> <template v-slot:header="{ column }">
>       {{ column.title }}
>      <span>test</span>
>      <icon></icon>
> </template>
> ```

建议少用 TextNode，使用有意义的标签比较合适
```
<template v-slot:header="{ column }">
     <span>{{ column.title }}</span>
     <span>test</span>
     <icon></icon>
</template>
```
