### ISSUE TITLE
在表头分组的情况下的键盘导航

### ISSUE THREAD

**Issue by kagaku** [x-extends/vxe-table#808]
### （必填）请填写问题描述 Describe the bug
在表头分组的情况下，如果设置键盘导航，则右侧方向键按下后，出现的位置不是预想位置
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 [jsrun](http://jsrun.net/Jy2Kp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/29922799/80866535-c599f700-8cc1-11ea-8113-28a1de8424ee.png)

### （必填）请填写期望的结果 Expected behavior

 希望右侧方向键按下后，右侧的方格被选中

### （必填）请填写版本号 Version

- os: Mac 10.12.6
- browser: chrome 79
- vue: 2.6.10
- vxe-table: 2.9.2

**Comment by xuliangzhan** [comment]
该问题会在 2.9.6+ 修复 http://jsrun.net/jy2Kp/edit
