### ISSUE TITLE
 vxe grid 怎么获取表格所有数据，包括用insert_actived新增进去的

### ISSUE THREAD

**Issue by DaYuan08** [x-extends/vxe-table#813]
### （必填）请填写问题描述 Describe
就我用 vxe grid 的toolbar来配置工具栏，加了几个按钮，用insert_actived进行新增，想获取表格的数据但是找不到方法，用data绑定了也没用?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.6.10?
- vxe-table:^2.9.6 ?

**Comment by huoshidehua** [comment]
api 搜索fulldata
