### ISSUE TITLE
是否可增加一个表格下拉选 编辑器，如动图所示。

### ISSUE THREAD

**Issue by uzyapp** [x-extends/vxe-table#814]
### （必填）这个需求解决了什么问题 What problem does this feature solve?
项目中需要用到可编辑表格，编辑器为表格下拉选。
动图效果是从别的网站项目中看到的，是否可增加一个类似的表格下拉选 编辑器？
实现效果：
1.单元格获得焦点后，显示表格下拉选，选择下拉选中某条数据，返回这条数据到可编辑表格中。
2.在可编辑表格中，手动输入可自动匹配下拉选表格中的数据，按回车键返回匹配的第一条数据到可编辑表格中。
3.表格下拉选编辑器，后边有“选择”按钮，单击选择按钮可以弹出窗口进行选择。
[点击查看GIF效果](http://static.giteasy.cn/GIF%202020-05-08%2013-10-54.gif)

### （必填）请填写问题链接来描述为什么无法实现该功能，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link
 ?

### 建议的 API 是什么样的 What does the proposed API look like ?
[点击查看GIF效果](http://static.giteasy.cn/GIF%202020-05-08%2013-10-54.gif)

### 是否已有其他不错的替代方案 Describe alternatives you've considered
目前项目使用的是EasyUi，其中可实现类似的功能。但是效率太慢，太笨重，且UI不太美观。
打算替换掉Easyui，所以了解到了此项目。

**Comment by xlz26296** [comment]
使用渲染器添加一个自定义组件就可以了

**Comment by jianliulin** [comment]
> 使用渲染器添加一个自定义组件就可以了

我也有这样的需求，但就是没有这样的水平，你能否做一个简单的贡献出来？

**Comment by huoshidehua** [comment]
这个功能太需要了吧

**Comment by huoshidehua** [comment]
请问在哪个网站看到的这个功能

**Comment by xuliangzhan** [comment]
如果有空的话再给你们写几个渲染器的示例 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/edit

**Comment by uzyapp** [comment]
> 请问在哪个网站看到的这个功能

在一个在线进销存系统中看到的
https://jxc.ningmengyun.com/w/scm.aspx

**Comment by uzyapp** [comment]
> 如果有空的话再给你们写几个渲染器的示例 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/edit

这个可以

**Comment by zhang5707** [comment]
为什么表格下拉渲染器，表格行高会被下拉容器撑开

**Comment by zhang5707** [comment]
![image](https://user-images.githubusercontent.com/33337464/83838559-26d34100-a72c-11ea-8b5f-db350577b92a.png)

**Comment by lguos9960** [comment]
![image](https://user-images.githubusercontent.com/67782322/86452487-f09ad880-bd4e-11ea-8a00-7d44331704cd.png)
![image](https://user-images.githubusercontent.com/67782322/86452809-7028a780-bd4f-11ea-8cb0-40d6f328ebe8.png)
![image](https://user-images.githubusercontent.com/67782322/86452869-859dd180-bd4f-11ea-9099-aea7b7420119.png)
![image](https://user-images.githubusercontent.com/67782322/86453099-d57c9880-bd4f-11ea-90c6-3fab79192454.png)


求教下，如果下拉表格 数据量很大的话，加载非常慢，测试了1万条下拉表格数据 。pulltabledata 是下拉的数据内容，传给下拉组件 EditDownTable。    @xuliangzhan

**Comment by tclqlove** [comment]
> ### （必填）这个需求解决了什么问题
> 项目中需要用到可编辑表格，编辑器为表格拖放选择。
> 动图效果是从别的网站项目中看到的，是否可增加一个类似的表格拖放选择编辑器？
> 实现效果：
> 1.单元格获得焦点后，显示表格拖动选择，选择替换上某条数据，返回此条数据到可编辑表格中
> 。2.在可编辑表格中，手动输入可自动匹配拖放选择表格中的数据，按回车键返回匹配的第一条数据到可编辑表格中。
> 3.表格下拉选编辑器，后边有“选择”按钮，单击选择按钮可以弹出窗口进行选择。
> [点击查看GIF效果](http://static.giteasy.cn/GIF%202020-05-08%2013-10-54.gif)
> 
> ### （必填）请填写问题链接来描述为什么无法实现该功能，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)，[codeandbox](https://codesandbox.io/s/vue-template-916h0)，[jsrun](https://jsrun.pro//vIyKp/edit)）复制链接
> ？
> 
> ### 建议的API是什么样的
> [点击查看GIF效果](http://static.giteasy.cn/GIF%202020-05-08%2013-10-54.gif)
> 
> ### 是否已有其他不错的替代方案
> 目前项目使用的是EasyUi，其中可实现类似的功能。但是效率太慢，太笨重，且UI不太美观。
> 打算替换掉Easyui，因此了解到了此项目。

如果是通过CDN来引入的表格（非vue），该如何使用可编辑渲染器来实现表格选择器？
