### ISSUE TITLE
show-overflow不能正常工作

### ISSUE THREAD

**Issue by yizixu** [x-extends/vxe-table#819]
### （必填）请填写问题描述 Describe the bug
show-overflow不能正常工作。复现条件：1.内容是英文；2.列宽为特定值（具体多少可以通过拖动列宽来复现，下面给了复现链接）；

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link
https://jsfiddle.net/yizixu/36cob1qe/20/

### 填写报错信息或截图 Error message or screenshots
无报错，截图不方便展示

### （必填）请填写期望的结果 Expected behavior
期望鼠标悬浮能正常显示tooltip

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6
- vxe-table: 2.9.6

**Comment by xuliangzhan** [comment]
默认的处理逻辑是无法支持所有场景的，你可以通过全局或局部方式去重写显示方法
https://jsfiddle.net/L8ms3c06/
