### ISSUE TITLE
列 fixed 属性动态变化，界面渲染不符合预期

### ISSUE THREAD

**Issue by yft** [x-extends/vxe-table#823]
### （必填）请填写问题描述 Describe the bug

RT，尝试调用 `recalculate` `refreshColumn` 无效。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/rI2Kp/edit

### 填写报错信息或截图 Error message or screenshots

 无

### （必填）请填写期望的结果 Expected behavior

 希望可以正常更新渲染，或者提供 method 进行更新。

### （必填）请填写版本号 Version

- os & browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- vue: 2.6.11
- vxe-table: 2.9.2

**Comment by xlz26296** [comment]
fixed 是字符串类型，建议去看文档

**Comment by yft** [comment]
_(:з」∠)_   这里是我写错了，不过，fixed 值动态变化，目前似乎是没有做处理的，上述链接示例我更新了，作者大大可以点开看看

**Comment by xuliangzhan** [comment]
你的用法不对 
https://jsrun.net/CTvKp/edit

**Comment by yft** [comment]
感谢大大，(･ิω･ิ)
