### ISSUE TITLE
虚拟滚动会导致show-overflow失效

### ISSUE THREAD

**Issue by jhrxx** [x-extends/vxe-table#828]
### 问题描述 Describe the bug
动态加载数据时，虚拟滚动会导致show-overflow失效 。

### 报错信息或截图 Error message or screenshots
滚动列表动态更新数据
![bad](https://user-images.githubusercontent.com/872413/81894271-f4796c80-95e1-11ea-8cc1-cb568ee99e04.gif)
![good](https://user-images.githubusercontent.com/872413/81894279-f8a58a00-95e1-11ea-8ab1-e0661e71e5ea.gif)

出错的配置:
`
<vxe-table
          max-height="100%"
          :data="tableData"
          show-overflow
          auto-resize
        >
          <vxe-table-column field="id" title="申请单号" min-width="80"></vxe-table-column>
          <vxe-table-column field="siteNames" title="站点名称" min-width="200" :show-overflow="false">
.
.
.
</vxe-table>
`

关闭虚拟滚动问题解决:
`
<vxe-table
          max-height="100%"
          :data="tableData"
          :scroll-y="{gt:-1}"
          show-overflow
          auto-resize
        >
`

### 版本号 Version

- os: windows
- browser: chrome  81.0.4044.138
- vue: 2.6.10
- vxe-table: 2.9.5

**Comment by HongHaiyang** [comment]
我也遇到了，开启虚拟滚动后，哪怕show-overflow设置为 false 也会强制超长省略号了
