### ISSUE TITLE
更改加载中的图片

### ISSUE THREAD

**Issue by alexjlw** [x-extends/vxe-table#831]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 
![image](https://user-images.githubusercontent.com/54834160/82029389-84deac80-96c9-11ea-9203-b21fdb6bb47a.png)
这个该怎么做？

**Comment by netcore-jroger** [comment]
同样需要此功能

**Comment by netcore-jroger** [comment]
为什么不给修改加载logo的机会呢？
