### ISSUE TITLE
全局设置modal不生效

### ISSUE THREAD

**Issue by skyzero110** [x-extends/vxe-table#842]
### （必填）请填写问题描述 Describe
全局设置VXETable.setup中 vxe-table生效,vxe-modal不生效

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

全局设置在一个vxeGloab.js中,main.js中已进行了引用,测试设置为
`VXETable.setup({
    table:{
        size:'mini',
    },
    modal:{
        size:'mini'
   }
});`

vue页面中写了<vxe-table>和<vxe-modal> 结果table生效了,modal怎么都不生效 不知道为什么.

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.9

**Comment by nekorrrr** [comment]
全局设置图标也有这个问题
