### ISSUE TITLE
vxe-talble

### ISSUE THREAD

**Issue by top319VIP** [x-extends/vxe-table#843]
####  我是这就复制这里面的代码进行测试的https://xuliangzhan.github.io/vxe-table/#/table/edit/manual，不编辑没有泄漏，只要编辑输入后保存就会有泄漏

![image](https://user-images.githubusercontent.com/24425777/82538019-a46c4e00-9b7d-11ea-83ec-969bc009b795.png)

**Comment by Sapphire2k** [comment]
最近也遇到 组件销毁了，并不会及时释放内存，导致内存报增，浏览器崩溃
