### ISSUE TITLE
当编辑表格即 edit-config.mode=cell时，在中文输入法状态下的问题

### ISSUE THREAD

**Issue by bensonGithubcom** [x-extends/vxe-table#845]
### （必填）请填写问题描述 Describe the bug
第一次看到这个vue的表格组格，非常的友好和强大！
首次使用，发现这个问题
1. 当编辑表格即 edit-config.mode=cell并且开启键盘导航时，在中文输入法状态下，首个按键被拦截
例如，中五笔输入法状态下，想打【规】字，即五笔编码是【fwm】，结果单元格是【f仙】，
因为f被截获了，后面的【wm】五笔会输出【仙】
拼音状态下存在同样问题。

2. 如果表格增加一个属性设置，按回车键时可以向右移就更好

### （必填）请填写版本号 Version

- os: win10
- browser: Edge
- vue: 2.6
- vxe-table: V3.0

**Comment by yinjisong** [comment]
解决这个问题了大哥

**Comment by gangweihua** [comment]
这个问题解决了吗？

**Comment by xuliangzhan** [comment]
#853
