### ISSUE TITLE
当输入框当类型为【number、integer、float】能否可以隐藏右边的上下微调按钮

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#847]
### 请填写问题描述 Describe

   当输入框当类型为【number、integer、float】能否可以隐藏右边的上下微调按钮，因为有些时候并不需要微调按钮。如图：
![image](https://user-images.githubusercontent.com/4531974/82774949-d0871800-9e78-11ea-9cff-810d51522626.png)

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
那你应该使用 text 去封装自身的业务逻辑

**Comment by jianliulin** [comment]
v2.9.16-beta 已提供此功能，感谢老大！！
