### ISSUE TITLE
关于fixed列与校验联动的BUG问题

### ISSUE THREAD

**Issue by anyclub** [x-extends/vxe-table#849]
### （必填）请填写问题描述 Describe the bug
通常情况下,启用校验函数可自动滚动到报错单元格
当存在fixed时,报错单元格可能被fixed元素遮挡
 

### （必填）请填写能重现问题的链接
![image](https://user-images.githubusercontent.com/19922265/82798068-9cc4e600-9eaa-11ea-8ef3-6b0d26ad8568.png)

http://jsrun.net/fd2Kp/edit

在编辑模式下,1920浏览器可复现次问题, 如无法复现 
调整浏览器宽度即可

### （必填）请填写期望的结果 Expected behavior
校验能自动滚动到可视区域内

**Comment by xuliangzhan** [comment]
这个因为固定列本身也是属于可视区，可视区是以表格宽高为基准，如果激活单元格刚好再固定列下层是会被遮挡的，这个需求工作量较大，目前可能没时间去支持

**Comment by anyclub** [comment]
提了PR,但是是基于3.0 版本改的
期望2.X版本能够更新此功能
