### ISSUE TITLE
vxe-grid高级表格自定义模版slots

### ISSUE THREAD

**Issue by cnbizhh** [x-extends/vxe-table#864]
### （必填）请填写问题描述 Describe
自定义模版 分组列头不能识别
但单列下是可以的
### 请填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/7309951/83377764-37707800-a409-11ea-8265-0171cb9e3d76.png)

![image](https://user-images.githubusercontent.com/7309951/83377728-1740b900-a409-11ea-8a47-79c8f9c38ecd.png)

### （必填）请填写版本号 Version

- os: Win7 x64
- browser: Google Chrome 81.0.4044.122（正式版本） （64 位）
- vue: 2.6.11
- vxe-table: 2.9.6

**Comment by zangtian2** [comment]
+1同样遇到这个问题

**Comment by xuliangzhan** [comment]
建议更新最新版本试试

**Comment by cnbizhh** [comment]
Thanks

**Comment by bosslay** [comment]
https://blog.csdn.net/bosslay/article/details/127401505
