### ISSUE TITLE
数据量大的时候校验卡顿

### ISSUE THREAD

**Issue by liang-louis** [x-extends/vxe-table#866]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 表格嵌套表单，用的是组件的方法。数据有3000条，修改其中的数据，点击保存 ，执行校验的方法等待时间很长

### （必填）请填写问题链接来描述为什么无法实现该功能，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 `
const errMap = await this.$refs.table.$refs.table.fullValidate().catch(errMap => errMap)
`
执行这行代码等待时间过长

### 建议的 API 是什么样的 What does the proposed API look like

 建议优化执行速度

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 无

**Comment by xuliangzhan** [comment]
建议用最新版试试吧

**Comment by liang-louis** [comment]
> 建议用最新版试试吧

这个早升级了 看我提的那俩bug吧
