### ISSUE TITLE
safari上固定列的表格拖动时表头跟随异常

### ISSUE THREAD

**Issue by TenseiWu** [x-extends/vxe-table#867]
### （必填）请填写问题描述 Describe the bug

 通过safari浏览 **固定列的表格**时，横向拖动表格，表头的跟随会延迟

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link
**使用safari打开拖动第一个表格**
 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/fixed

### 填写报错信息或截图 Error message or screenshots

 
![IMG_1125](https://user-images.githubusercontent.com/36643194/83508407-77645780-a4fc-11ea-84df-1b4dd79d9aa4.PNG)

### （必填）请填写期望的结果 Expected behavior

 能与其他浏览器一致

### （必填）请填写版本号 Version

- os: ios 13.1
- browser: safari
- vue: 2.6.11
- vxe-table: 2.9.9

**Comment by xlz26296** [comment]
![image](https://user-images.githubusercontent.com/34787386/83516314-6706a980-a509-11ea-8c72-7f4d01a788a8.png)
