### ISSUE TITLE
请问为什么unpkg和cdnjs都找不到3.x版本，npm install 安装也没有3.x版本

### ISSUE THREAD

**Issue by 99937272** [x-extends/vxe-table#876]
### （必填）请填写问题描述 Describe

请问为什么unpkg和cdnjs都找不到3.x版本，npm install 安装也没有3.x版本

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by 99937272** [comment]
??????不符合要求！！！？？？？老大，我的问题跟本套不了你的提BUG格式，很简单，就是npm install 里面没有3.x版本，文档里却有3.x版本，回应一下有那么难吗
#

**Comment by pharaoh2012** [comment]
我也有同样的疑问，我用select的时候multiple（多选）报错，我看github上是有这个属性的，本地文件没有对应属性，想升级版本，不知道怎么升级。
