### ISSUE TITLE
表格验证参数fullValidate的使用（版本更新后与原使用方式不兼容问题）

### ISSUE THREAD

**Issue by cjill** [x-extends/vxe-table#880]
### （必填）请填写问题描述 Describe

![image](https://user-images.githubusercontent.com/22977781/84358064-2b4e9c80-abf9-11ea-8a36-da390505ace8.png)
这是原来的使用方式：
this.$refs.xTable.validate((valid, errMap) => {
            if (!valid) {
             }
})
根据valid（Boolean类型）进行判断，假如验证不通过使用errMap获取相关错误信息
这是现在的使用方式：
 const errMap = await this.$refs.xTable.fullValidate().catch(errMap => errMap)
              if (errMap) {}else{}
用新版本的vxe-table和原来的使用方式，导致valid不再是Boolean类型，Boolean只有在有错误信息的时候返回错误对象信息，与原来代码的使用方式不兼容，因旧代码要进行改动的话整体维护比较繁琐，是否有其他方式或者做兼容呢？
还有是否有更新文档说明，否则智能根据文档进行查阅，无法知道每个版本之间的更新内容

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

无

### 请填写报错信息或截图 Error message or screenshots

无

### （必填）请填写版本号 Version

- os: window
- browser: Google Chrome  版本 80.0.3987.132（正式版本） （64 位）
- vue: 2.6.11
- vxe-table: 2.9.9

**Comment by xlz26296** [comment]
更新日志都要说明呢，通过参数设置可以继续使用旧校验参数：
```javascript
VXETable.setup({
  validArgs: 'obsolete'
})
```

**Comment by cjill** [comment]
> 更新日志都有说明呢，通过参数设置可以继续使用旧校验参数：
> 
> ```js
> VXETable.setup({
>   validArgs: 'obsolete'
> })
> ```
> 
> 旧版本
> 
> ```js
> // callback
> xTable.validate((vaild, errMap) => {
>   if (errMap) {}
> })
> // promise
> Promise({resolve: void, reject: errMap})
> ```
> 
> 新版本2.9+
> 
> ```js
> // callback
> xTable.validate((errMap) => {
>   if (errMap) {}
> })
> // promise
> Promise({resolve: void, reject: errMap})
> ```

好的。谢谢！在文档里看不到这个参数，在源码里面看到相关的判断了。
![image](https://user-images.githubusercontent.com/22977781/84363108-d31b9880-ac00-11ea-9053-f986500bf45f.png)
只是在未来的3.0中废弃的话，那岂不是对原项目也必须要改动嘛。

**Comment by xlz26296** [comment]
> > 更新日志都有说明呢，通过参数设置可以继续使用旧校验参数：
> > ```js
> > VXETable.setup({
> >   validArgs: 'obsolete'
> > })
> > ```
> > 
> > 
> > 旧版本
> > ```js
> > // callback
> > xTable.validate((vaild, errMap) => {
> >   if (errMap) {}
> > })
> > // promise
> > Promise({resolve: void, reject: errMap})
> > ```
> > 
> > 
> > 新版本2.9+
> > ```js
> > // callback
> > xTable.validate((errMap) => {
> >   if (errMap) {}
> > })
> > // promise
> > Promise({resolve: void, reject: errMap})
> > ```
> 
> 好的。谢谢！在文档里看不到这个参数，在源码里面看到相关的判断了。
> ![image](https://user-images.githubusercontent.com/22977781/84363108-d31b9880-ac00-11ea-9053-f986500bf45f.png)
> 只是在未来的3.0中废弃的话，那岂不是对原项目也必须要改动嘛。

对，要么早点改，要么不要升级v3哈
