### ISSUE TITLE
請問有支持多筆row選取拖拉移動的功能嗎

### ISSUE THREAD

**Issue by HenryLin0914** [x-extends/vxe-table#881]
### （必填）这个需求解决了什么问题 What problem does this feature solve

目前使用第三方sortableJS的row拖拉功能，但僅能單筆拖拉，實際參考該元件是有支持多筆拖拉的

但套用在vxe-table上無效果，我在屬性中有看到 "multiDrag" 這個屬性，但實際使用無效果

是否可提供範例

### （必填）请填写问题链接来描述为什么无法实现该功能，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

sortableJS支援以下方法
![image](https://user-images.githubusercontent.com/30704531/56838060-baa8bd00-684a-11e9-91c6-02439b96d1ba.gif)

### 建议的 API 是什么样的 What does the proposed API look like

sortableJS

### 是否已有其他不错的替代方案 Describe alternatives you've considered

sortableJS

**Comment by xuliangzhan** [comment]
具体兼容性你应该去看 sortableJS 相关用法，该表格目前不会支持拖拽功能
