### ISSUE TITLE
datetime无效？

### ISSUE THREAD

**Issue by gadore** [x-extends/vxe-table#884]
### （必填）请填写问题描述 Describe

 在表格里编辑datetime格式的input时变为纯文本，而不是timepicker

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 http://jsrun.net/KfWKp/edit
我直接使用文档里指向的在线编辑器测试的也不行

### （必填）请填写版本号 Version

- os: windows10
- browser: chrome (newest)
- vue: 2.5.6
- vxe-table: 2.9.9

**Comment by gadore** [comment]
切换到了npm发布的最新版2.9.11，好像问题依然存在

**Comment by xuliangzhan** [comment]
如果使用的是 [input](https://www.runoob.com/tags/att-input-type.html)，那么能不能支持应该去看对应的[文档](https://www.runoob.com/tags/att-input-type.html)，因为这个功能和表格无关

**Comment by gadore** [comment]
> 如果使用的是 [input](https://www.runoob.com/tags/att-input-type.html)，那么能不能支持应该去看对应的[文档](https://www.runoob.com/tags/att-input-type.html)，因为这个功能和表格无关

大师，出问题的是vxe-table-column，
input是我描述不清，不是用的input，
vxe-table-column的type ，我看文档是支持datetime的，但好像失效了。

**Comment by xuliangzhan** [comment]
建议等有重现链接的时候再来问吧 #390
