### ISSUE TITLE
請問有開放checkbox-config="{range: true}" 操作後的event嗎? 

### ISSUE THREAD

**Issue by HenryLin0914** [x-extends/vxe-table#886]
### （必填）请填写问题描述 Describe
1.目前使用range勾選後，@checkbox-change 操作後不會被觸發，請問有其他事件可以用嗎
2.另外當checkbox被disable後，使用range的方法一樣可以將其打勾

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/66756295/84594743-f2c3f280-ae86-11ea-8f11-c38b90974bb8.png)

![image](https://user-images.githubusercontent.com/66756295/84594756-00797800-ae87-11ea-9480-32e7678bffae.png)

### （必填）请填写版本号 Version

- os: win7
- browser: chrome
- vue: 2.6
- vxe-table: 3.x

**Comment by fh345392977** [comment]
希望能增加一个

**Comment by xuliangzhan** [comment]
文档不是有吗 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=range

**Comment by HenryLin0914** [comment]
感謝大神回覆!
