### ISSUE TITLE
行选择启用字段绑定(checkField:'checked'), v-if 显示隐藏表格会导致绑定的字段值都设置为false

### ISSUE THREAD

**Issue by windhuan** [x-extends/vxe-table#888]
### （必填）请填写问题描述 Describe the bug

行选择启用字段绑定(checkField:'checked'), v-if 显示隐藏表格会导致绑定的字段值都设置为false

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 http://jsfiddle.net/L9ng0hbs/

### 填写报错信息或截图 Error message or screenshots

 checked字段数据被修改

### （必填）请填写期望的结果 Expected behavior

v-if 隐藏显示表格后仍然是之前的值

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.9.11

**Comment by xuliangzhan** [comment]
该问题会在 2.9.12 修复 http://jsfiddle.net/xh2ys98r/

**Comment by windhuan** [comment]
> 你应该是穿越的吧，哪来的 2.9.12版本？
> 该问题会在 2.9.12+ 修复 http://jsfiddle.net/xh2ys98r/

好的
