### ISSUE TITLE
需要批量替换功能

### ISSUE THREAD

**Issue by wizardwangbin** [x-extends/vxe-table#889]
### （必填）这个需求解决了什么问题 What problem does this feature solve
在表格中会有相同的数据要进行相同的修改。逐个修改不仅慢，而且容易出错。因此需要类似ctrl + H的批量替换功能。
 ?

### （必填）请填写问题链接来描述为什么无法实现该功能，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link
目前编辑都是针对一行或者一个单元格的，无法对多个不同行的单元格同时进行
 ?

### 建议的 API 是什么样的 What does the proposed API look like
需要一个替换功能的API，给出原字符串和目标字符串。如果能提供全部替换和逐一确认的选项更好。
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered
只能自己在网页上添加控件，然后去修改当前编辑数据集
 ?

**Comment by xuliangzhan** [comment]
这个只有 pro 版本才单元格操作功能，复制粘贴、查找替换等..
