### ISSUE TITLE
vx-ajax遇到跨越问题 怎么设置呢

### ISSUE THREAD

**Issue by cor0ps** [x-extends/vxe-table#891]
### （必填）请填写问题描述 Describe

Access to fetch at 'http://0.0.0.0:5000/api/user/list' from origin 'http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
比如我们前端端口和后端端口不同，需要跨越访问，这个怎么设置呢

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/13083624/85080661-673ac080-b1fc-11ea-9e18-1136c2ef17ff.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
你应该是走错片场了吧
