### ISSUE TITLE
如何实现相同行合并并且相同列也一起合并

### ISSUE THREAD

**Issue by LH040707** [x-extends/vxe-table#907]
**（必填）请填写问题描述或截图**
相同行合并如何同时将相同列一起合并
**（必填）请填在线链接**
http://jsrun.net/7UvKp/edit

**（必填）请填写以下信息：**

- OS: Windows 10
- Browser: 谷歌浏览器
- vue: 2.6.11
- vxe-table: 2.9.14

**Comment by xuliangzhan** [comment]
不管行还是列，合并都是一样的逻辑，准确计算出 rowspan、colspan 就可以合并了

**Comment by LH040707** [comment]
> 不论行还是列，合并都是一样的逻辑，准确计算出rowspan，colspan就可以合并了

不知道如何实现，目前实现了行相同合并，但是在列相同合并的时候不知道如何写

**Comment by xuliangzhan** [comment]
如果想简单点你可以运算出 mergeCells 对象，使用提供的公共方法去合并也行，具体逻辑得应该自行去实现了
https://jsrun.net/wevKp/edit

**Comment by LH040707** [comment]
> 如果想简单点你可以运算出 mergeCells 对象，使用提供的公共方法去合并也行，具体逻辑得应该自行去实现了
> https://jsrun.net/wevKp/edit

这不行，因为数据具体有多少不是固定的很难算出具体合并的行列

**Comment by xuliangzhan** [comment]
> > 如果想简单点你可以运算出 mergeCells 对象，使用提供的公共方法去合并也行，具体逻辑得应该自行去实现了
> > https://jsrun.net/wevKp/edit
> 
> 这不行，因为数据具体有多少不是固定的很难算出具体合并的行列

那你就只能去通过 span-method 方法写复杂的合并逻辑了，再你行 mergeRowMethod 方法的基础上再遍历列的聚合运算，具体得自行去实现了，我目前没时间给你写这个。。。

**Comment by xiaogaofudao** [comment]
@xuliangzhan mergeCell 合并行发现一个小问题。如果开启鼠标 hover 和 current-change 事件。合并的第一行可以通到底，其他行选中的背景色只能是局部，不能一行通到底，有什么方法嘛
