### ISSUE TITLE
调用toggleCollapse()表格高度无法铺满

### ISSUE THREAD

**Issue by huoshidehua** [x-extends/vxe-table#920]
**（必填）请填写问题描述或截图**
在grid外层套了一个div并且高度设置好 调用toggleCollapse()的时候,vxe-grid（height:auto）变成无法铺满屏幕 具体如下：

这是form 未展开状态 此时表格整体位置在这里：
![image](https://user-images.githubusercontent.com/8519297/86309985-f661c280-bc57-11ea-9546-b37e8cda915e.png)
展开后表格整体往下移动 看不到分页 并且出现滚动条，（正常效果应该是表格头部往下移动，并不是整体下移）
![image](https://user-images.githubusercontent.com/8519297/86310080-28732480-bc58-11ea-890f-7241faf07b24.png)

**（必填）请填在线链接**
http://jsrun.net/3PvKp/
http://jsrun.net/3PvKp/edit

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6+
- vxe-table: 2.9.14

**Comment by xuliangzhan** [comment]
如果使用插槽的话，那么你应该自行处理表格的计算更新，可以在折叠完成后调用 recalculate 方法使表格重新计算
http://jsrun.net/PPvKp/

**Comment by huoshidehua** [comment]
> 如果使用插槽的话，那么你应该自行处理表格的计算更新，可以在折叠完成后调用 recalculate 方法使表格重新计算
> http://jsrun.net/PPvKp/

ok没问题了，就是文档有问题： 我调用过这个this.$refs.grid.recalculate() 发现没效果 原来少了个true参数，文档中没有写明改参数
![image](https://user-images.githubusercontent.com/8519297/86315744-e650df80-bc65-11ea-9d52-219d58d08f47.png)

**Comment by xuliangzhan** [comment]
> > 如果使用插槽的话，那么你应该自行处理表格的计算更新，可以在折叠完成后调用 recalculate 方法使表格重新计算
> > http://jsrun.net/PPvKp/
> 
> ok没问题了，就是文档有问题： 我调用过这个this.$refs.grid.recalculate() 发现没效果 原来少了个true参数，文档中没有写明改参数
> ![image](https://user-images.githubusercontent.com/8519297/86315744-e650df80-bc65-11ea-9d52-219d58d08f47.png)

👍文档已更新
