### ISSUE TITLE
前端分页

### ISSUE THREAD

**Issue by xiaofan007** [x-extends/vxe-table#921]
**（必填）这个需求解决了什么问题**
接口一次查询出所有数据，然后在前端进行分页显示。

**建议的 API 是什么样的**

vxePage: { // 是否前端分页
      type: Boolean,
      default: false
    },
如果为true的话，则进行前端分页。

**是否已有其他不错的替代方案**
？暂时没有

**Comment by yizhiyan** [comment]
我也希望前端分页，因为我要处理很多本地数据
