### ISSUE TITLE
[vxe-table] 缺少必要的 "id" 参数，这可能会导致出现错误

### ISSUE THREAD

**Issue by cxy-js** [x-extends/vxe-table#926]
**（必填）请填写问题描述或截图**
把官网的例子复制过来也报这个错
版本时2.9.14

**（必填）请填在线链接**
？

**（必填）请填写期望的结果**
？

**（必填）请填写以下信息：**

- OS: ？
- Browser: ？
- vue: ？
- vxe-table: ？

**Comment by kongruojun** [comment]
我也碰到了，没想到在这里找到4年前的issue.
结论：
我找到的问题点是customConfig这个配置，只要把这个整体注释掉即可让报错停止。
但是我要用下面的checkMethod，所以只能让他继续报错了，并不影响正常使用。
