### ISSUE TITLE
部分全局配置不生效

### ISSUE THREAD

**Issue by mynetfan** [x-extends/vxe-table#927]
**（必填）请填写问题描述或截图**
全局配置中指定的setup.table.emptyRender不能成为组件的默认值。请看codesandbox中的演示，两个gird对比可见，下面的grid在组件中指定了emptyRender属性所以有效，上面的grid应该使用全局配置的，但并没有生效

**（必填）请填在线链接**
https://codesandbox.io/embed/vxe-table-ceshide-demo-mhx6d?fontsize=14&hidenavigation=1&theme=dark

**（必填）请填写以下信息：**

- OS: Any
- Browser: Any
- vue: 2.6.10
- vxe-table: latest

**Comment by xlz26296** [comment]
emptyRender 仅仅是全局参数并非开关，需要在调用时设置 empty-render 为启用状态

```javascript
VXETable.setup({
  table: {
    emptyRender: {
      name: "AEmpty"
    }
  }
})
```
```html
<vxe-table empty-render>
...
</vxe-table>
```

**Comment by Ttou** [comment]
@xlz26296 这个配置是不是对高级表格无效

**Comment by 814992069** [comment]
![image](https://github.com/x-extends/vxe-table/assets/64940341/acebb0ff-4a5e-4126-b443-ecfebc2358d1)
看后面的继承setup.
