### ISSUE TITLE
sort 上排序图表上title属性能否可配置

### ISSUE THREAD

**Issue by chensimin09** [x-extends/vxe-table#932]
**（必填）请填写问题描述或截图**
图上原始title的值可否配置是否要显示，包括显示的值

**（必填）请填在线链接**
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/full

**（必填）请填写以下信息：**

- Browser: chorme
- vue:2.6
- vxe-table: 2.9.14

**Comment by Linya-IronMan** [comment]
可以修改，这个title其实就是dom上的一个属性，直接通过dom更改即可。
vxe-table有没有提供操作的接口，这个就不确定了，找了半天，没有找到。
