### ISSUE TITLE
使用循环产生的vxe-table-column中，若使用sort-method，希望可以传入当前的Column

### ISSUE THREAD

**Issue by sleiphur** [x-extends/vxe-table#937]
**（必填）这个需求解决了什么问题：**
使用循环产生的vxe-table-column中，若使用sort-method，希望可以传入当前的Column；当前的API只传入了prevRow, nexRow，若不传入当前的Column，无法判定当前是哪一列

**建议的 API 是什么样的：**
列的排序方法 Function(prevRow, nexRow,column) 或者Function(prevRow, nexRow,column,property)

**是否已有其他不错的替代方案：**
暂无

**Comment by sleiphur** [comment]
`
<vxe-table-column
                    v-for="(item, key) in gridHeader"
                    :key="key"
                    type="html"
                    :title="item.label"
                    :field="item.property"
                    :fixed="key === 0 ? 'left': null"
                    :visible="key === gridHeader.length - 2 ? false : true"
                    min-width="128"
                    :sortable="key > 0 && key < gridHeader.length - 2 ? true : false"
                    :sort-method="sortMethod"
                  >
                    <template slot-scope="scope">
                      <span v-html="scope.row[scope.column.property]" />
                    </template>
                  </vxe-table-column>
`
此时sortMethod中只能得到prevRow, nexRow，因为是循环产生的column，无法得知这个sortMethod是针对哪一列的，因此希望可以再多传入一个Column，用来判别列

**Comment by yuntao1997** [comment]
你为啥不直接用 table 的sort-change 事件

**Comment by 1008611** [comment]
@sleiphur  给你提供个思路 :sort-method="(a, b) => sortMethod(a, b, item.property)"，但是现在已经废弃了sortMethod。还是用别的吧。
