### ISSUE TITLE
form表单input 类型为date时双向绑定存在bug！！

### ISSUE THREAD

**Issue by huoshidehua** [x-extends/vxe-table#946]
**（必填）请填写问题描述或截图：**
form表单input 类型为date时双向绑定存在bug:手动清空date后获取数据依然存在并不为空，而且这个bug不是必现，但是大多数情况会发生 截图如下：
正常状态
![image](https://user-images.githubusercontent.com/8519297/87744399-652d4700-c826-11ea-909f-69a48e8f0548.png)
接着我把该控件的值手动清空该form表单的值后 仍然可以获取到值 双向绑定失效！！！
![image](https://user-images.githubusercontent.com/8519297/87744604-da991780-c826-11ea-8004-011ce2cd1495.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-sort-ceshide-demo-uqwkp?file=/src/views/Demo1.vue

**（必填）请填写期望的结果：**
input的date类型双向绑定正常工作，目前发现的是date类型，其他类型的表单控件不知道有没有相同的问题

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome 或者 edge(ps:chrome内核)
- vue:2.6+
- vxe-table: 2.9.16beta0

**Comment by huoshidehua** [comment]
手动清空指的不是 点X号清空 是全选内容后 按BACKSPACE键 清空

**Comment by xuliangzhan** [comment]
该问题在 2.9.16-beta.3 中修复 https://codesandbox.io/s/vxe-table-sort-ceshide-demo-1q3q1

**Comment by huoshidehua** [comment]
> 该问题在 2.9.16-beta.3 中修复 https://codesandbox.io/s/vxe-table-sort-ceshide-demo-1q3q1

我升级后发现 依然存在问题 前后两次选择一样的日期发现第二次的选不上去 
用vue-tools调试后 发现一些问题 本地 和 你的 codesandbox上的 属性差了好几个 不知道是不是版本发布问题？
![image](https://user-images.githubusercontent.com/8519297/88501428-67518b80-d006-11ea-884e-09566c03a852.png)

**Comment by huoshidehua** [comment]
解决！
