### ISSUE TITLE
显示隐藏列菜单新增一个筛选框，自动匹配出列

### ISSUE THREAD

**Issue by withyanni** [x-extends/vxe-table#947]
**（必填）这个需求解决了什么问题：**

当前做的需求，类似此链接：http://jsrun.net/TjvKp/edit
有表头分组，最底层是重复的列名如已完成、未完成这种。用户如果只想看已完成，或者想筛选A1列，目前只能一个一个点。

能否在控制显示隐藏列的option里增加一个筛选框，可以直接筛选出符合条件的列名？

**建议的 API 是什么样的：**
如

全部 【筛选框】

|A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp; A1 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;|
|   &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;       已完成|
|  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|

如
|全部                   |
|【筛选框】  &nbsp;&nbsp;  |
|A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp; A1 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;|
|   &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;       已完成|
|  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|

**是否已有其他不错的替代方案：**

如果不提供，只能重新写一个控制隐藏列的option

**Comment by xuliangzhan** [comment]
目前不会支持这种功能
