### ISSUE TITLE
vxe-grid 支持多个row高亮展示吗？

### ISSUE THREAD

**Issue by lengband** [x-extends/vxe-table#948]
**（必填）这个需求解决了什么问题：**
目前的情况是当setCurrentRow(row)执行的时候，上一次被选中的row被取消了

**建议的 API 是什么样的：**
setCurrentRow支持数组，支持setCurrentRow多个row

**是否已有其他不错的替代方案：**
没有

**Comment by xlz26296** [comment]
当前行本身就是一行，要多行就用 checkbox
