### ISSUE TITLE
无法自定义主题样式

### ISSUE THREAD

**Issue by GevinYang** [x-extends/vxe-table#955]
**（必填）请填写问题描述或截图：**
主题样式不加载
@import 'vxe-table/styles/variable.scss';
@import 'vxe-table/styles/modules.scss';

**（必填）请填在线链接：**
http://jsrun.net/tBvKp/edit
[](url)

**（必填）请填写期望的结果：**
正常加载vxe-table/styles/modules.scss、vxe-table/styles/variable.scss并可修改样式

**（必填）请填写以下信息：**

- OS: win10 1909
- Browser: chrome83
- vue: 2.6.10
- vxe-table: 2.9.15

**Comment by 850036165** [comment]
请问怎么修改样式

**Comment by suiyingsky** [comment]
我也遇到了此类问题，导入后找不到模块下的scss文件

**Comment by isolatedchai** [comment]
试试 @import '~vxe-table/styles/variable.scss';
