### ISSUE TITLE
date 在vxe-form表单下样式出错(版本2.9.16.beta2)

### ISSUE THREAD

**Issue by huoshidehua** [x-extends/vxe-table#957]
**（必填）请填写问题描述或截图：**

![image](https://user-images.githubusercontent.com/8519297/88254011-b3db5500-ccee-11ea-9090-98a1682f413f.png)

**（必填）请填在线链接：**
https://jsrun.net/9SvKp/edit

**（必填）请填写期望的结果：**
正常显示控件

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome(edge)
- vue: 2.6
- vxe-table: 2.9.16.beta2

**Comment by xuliangzhan** [comment]
该问题在 2.9.16-beta.3 中修复 https://jsrun.net/EKLKp/edit
