### ISSUE TITLE
导出功能中，部分配置失效

### ISSUE THREAD

**Issue by xiaofan007** [x-extends/vxe-table#959]
**（必填）请填写问题描述或截图：**
1： isFooter 
导出功能的 :export-config  openExport({options})  .exportData({options}) 中， isFooter 属性在有表格有表尾的情况下，设置为false 均无效。

2：data
导出功能的 :export-config  openExport({options})  设置自定义data 不生效。导出的数据还是表格数据。

3：columns 和 columnFilterMethod
导出功能的 :export-config  openExport({options})  设置自定义   columns 和 columnFilterMethod 不生效。弹出的下载框中，仍然显示全部column

![image](https://user-images.githubusercontent.com/55171182/88364453-89080400-cdb5-11ea-85ff-3c3582baa1bb.png)

**（必填）请填在线链接：**

https://jsrun.net/3BWKp/edit

**（必填）请填写期望的结果：**

在导出功能的 :export-config  openExport({options}) 设置中 isFooter  data  columns 和 columnFilterMethod 配置能够生效。

**（必填）请填写以下信息：**

- OS: window10 1909
- Browser: Microsoft Edge  81.0.416.64
- vue: 2.6.11
- vxe-table: 3.4.0

**Comment by xuliangzhan** [comment]
该问题会在 2.9.23+ 修复，https://jsrun.net/Zp6Kp/edit
