### ISSUE TITLE
:mouse-config="{ selected: true, checked: true }" 按住鼠标左键，一直向下拖动，滚动条不会变化

### ISSUE THREAD

**Issue by yan695432** [x-extends/vxe-table#963]
**（必填）这个需求解决了什么问题：**
表格中数据超过一页数据有滚动条时  拉选到底部的时候，滚动条不会自动跟随往下滚动，如果滚动条可自动往下滚动的话，那么就不需要按住鼠标左键+滚轮方式操作

**建议的 API 是什么样的：**
无

**是否已有其他不错的替代方案：**
无

**Comment by xuliangzhan** [comment]
目前版本并没有说明 checked 参数支持使用，如果是想要单元格区域选择/复制/粘贴等功能，只有 pro 版本才支持

**Comment by yan695432** [comment]
那要怎么才能使用pro版本
