### ISSUE TITLE
升级新版本后，点击工具栏上的“列设置”后，出现错误提示“[vxe-table] 工具栏无法关联表格”

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#964]
**（必填）请填写问题描述或截图：**
升级新版本后，点击工具栏上的“列设置”后，出现错误提示  “[vxe-table] 工具栏无法关联表格” ，2.9.3版本不存在这个问题，

通过对比发现，如果获取配置的函数是异步的 ，则会出现这个提示，

![image](https://user-images.githubusercontent.com/4531974/88617357-08087f80-d0c9-11ea-89ea-cb2b9ab7164d.png)

**（必填）请填在线链接：**
https://jsrun.net/LX2Kp/edit

**（必填）请填写期望的结果：**
希望能和v2.9.3版本一样，能正确识别toolbar

**（必填）请填写以下信息：**

- OS:  windows server 2008 R2
- Browser:  chrome
- vue: 2.6.11
- vxe-table: 2.9.15

**Comment by jianliulin** [comment]
速度真快，v2.9.16-beta.4 已经修复，谢谢！！！

**Comment by Luochao0511** [comment]
老是说我id报错 
![image](https://user-images.githubusercontent.com/93471473/157225689-162f445d-d67f-491e-8095-24c4fb6f24b2.png)
