### ISSUE TITLE
(嚴重)table資料導出問題，資料筆數大於100後，導出的資料會變成源數據(文內有執行範例請參考)

### ISSUE THREAD

**Issue by HenryLin0914** [x-extends/vxe-table#967]
**（必填）请填写问题描述或截图：**
導出數據時，當筆數小於100，資料會正常依照畫面上顯示之導出來
當資料筆數大於100，資料導出變成源數據，和顯示的不同

**（必填）请填在线链接：**
筆數200範例:https://jsfiddle.net/e5xwLb7r/
筆數100範例:https://jsfiddle.net/b1om8qcy/

**（必填）请填写期望的结果：**
這BUG有點嚴重，希望可以修正!!
(持續Donate貴團隊，希望越來越強大)

**（必填）请填写以下信息：**

- OS: win7
- Browser: edge
- vue: 2.6.11
- vxe-table: 最新版

**Comment by xuliangzhan** [comment]
插槽模板是不能导出的，你应该使用 formatter 或者 export-method
https://jsfiddle.net/52u9wso7/

**Comment by HenryLin0914** [comment]
了解! 已解決
