### ISSUE TITLE
XEUtils.commafy()  函数四舍五入有误。

### ISSUE THREAD

**Issue by jianliulin** [x-extends/vxe-table#969]
**（必填）请填写问题描述或截图：**
XEUtils.commafy()  函数四舍五入有误，格式化字符也不对
![image](https://user-images.githubusercontent.com/4531974/89166351-80c97900-d5ac-11ea-8281-a1b0511371b4.png)

**（必填）请填在线链接：**
https://jsrun.net/iyLKp/edit

**（必填）请填写期望的结果：**
希望修修正

**（必填）请填写以下信息：**

- OS: Window Server 2008 R2
- Browser: chrome 
- vue: 2.6.11
- vxe-table: 2.9.16-beta.7

**Comment by xuliangzhan** [comment]
你好像走错片场了吧😆

**Comment by jianliulin** [comment]
已修正，谢谢！！
