### ISSUE TITLE
合并单元格并且冻结列 在虚拟滚动时不能共存

### ISSUE THREAD

**Issue by Chenhuif** [x-extends/vxe-table#970]
**（必填）请填写问题描述或截图：**
横向虚拟滚动时，合并单元格和冻结列不能共存
![image](https://user-images.githubusercontent.com/38899782/89167484-0d286b80-d5ae-11ea-824e-c5429b8b2171.png)

![image](https://user-images.githubusercontent.com/38899782/89167466-0699f400-d5ae-11ea-8d28-01cc96603c2e.png)

**（必填）请填在线链接：**
https://codesandbox.io/s/vxe-table-ceshide-demo-ftu5f?fontsize=14&hidenavigation=1&theme=dark

**（必填）请填写期望的结果：**
虚拟滚动时，同时支持合并单元格和冻结列

**（必填）请填写以下信息：**

- OS: windows
- Browser: 谷歌
- vue: 2.5.17
- vxe-table: 2.9.15

**Comment by xuliangzhan** [comment]
虚拟滚动目前不支持合并，你可以关闭虚拟滚动来换取支持合并

**Comment by Chenhuif** [comment]
![image](https://user-images.githubusercontent.com/38899782/89178255-ce031600-d5bf-11ea-8abf-c952d7c3f5f4.png)
 这个if判断不能去掉嘛，因为渲染了上百列，所以不使用虚拟滚动的话，滚动会卡

**Comment by Chenhuif** [comment]
> 虚拟滚动当前不支持合并，您可以关闭虚拟滚动来换取支持合并


![](https://user-images.githubusercontent.com/38899782/89178255-ce031600-d5bf-11ea-8abf-c952d7c3f5f4.png)
这个if判断不能去掉嘛，因为渲染了上百列，所以不使用虚拟滚动的话，滚动会卡

**Comment by oyboyb** [comment]
> v2虚拟滚动不支持合并，只有v3支持虚拟合并，v2中你可以关闭虚拟滚动来换取支持合并

我项目也有这个需求，希望有空能忙

> v2虚拟滚动不支持合并，只有v3支持虚拟合并，v2中你可以关闭虚拟滚动来换取支持合并

什么时候发布V3版本，我们也很虚拟滚动支持合并单元格之类的功能。

**Comment by LiSiQinF** [comment]
这个在v3哪个版本支持

**Comment by lio-mengxiang** [comment]
> 这个在v3哪个版本支持

虚拟滚动不可能同时还支持合并单元格的，原理上就不行。你想，虚拟滚动是一次渲染10行或者20行，假设我要合并列100行，虚拟滚动咋办？除非你一直保留着合并100行的单元格在滚动期间不消失，那么问题来了，它既然不消失，跟虚拟滚动本身的原理渲染部分列表就冲突了

**Comment by oyboyb** [comment]
嗯 ，有道理。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 下午2:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [x-extends/vxe-table] 合并单元格并且冻结列 在虚拟滚动时不能共存 (#970)





  
这个在v3哪个版本支持
  
虚拟滚动不可能同时还支持合并单元格的，原理上就不行。你想，虚拟滚动是一次渲染10行或者20行，假设我要合并列100行，虚拟滚动咋办？除非你一直保留着合并100行的单元格在滚动期间不消失，那么问题来了，它既然不消失，跟虚拟滚动本身的原理渲染部分列表就冲突了

**Comment by LiSiQinF** [comment]
自己写个slots的default样式来模拟合并行或许可以，这种大数据量的最好是做成分页的形式了，如果需要使用到合并那些方法的话
