### ISSUE TITLE
vxe-grid 表格树 修改后新增 保存时无法获取修改的数据

### ISSUE THREAD

**Issue by SmallFlyBird66** [x-extends/vxe-table#978]
**（必填）请填写问题描述或截图：**
vxe-grid 表格树先修改后新增，保存后无法获取修改数据

**（必填）请填在线链接：**
测试项目为发布链接
**（必填）请填写期望的结果：**
希望能够修复或提供解决思路

**（必填）请填写以下信息：**

- OS: mac os
- Browser: 谷歌
- vue:  2.6
- vxe-table: vxe-grid

**Comment by glw116** [comment]
同遇到，解决了吗
