### ISSUE TITLE
vxe-grid 表格树先修改后新增，保存后修改数据无法获取

### ISSUE THREAD

**Issue by SmallFlyBird66** [x-extends/vxe-table#979]
**（必填）请填写问题描述或截图：**
vxe-grid 表格树先修改后新增，保存后修改数据无法获取
**（必填）请填在线链接：**
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/tree/toolbar
**（必填）请填写期望的结果：**
如果时bug希望在版本更新后修复，不是bug希望提供解决思路，谢谢

**（必填）请填写以下信息：**

- OS: mac os
- Browser:谷歌
- vue: 2.6
- vxe-table: vxe-grid

**Comment by xuliangzhan** [comment]
树结构只能操作根节点，深层子节点不能使用内置的 CRUD 管理器，你可以通过数据源的方式去 push 即可
