### ISSUE TITLE
树形表格刷新后保留节点展开状态的功能，在2.9.9版本后失效了

### ISSUE THREAD

**Issue by CoderSunnyLau** [x-extends/vxe-table#982]
**（必填）请填写问题描述或截图：**
树形表格刷新后保留节点展开状态的功能，在2.9.9版本后失效了，之前 2.7 版本曾经实现过该功能。

**（必填）请填在线链接：**
[http://jsrun.net/NfLKp/edit](http://jsrun.net/NfLKp/edit)

**（必填）请填写期望的结果：**
刷新后还可保留之前节点的展开状态

**（必填）请填写以下信息：**

- OS: MacOs High Sierra
- Browser: Chrome
- vue: 2.x
- vxe-table: 2.9.9~2.9.15

**Comment by xuliangzhan** [comment]
如果改变了源，可以通过设置 reserve 去保留状态

**Comment by 850036165** [comment]
同，设置 reserve了但是没有保留展开状态，数据源是用vxegrid托管的

**Comment by 850036165** [comment]
@xuliangzhan 演示http://jsrun.net/JY6Kp

**Comment by xuliangzhan** [comment]
> @xuliangzhan 演示http://jsrun.net/JY6Kp

这没看出有什么问题

**Comment by 850036165** [comment]
@xuliangzhan 我设置表格 expandAll: true, reserve: true，点击一个表格收起的时候，再reload，表格又变成了展开状态，如果是reserve的话应该收起状态的表格保持不变吧。

**Comment by xuliangzhan** [comment]
> @xuliangzhan 我设置表格 expandAll: true, reserve: true，点击一个表格收起的时候，再reload，表格又变成了展开状态，如果是reserve的话应该收起状态的表格保持不变吧。

@850036165  文档应该写得很清楚的吧，reload 行为是会重置状态的
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?q=loadData

**Comment by 850036165** [comment]
@xuliangzhan 谢谢指导，应该是用query不是reload

**Comment by UnicornXU** [comment]
> @xuliangzhan 谢谢指导，应该是用query不是reload

query是哪个?api没得,大佬请赐教
