### ISSUE TITLE
vxe-grid filterConfig.remote===true 时，filter变化时将内置分页重置为1

### ISSUE THREAD

**Issue by fh345392977** [x-extends/vxe-table#992]
**（必填）这个需求解决了什么问题：**
有时候会浏览到后面页数时才开始使用filter，这时页数不会回到1，导致看不到数据
假设浏览器第6页，filter过滤后的数据只有2页，那么底部分页显示为 6/2，且显示表格数据为空，如果能回到第1页，就能看到数据。

同样的情况也出现在sort中，希望能增加`resetPage`属性，增强`gridOptions`的实用性。

**建议的 API 是什么样的：**
在`filterConfig`里增加一个配置，`resetPage:true` ,那么过滤后页码回到1

**是否已有其他不错的替代方案：**
有替代方案，但很麻烦，分页和表格数据都需要自行维护，无法像`gridOptions`那样方便

**Comment by xuliangzhan** [comment]
远程筛选和排序的行为是应该重置为第一页的，会在下版本修复
